-- BATCH 적재 SQL — BATCH-R1 (2026)
-- 출처: batch-R1-knowledge-graph.json
-- 노드: 24 / 엣지: 43 / 산식: 0 / 상수: 20
-- 적용: wrangler d1 execute <db-name> --file=<this-file> --remote
-- 사전 의무: migration 0019 production 적용 완료
-- 멱등성: INSERT OR IGNORE — 재실행 시 충돌 없음
--
-- AI 생성 데이터 (CLAUDE.md Hard Limit) — status='draft' 만 INSERT
-- 진산님 검수 후 status_transitions UPDATE 로 review/approved 전이
--
-- 주의: D1 wrangler execute --file 은 전체 파일을 자동 트랜잭션으로 감싼다.
-- 명시 BEGIN TRANSACTION/COMMIT 은 D1 거부 (Durable Object 충돌). 의도적으로 생략.

-- 1. knowledge_nodes (24 rows)
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-154', 'CONCEPT', '[26년 개정] 농작물재해보험 가입기준 (보험가입금액)', '26년 개정 정합. 2025년 기준 ① 200만원 이상: 사과·배·단감·떫은감·감귤·포도·복숭아·자두·살구·매실·참다래·대추·유자·무화과·밤·호두·마늘·양파·감자·고구마·고추·양배추·브로콜리·오미자·복분자·오디·인삼·수박(노지)·두릅·블루베리. ② 100만원 이상: 옥수수·콩·팥·배추·무·파·단호박·당근·시금치(노지)·양상추. ③ 50만원 이상: 벼·밀·보리·메밀·귀리. ④ 비가림시설 200㎡ 이상 (포도·대추·참다래). ⑤ 농업용 시설물·시설작물·버섯재배사 단지 면적 300㎡ 이상. ⑥ 1,000㎡ 이상: 차·조사료용 벼·사료용 옥수수. + 신규 종합위험: 녹두·생강·참깨·종합위험 사과배단감떫은감.', '농작물재해보험 공통', NULL, NULL, 'p.1', 1, 1, '26년 개정사항 정리', '1. 가입기준 (구교재 P25)', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-155', 'CONCEPT', '[26년 개정] 보장 재해 추가 (사과 탄저병/가을배추 무름병/원예시설 일조량 부족)', '26년 개정. 사과 = 자연재해성 탄저병 추가 (피해율 = 평수미/평 산정, 피해인정계수 1.0/0.5는 최종수정본 3.31에서 삭제). 가을배추 = 자연재해성 무름병 추가 (단 수입안정보장 제외). 원예시설작물 (버섯 제외) = 농작물재해보험 사업시행지침에 따라 인정된 일조량 부족 추가. 구교재 P89.', '농작물재해보험 공통', NULL, NULL, 'p.1', 1, 1, '26년 개정사항 정리', '2. 보장하는 재해 (구교재 P89)', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-156', 'CONCEPT', '[26년 개정] 자기부담비율 최소 20%형 / 15%형 추가', '26년 개정. 최소 20%형 추가 = 유자·호두·귀리·두릅·블루베리·수박·녹두·생강·참깨·고랭지당근·간척농지(벼/조사료용벼)·가을배추·가을무·양상추·쪽파·봄배추·농업수입안정보장(포도/복숭아/만감류/단감/고구마/양배추/봄감자/가을감자). 최소 15%형 추가 = 농업수입안정보장 (1) 복수농지가입(벼 7개+/콩 4개+) (2) 채소가격안정제(마늘/양파/가을배추/가을무/고랭지배추/고랭지무/고랭지감자) (3) 벼재배면적감축(콩/보리/옥수수). 구교재 P91.', '농작물재해보험 공통', NULL, NULL, 'p.2', 2, 2, '26년 개정사항 정리', '3. 자기부담비율 (구교재 P91)', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-157', 'CONCEPT', '[26년 개정] 정부지원비율 (보장수준별 %) 최종공지 변경', '26년 개정 (3.31 최종 공지, 2.25 1차 공지와 다름). 사과·배·단감·떫은감·벼: 60%(65) / 70%(60) / 80%(50) / 85%(38) / 90%(33). 콩·감자·고구마·보리·옥수수·마늘·양파·양배추·포도·배추·무·복숭아·만감류: 60%(60) / 70%(55) / 80%(50) / 85%(48) / 90%(47). 농업수입안정보장 — 복수농지/전략작물직불금/채소가격안정제 65/60/50/48/-. 단감·포도·만감류·복숭아·고구마·양배추(가을월동)·감자(봄가을): 60/55/50/-/-. 배추·무 = 계절 구분 없음. 구교재 P105.', '농작물재해보험 공통', NULL, NULL, 'p.2', 2, 2, '26년 개정사항 정리', '4. 정부지원비율 (구교재 P105)', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-158', 'CONCEPT', '[26년 개정] 손해율 따른 할인할증률 (5년 손해율 20% 미만 -30%)', '26년 개정. 평가기간 5년·손해율 20% 미만 = -30% 할인 (기존 -25% → -30%). 5년 가입자에 최대 할인 적용. 보험료 산식 변경 (구교재 P133): 변경전 = (1+방재시설할인율) × ... / 변경후 = (1-방재시설할인율) × ... — 부호 반전. 5단계 평가기간 × 손해율 12구간 매트릭스. 구교재 P97.', '농작물재해보험 공통', NULL, NULL, 'p.3', 3, 3, '26년 개정사항 정리', '5. 손해율에 따른 할인 할증율 (구교재 P97)', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-159', 'CONCEPT', '[26년 개정] 종합위험 수확감소보장 과수4종 보험기간 통일', '26년 개정. 사과·배·단감·떫은감 4종 모두 — 종합위험 수확감소보장 보험기간 = 계약체결일 24시 ~ 수확기 종료 시점 (이듬해 11월 20일 초과 X). 종합위험 나무손해보장 = 이듬해 2월 1일 ~ 이듬해의 다음해 1월 31일. 즉 과실 = 11/1~이듬 11/20 / 나무 = 이듬 2/1~이듬다음해 1/31.', '전기간 종합위험 과수4종', NULL, NULL, 'p.3', 3, 3, '26년 개정사항 정리', '6. 전기간 종합위험 수확감소보장 과수4종', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-160', 'CONCEPT', '[26년 개정] 감귤(온주밀감) 수확기 잔존비율 산식 변경', '26년 개정. 새 산식: 12월 = (100-39) - (0.935 × 사고일자) / 1월 = (100-68) - (0.774 × 사고일자) / 2월 = (100-92) - (0.286 × 사고일자). 사고 발생일자 = 해당 월의 사고 발생일자. 구교재 P144 수정.', '종합위험 감귤(온주밀감) 과실손해', NULL, NULL, 'p.4', 4, 4, '26년 개정사항 정리', '7. 감귤(온주밀감) 수확기 잔존비율', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-161', 'CONCEPT', '[26년 개정] 블루베리 과실손해피해율 산출식 수정 (괄호 오류 정정)', '26년 개정 (이론서 괄호 오류 수정). ① 꽃 피해조사 미실시 시 = 과실손해피해율 × (1 - 미보상비율). ② 꽃 피해조사 실시 시 = 최종 꽃 피해율 + {(1 - 최종 꽃 피해율) × 과실손해피해율 × (1 - 미보상비율)}. ③ 과실손해피해율 = (∑재배종별·수령별 고사주수÷실제결과주수 × 재배종별 잔여수확량비율) + {(재배종별·수령별 조사대상주수÷실제결과주수) × (∑재배종별·수령별 표본가지 피해과실수 × 재배종별잔여수확량비율) ÷ ∑재배종별·수령별 표본가지 전체 과실수}. 구교재 P145 수정.', '종합위험 과실손해 블루베리', NULL, NULL, 'p.4', 4, 4, '26년 개정사항 정리', '8. 블루베리 과실손해피해율', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-162', 'CONCEPT', '[26년 개정] 적과전 종합위험 — 상한 적용 5년 중 3년 가입 이력', '26년 개정 (구교재 P120). 적과전 종합위험 상한 적용 = 가입 당해 포함 과거 5개년 중 3년 이상 가입 이력 과수원에 한하여 적용. 적용 가능 예시: 2022(O)·2024(O)·2026(O) → 3년 가입 완료 (상한 적용 대상). 적용 불가 예시: 2025(O)·2026(O) → 2년 가입 (상한 적용 제외).', '적과전 종합위험 II', NULL, NULL, 'p.4', 4, 4, '26년 개정사항 정리', '9. 25년 논란부분 정리', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-163', 'CONCEPT', '[26년 개정] 온주밀감 방재시설 — 동상해 특약 산출에만 적용', '26년 개정 (구교재 P99). 온주밀감 방상팬·서리방지 미세살수장치 할인율 = 동상해 특약 가입 시 동상해특약보험료 산출에만 적용. 과실손해보장·과실손해추가보장에는 적용 X.', '종합위험 감귤(온주밀감) 과실손해', NULL, NULL, 'p.4', 4, 4, '26년 개정사항 정리', '9. 25년 논란부분 정리', 'BATCH-R1', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-164', 'CONCEPT', '[26년 개정] 단기요율 — 화재·화재대물배상책임 특약 가산 X', '26년 개정 (구교재 P207). 단기요율 = 1·2·3·6·7·8·9·11·12월이 포함될 때 각 월마다 10% 가산. 단 화재 및 화재대물배상책임특약은 가산 X.', '농작물재해보험 공통', NULL, NULL, 'p.4', 4, 4, '26년 개정사항 정리', '9. 25년 논란부분 정리', 'BATCH-R1', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-165', 'CONCEPT', '[26년 개정] 평년수확량 산정 변경사항 (품목별)', '26년 개정. 1) 유자(7년 중 4년 이상) = min{max(산출 평년수확량, 7년 과거수확량 올림픽평균값), 표준수확량 130%}. 2) 포도·복숭아 평년수확량 = 표준수확량 130% 한도 미적용 (밤·블루베리·무화과 삭제). 3) 과수4종 = 적과전종합위험 평년착과량 산정 준용 (수확전 착과수조사값을 적과후 착과수로 대체). 4) 오디 = B값 = 평균 X = 품종별 표준결실수. 5) 복분자 = 평년결과모지수 = 표준결과모지수 130% 한도 (기존 50~130%에서 130%만). 6) 팥·살구 = 신규가입 시 표준수확량 70% (유자 삭제). 7) 밀 = 벼 산식 동일 적용.', '농작물재해보험 공통', NULL, NULL, 'p.5', 5, 5, '26년 개정사항 정리', '10. 평년수확량', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-166', 'CONCEPT', '[26년 개정] 벼·밀 평년수확량 산식 + 가입수확량', '26년 개정. 평년수확량 = [A + (B×D - A) × (1 - Y/5)] × C / D. A = 과거 5년 수확량 합 ÷ Y. B = 가입연도 지역별 기준수확량. C = 가입연도 보정계수 (가입년도 품종·이앙일자·친환경재배 보정계수 곱). D = 과거 5년 보정계수 합 ÷ Y. Y = 과거수확량 산출연도 횟수 (가입횟수). 평년수확량 ≤ 표준수확량의 130%. 조사료용 벼 제외. 가입수확량 = 평년수확량의 50~100% (5% 단위 리·동별 선정 가능). 구교재 P163.', '종합위험 수확감소보장 벼·밀', NULL, NULL, 'p.5', 5, 5, '26년 개정사항 정리', '10. 평년수확량', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-167', 'CONCEPT', '[26년 개정] 밭작물 신규 품목 + 보장방식 변경', '26년 개정 (구교재 P164). 신규 종합위험 수확감소보장 = 녹두·생강·참깨. 보장방식 변경 (생산비 → 수확감소): 가을배추(일반·병충해보장형)·가을무(일반)·단호박·당근(고랭지·가을·월동). 계절 구분 = 양배추(가을·월동)·당근(고랭지·가을·월동) — 계절별 분리.', '종합위험 수확감소 밭작물', NULL, NULL, 'p.6', 6, 6, '26년 개정사항 정리', '11. 밭작물 품목 추가 및 보장방식', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-168', 'CONCEPT', '[26년 개정] 재파종·재정식 보장 품목 + 보험금 산식', '26년 개정 (구교재 P187). 재파종 보장 = 당근(고·가·월) 15% / 가을감자·가을무 20% / 마늘(난지형만) 35% × 표준피해율. 재정식 보장 = 단호박·가을배추(일반·병충해)·양파·양배추(가을·월동) 20% × 면적피해율. 한지형 마늘 = 재파종 X (난지형만). 종기파종 보험금 (제주 남도종 마늘) = 보험가입금액 × 25% × 표준 피해율 (10a 기준 = (30,000-식물체주수) ÷ 30,000). 지급사유 = 면적피해율 자기부담 초과 또는 식물체주수 30,000 미만 → 30,000 이상 재파종.', '종합위험 수확감소 밭작물', NULL, NULL, 'p.6', 6, 6, '26년 개정사항 정리', '12. 재정식·재파종', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-169', 'CONCEPT', '[26년 개정] 수확감소 밭작물 보험기간 — 개시일·종료일·재파종/재정식 한계일', '26년 개정 (구교재 P171). 1) 계약24시 개시: 녹두·차·고랭지감자·옥수수·콩·팥·마늘·양파·고구마·생강. 2) 정식·파종완료일24시 (한계일 초과 X): 단호박(5/29)·수박(5/31)·고랭지당근(5/31)·참깨(6/20)·가을월동당근(8/31)·가을배추(9/10)·가을무(9/15)·양배추가을월동(9/30). 3) 정식·파종완료일24시 (경과 시 계약24시): 봄감자·가을감자. 재파종 한계일: 고랭지당근 5/31, 가을월동당근 8/31, 가을감자 9/15, 가을무 9/25, 마늘 10/31. 재정식 한계일: 단호박 5/31, 가을배추 9/20, 가을월동양배추 10/15, 양파 11/21. 경작불능 종료일 = 수확개시 시점 (콩·팥 변경). 수확감소 종료일: 봄감자 7월·수박 8/10·단호박 8/27·옥수수 9월·참깨 10/20·고당 10/20·고구마 10·고랭지감자 10·생강 11/10·팥 11/13·녹두 11/15·콩·가을양배추·가을감자 11·제주 가을감자 12/31·가을배추 12/15·가을무 12/15·이듬해 가월당 2·극조생/조생 월동양배추 2·중생 월동양배추 3/15·만생 월동양배추 3·차 5(전북 외 10일/전북 20일)·마늘·양파 6.', '종합위험 수확감소 밭작물', NULL, NULL, 'p.7', 7, 7, '26년 개정사항 정리', '13. 수확감소 밭작물 보험기간', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-170', 'CONCEPT', '[26년 개정] 인삼·해가림시설 — 1·2형 통합 + 보험료 할인', '26년 개정 (구교재 P177-180). 인삼 보험기간 = 1형·2형 구분 X (통합 운영). 청약 승낙 + 1회 보험료 납입 시점 (5/1 이전 가입 시 5/1). 보험증권 기재 보장종료일 (6년근 = 판매개시연도 10/31 초과 X). 연근별 보상가액 = 인삼 보험가입금액 = 재배면적 × 단위면적당 연근별보상가액. 단위면적당 연근별보상가액 = 계약체결시점 직파(만나이+1년)·이식(만나이+2년). 인삼 보험료 = 가×요×손×방 (관수시설 5% 할인). 해가림시설 보험료 = 가×요×종별요율×6년근재배 해가림시설 10% 할인. 종별요율: 2종 0.9 / 3종 1.0 / 4종 1.1 / 5종 1.2.', '작물특정 인삼·해가림시설', NULL, NULL, 'p.8', 8, 8, '26년 개정사항 정리', '14. 인삼·해가림시설', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-171', 'CONCEPT', '[26년 개정] 준비기생산비계수 + 손해정도비율 20→10% 변경', '26년 개정 (구교재 P189-212). 고추 준비기생산비계수 54.2% / 표준생장일수 풋고추 70일·홍고추 100일 / 수확종료일 정식일+150일 초과 X. 브로콜리 67.1%. 백합·국화·카네이션 재절화 시 20%. 버섯: 표고(톱밥배지) 81.4% / 느타리(균상재배) 69.7% / 양송이(균상재배) 70.3%. 느타리(병재배) 경과비율 = 88.7% (일자 무관). 새송이(병재배) 경과비율 = 91.7% (일자 무관). 손해정도비율 = 생산비보장(노지) + 시설작물 = 20% 구간 → 10% 구간 변경 (단 2-1 버섯 제외). 브로콜리 = 정상·50%·80%·100% 4단계.', '종합위험 시설작물·생산비보장', NULL, NULL, 'p.9', 9, 9, '26년 개정사항 정리', '15. 준비기생산비계수', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-172', 'CONCEPT', '[26년 개정] 농업수입안정보장 가격조항 — 품목 추가 + 산식', '26년 개정 (구교재 P228-235). 추가 품목 = 고랭지(배추·무) + 가을(배추 일반/병충해보장 제외, 무 일반) + 단감·만감류·복숭아·벼. 백태/서리태: 기준가격 = 과거 5년 연도별 『상품』 평균가격 올림픽평균 - 가장 최근 연도 유통비용. 수확기가격 = 수확연도 『상품』 평균가격 - 최근 유통비용. 흑/벼/마/나/보/고감: 기준가격 = 과거 5년 평균 매입(수매)가격 올림픽평균. 수확기가격 = 수확연도 평균 매입가격. 나머지: 기준가격 = 과거 5년 연도별 중품·상품 올림픽평균 - 최근 유통비용. 수확기가격 = 수확연도 중품·상품 - 최근 유통비용. 가중평균: 1농지에 기준가격 2개+ 시 수확량/면적 비율로 가중평균.', '농업수입안정보장', NULL, NULL, 'p.9', 9, 9, '26년 개정사항 정리', '16. 농업수입안정보장 가격조항', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-173', 'CONCEPT', '[26년 개정] 농업수입안정보장 보험금 — 과거수입형/기대수입형 (옥수수 별도)', '26년 개정 (구교재 P226). 옥수수 외 — 과거수입형: 보험금 = 보험가입금액 × (피해율 - 자기부담비율) / 피해율 = (기준수입 - 실제수입) ÷ 기준수입 / 기준수입 = 평년수확량 × 기준가격 / 실제수입 = (수확량 + 미보상감수량 - 병충해감수량 복숭아·감자만) × 수확기가격. 기대수입형: 보험금 = 기준수입 × (피해율 - 자기부담비율) / 기준수입 = 평년수확량 × max[기준가격, 수확기가격] (수확기가격은 기준가격의 150% 초과 X). 옥수수: 과거수입형 보험금 = 보험가입금액 × (피해율 - 자기부담비율). 옥수수 손해액 (이론서) — 기준≥수확기: (기준-수확기) × (평년-피해) + (기준×피해), 기준<수확기: 기준×피해. 약관과 이론서 산식 차이 주의.', '농업수입안정보장', NULL, NULL, 'p.10', 10, 10, '26년 개정사항 정리', '17. 농업수입안정보장 보험금', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-174', 'CONCEPT', '[26년 개정] 인수제한 — 과수4종 나무수령 + 비가림 + 호두 + 보리·밀·귀리 + 마늘 피복 + 출현율 80%', '26년 개정. 적과전종합위험 과수4종 나무수령: 다축재배 = 밀식과 동일 3년 미만 인수제한. 전기간 종합위험 과수4종: 사과 — 밀식 2년/반밀식 3년/일반 4년/다축재배 2년 미만 / 배 — 2년 미만 / 단감 — 4년 미만. ※ 가입년도 기준이라 적과전종합위험보다 1년 적음. 다축재배 인수제한: 지지대+관수시설 모두 설치 필수 (미설치 = 밀식으로 가입). 비가림시설 = 폭 2.5m±20% / 동고 2.75m±15% 범위 벗어나면 제한. 호두 = 실생묘 8년 미만 또는 신령 접목묘 6년 미만 (왜성호두 등 신령 외 품종 제한). 보리 파종 = 11/27 이후 / 밀·귀리 = 11/20 이후 인수제한. 마늘 = 대서종 무멀칭 시범사업 지역 內 12/15~1월말 피복 필수 (남부 23개 지역 제외). 출현율 80% 미만 인수제한 품목: 마늘·당근(고가월)·감자·고구마·옥수수·콩·팥·수박·생강·녹두·참깨·가을무·단호박·메밀·시금치(노지)·무·쪽파. 차 = 전남·경남 외 + 전북지역 (5/20 이후 가능).', '농작물재해보험 공통', NULL, NULL, 'p.11', 11, 11, '26년 개정사항 정리', '18. 인수제한', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-175', 'CONCEPT', '[26년 개정] 인수제한 — 녹두·참깨·생강 (신규 품목 상세 조건)', '26년 개정. 녹두 인수제한: 일시(기계)수확 X / 보험가입면적 300㎡ 미만 / 출현율 80% 미만 / 보험계약 시 피해 확인 / 재식밀도 16,000주/10a 미만. 참깨 인수제한: 보험가입면적 300㎡ 미만 / 재식밀도 7,000주/10a 미만 / 다른작물 혼식 / 4/16 이전 또는 6/20 이후 파종 / 출현율 80% 미만 / 전작 들깨·참깨 재배 / 피해 확인 / 시험연구·도시계획 편입. 생강 인수제한: 보험가입면적 300㎡ 미만 / 출현율 80% 미만 / 4/15~5/20 외 파종 / 전년 동일 농지 생강 재배 (연작) / 직전 4년 병충해 피해 / 재식밀도 5,550주/10a 미만 / 관수시설 미설치 (물호스는 인정 X) / 다른 작물 혼식 / 시험연구·도시계획 편입.', '종합위험 수확감소 밭작물', NULL, NULL, 'p.12', 12, 12, '26년 개정사항 정리', '18. 인수제한', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-176', 'CONCEPT', '[26년 개정] 가축재해보험 — 소 1년 이내 출하 가입조건 + 국고지원율', '26년 개정 (구교재 P286). 소 = 1년 이내 출하예정인 경우 일부 가입 가능 — 신규가입자·손해율 130% 초과자 = 소이력제 현황의 전부 가입 / 손해율 130% 이하자 = 80% 이상 가입. 총 보험료의 50% 국고지원 — 손해율 500% 초과 ''소'' 농가의 경우 국고지원 비율 차등화 50% → 40%.', '가축재해보험', NULL, NULL, 'p.12', 12, 12, '26년 개정사항 정리', '19. 가축', 'BATCH-R1', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-177', 'CONCEPT', '[26년 개정] 농어업재해보험 26년 개정사항 정리 — 전체 19개 항목', '2026년 시행 농작물재해보험 + 가축재해보험 개정사항 통합. 한종찬 교수 정리본 (2026-03-31 기준). 19개 변경 항목: 1) 가입기준 + 신규 종합위험 (녹두·생강·참깨·과수4종) / 2) 보장재해 추가 (사과 탄저병, 가을배추 무름병, 원예시설 일조량) / 3) 자기부담비율 / 4) 정부지원비율 (3.31 최종) / 5) 손해율 할인 -25→-30% / 6) 과수4종 보험기간 통일 / 7) 감귤 잔존비율 / 8) 블루베리 산식 / 9) 25년 논란부분 / 10-11) 평년수확량 + 밭작물 추가 / 12-13) 재정식·재파종 + 보험기간 / 14) 인삼·해가림시설 통합 / 15) 준비기생산비계수 + 손해정도비율 20→10% / 16-17) 농업수입안정 가격조항 + 보험금 / 18) 인수제한 / 19) 가축. BATCH-1~5 + BATCH-6 적재 시점에 일부 정합 반영됨 (손해정도비율 / 가을무·감자 재파종 / 신규품목 / 인삼·해가림시설). 본 BATCH-R1 = 19개 항목 명시 학습 객체화.', '농작물재해보험 + 가축재해보험 공통', NULL, NULL, 'p.1', 1, 1, '26년 개정사항 정리', '전체', 'BATCH-R1', 2026, 10, 'draft');

-- 2. formulas (0 rows, INSERT OR IGNORE — 기존 등록 row 보존)

-- 3. constants (20 rows, INSERT OR IGNORE)
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-143', 'ratio', '26년 손해율 5년 20%미만 최대 할인율 (-)', '0.30', 0.3, '26년 손해율 5년 20%미만 최대 할인율 (-)', 'p.3', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-144', 'ratio', '26년 정부지원 사과배단감떫은감벼 60% 보장수준', '0.65', 0.65, '26년 정부지원 사과배단감떫은감벼 60% 보장수준', 'p.2', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-145', 'ratio', '26년 정부지원 사과배단감떫은감벼 90% 보장수준', '0.33', 0.33, '26년 정부지원 사과배단감떫은감벼 90% 보장수준', 'p.2', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-146', 'ratio', '26년 종기파종 보험금율 (제주 남도종 마늘)', '0.25', 0.25, '26년 종기파종 보험금율 (제주 남도종 마늘)', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-147', 'ratio', '26년 마늘(난지형) 재파종 보험금율', '0.35', 0.35, '26년 마늘(난지형) 재파종 보험금율', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-148', 'ratio', '26년 당근 재파종 보험금율', '0.15', 0.15, '26년 당근 재파종 보험금율', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-149', 'threshold', '26년 종기파종 표준피해율 분모 (10a 30,000주)', '30000', 30000.0, '26년 종기파종 표준피해율 분모 (10a 30,000주)', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-150', 'ratio', '26년 인삼 관수시설 보험료 할인율', '0.05', 0.05, '26년 인삼 관수시설 보험료 할인율', 'p.8', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-151', 'ratio', '26년 해가림시설 6년근재배 보험료 할인율', '0.10', 0.1, '26년 해가림시설 6년근재배 보험료 할인율', 'p.8', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-152', 'coefficient', '26년 고추 준비기생산비계수', '0.542', 0.542, '26년 고추 준비기생산비계수', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-153', 'coefficient', '26년 브로콜리 준비기생산비계수', '0.671', 0.671, '26년 브로콜리 준비기생산비계수', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-154', 'coefficient', '26년 표고버섯 톱밥배지 준비기생산비계수', '0.814', 0.814, '26년 표고버섯 톱밥배지 준비기생산비계수', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-155', 'coefficient', '26년 느타리(균상재배) 준비기생산비계수', '0.697', 0.697, '26년 느타리(균상재배) 준비기생산비계수', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-156', 'coefficient', '26년 양송이(균상재배) 준비기생산비계수', '0.703', 0.703, '26년 양송이(균상재배) 준비기생산비계수', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-157', 'ratio', '26년 느타리(병재배) 경과비율 고정', '0.887', 0.887, '26년 느타리(병재배) 경과비율 고정', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-158', 'ratio', '26년 새송이(병재배) 경과비율 고정', '0.917', 0.917, '26년 새송이(병재배) 경과비율 고정', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-159', 'ratio', '26년 농업수입안정 기대수입형 수확기가격 한도 (기준가격 배수)', '1.50', 1.5, '26년 농업수입안정 기대수입형 수확기가격 한도 (기준가격 배수)', 'p.10', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-160', 'ratio', '26년 가축재해보험 소 손해율 130% 초과 가입 비율', '1.00', 1.0, '26년 가축재해보험 소 손해율 130% 초과 가입 비율', 'p.12', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-161', 'ratio', '26년 가축재해보험 소 손해율 130% 이하 가입 비율 최저', '0.80', 0.8, '26년 가축재해보험 소 손해율 130% 이하 가입 비율 최저', 'p.12', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-162', 'ratio', '26년 가축재해보험 소 손해율 500% 초과 국고지원율', '0.40', 0.4, '26년 가축재해보험 소 손해율 500% 초과 국고지원율', 'p.12', 2026);

-- 4. knowledge_edges (43 rows) — nodes 적재 후
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0001', 'CONCEPT-177', 'CONCEPT-154', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0002', 'CONCEPT-177', 'CONCEPT-155', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0003', 'CONCEPT-177', 'CONCEPT-156', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0004', 'CONCEPT-177', 'CONCEPT-157', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0005', 'CONCEPT-177', 'CONCEPT-158', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0006', 'CONCEPT-177', 'CONCEPT-159', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0007', 'CONCEPT-177', 'CONCEPT-160', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0008', 'CONCEPT-177', 'CONCEPT-161', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0009', 'CONCEPT-177', 'CONCEPT-162', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0010', 'CONCEPT-177', 'CONCEPT-163', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0011', 'CONCEPT-177', 'CONCEPT-164', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0012', 'CONCEPT-177', 'CONCEPT-165', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0013', 'CONCEPT-177', 'CONCEPT-166', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0014', 'CONCEPT-177', 'CONCEPT-167', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0015', 'CONCEPT-177', 'CONCEPT-168', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0016', 'CONCEPT-177', 'CONCEPT-169', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0017', 'CONCEPT-177', 'CONCEPT-170', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0018', 'CONCEPT-177', 'CONCEPT-171', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0019', 'CONCEPT-177', 'CONCEPT-172', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0020', 'CONCEPT-177', 'CONCEPT-173', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0021', 'CONCEPT-177', 'CONCEPT-174', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0022', 'CONCEPT-177', 'CONCEPT-175', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0023', 'CONCEPT-177', 'CONCEPT-176', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0024', 'CONCEPT-171', 'CONCEPT-081', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0025', 'CONCEPT-168', 'F-71', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0026', 'CONCEPT-167', 'CROP-045', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0027', 'CONCEPT-167', 'CROP-046', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0028', 'CONCEPT-167', 'CROP-042', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0029', 'CONCEPT-170', 'CROP-058', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0030', 'CONCEPT-170', 'CROP-059', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0031', 'CONCEPT-176', 'INS-33', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0032', 'CONCEPT-160', 'INS-09', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0033', 'CONCEPT-161', 'INS-12', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0034', 'CONCEPT-159', 'INS-01', 'SUPERSEDES', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0035', 'CONCEPT-156', 'CONCEPT-154', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0036', 'CONCEPT-157', 'CONCEPT-154', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0037', 'CONCEPT-158', 'CONCEPT-157', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0038', 'CONCEPT-167', 'CONCEPT-154', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0039', 'CONCEPT-168', 'CONCEPT-167', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0040', 'CONCEPT-169', 'CONCEPT-168', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0041', 'CONCEPT-173', 'CONCEPT-172', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0042', 'CONCEPT-174', 'CONCEPT-167', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R1-0043', 'CONCEPT-175', 'CONCEPT-174', 'DEPENDS_ON', NULL);

-- 검증 SQL (적용 후 진산님 직접 확인):
-- SELECT COUNT(*) FROM knowledge_nodes WHERE batch_id='BATCH-R1'; -- expect: 24
-- SELECT COUNT(*) FROM knowledge_edges WHERE id LIKE 'EDGE-BATCH-R1-%'; -- expect: 43
-- SELECT COUNT(*) FROM formulas WHERE id LIKE 'F-%'; -- expect: \u003E= 0 (기존 등록 합산)
