-- BATCH 적재 SQL — BATCH-7 (2026)
-- 출처: batch-7-knowledge-graph.json
-- 노드: 20 / 엣지: 36 / 산식: 6 / 상수: 7
-- 적용: wrangler d1 execute <db-name> --file=<this-file> --remote
-- 사전 의무: migration 0019 production 적용 완료
-- 멱등성: INSERT OR IGNORE — 재실행 시 충돌 없음
--
-- AI 생성 데이터 (CLAUDE.md Hard Limit) — status='draft' 만 INSERT
-- 진산님 검수 후 status_transitions UPDATE 로 review/approved 전이
--
-- 주의: D1 wrangler execute --file 은 전체 파일을 자동 트랜잭션으로 감싼다.
-- 명시 BEGIN TRANSACTION/COMMIT 은 D1 거부 (Durable Object 충돌). 의도적으로 생략.

-- 1. knowledge_nodes (20 rows)
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-204', 'CONCEPT', '[BATCH-7 META] 손해평가 이론 (제3절 보험금 지급+심사) + 별표 1~9 통합', 'BATCH-7 통합 학습 객체. 영역 ① 제3절 보험금 지급 및 심사 (보험가액·금액 / 지급보험금 계산방식 / 자기부담금 / 잔존보험가입금액 / 비용손해 5종 / 보험금 심사 / 보험사기 방지) ② 별표 1~9 (1=품목별 표본주수표 / 2=미보상비율 적용표 / 3=피해인정계수 LAW-007 기존 / 4=매실 비대추정지수 LAW-008 기존 / 5=무화과 잔여수확량 / 6=손해정도비율 10단계 / 7=고추 병충해 등급 인정비율 / 8=다른 계약 보험금 계산 LAW-009 기존 / 9=품목별 감수과실수 메타). 별표 9 (75p) 본문 산식은 BATCH-1~5에 이미 적재되어 카탈로그 메타 노드만.', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.676', 676, 683, '손해평가 이론과 실무 — 제3절 + 별표', 'META 통합', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-205', 'CONCEPT', '보험가액과 보험금액 — 이득금지원칙 + 피보험이익 + 4종 보험관계', '이득금지원칙: 보험으로 이득 X (BATCH-1~6 CONCEPT-124 정합). 피보험이익 = 보험사고로 입게 될 경제적 이익. 보험가액 = 피보험이익을 금전적 가치로 평가 (이득금지 판정 기준 + 재해보험사업자 법률상 보상한도액). 보험가입금액 = 계약상 보상한도액. 보험가액·가입금액 관계 4종: ① 전부보험(가액=가입금액) ② 초과보험(가액<가입금액) ③ 중복보험(여러 계약 가입금액 합계 > 가액) ④ 일부보험(가액>가입금액). 보험가액은 사고가 발생한 곳·때의 가액으로 평가되므로 수시 변경 가능.', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.676', 676, 683, '손해평가 이론과 실무 — 제3절', '1. 보험가액과 보험금액', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-206', 'CONCEPT', '지급보험금 계산방식 — 전부·초과 / 일부 / 다른 계약 / 비례배분', '지급보험금 = 약관 부문별 자기부담금 차감. ① 전부보험·초과보험 = 보험가입금액 한도로 손해액 전액 (가입금액>가액 시 가액 한도). ② 일부보험 = 손해액 × (보험가입금액÷보험가액) [F-152]. ③ 동일 계약 목적·사고에 다른 계약 + 가입금액 합계 > 가액 = 별표8 [F-153 같은 계산방법 / F-154 다른 계산방법] - 자기부담금. ④ 하나의 가입금액으로 둘 이상 보험 목적 = 전체가액 대비 각 가액 비율로 비례배분. 다른 계약 + 타인을 위한 보험 + 상법 제682조 대위권 행사 시: 다른 계약 우선 vs 다른 계약 없는 가정 등 분기 처리.', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.677', 677, 684, '손해평가 이론과 실무 — 제3절', '2. 지급보험금 계산', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-207', 'CONCEPT', '가축재해보험 자기부담금 — 부문별 차등 (가축 비율 / 특약 200만원 / 축사 50만원 / 말 20%)', '자기부담금 기능: 재해보험사업자 지출비용 축소(보험료 경감) + 도덕적 해이·사고방지 의식 고취. 부문별 적용: ① 소·돼지·종모우·가금·기타가축 부문 = 지급보험금 × 보험증권 자기부담금 비율. ② 폭염·전기적장치·질병위험 특약 = max(자기부담금, 2,000,000원). ③ 축사 부문 풍수재·설해·지진 손해 = max(자기부담금, 500,000원). ④ 말 부문 = 지급보험금 × 20%. ⑤ 단 경주마(가입 후 용도 변경 포함) = 보험증권 비율.', '가축재해보험', NULL, NULL, 'p.678', 678, 685, '손해평가 이론과 실무 — 제3절', '3. 자기부담금', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-208', 'CONCEPT', '잔존보험가입금액 — 일부손해 보험금 지급 후 잔액 (돼지·가금·기타·축사)', '잔존보험가입금액 = 보험기간 중도에 재해보험사업자가 일부손해 보험금 지급 시, 손해발생일 이후 보험기간에 대해서는 보험가입금액에서 그 지급보험금을 공제한 잔액으로 보장. 가축재해보험 적용 부문 = 돼지·가금·기타가축·축사 (소·말 부문 미적용). 약관 규정에 따라 손해의 일부를 보상한 경우 적용.', '가축재해보험', NULL, NULL, 'p.679', 679, 686, '손해평가 이론과 실무 — 제3절', '4. 잔존보험가입금액', 'BATCH-7', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-209', 'CONCEPT', '비용손해 5종 + 지급한도 (잔존물처리 10% / 손해방지·대위권·잔존물보전 자기부담금 X / 기타협력 전액)', '가축재해보험 비용손해 5종 = ① 잔존물처리비용 ② 손해방지비용 ③ 대위권 보전비용 ④ 잔존물 보전비용 ⑤ 기타 협력비용. 지급한도: ① 보험금+잔존물처리비용 합계 = 보험가입금액 한도, 잔존물처리비용 = 손해액 10% 초과 X. ② 손해방지·대위권·잔존물보전 = 가입금액 초과해도 지급 (자기부담금 차감 X). ③ 기타협력 = 가입금액 초과해도 전액 지급. 일부·중복보험 시 손해방지·대위권·잔존물보전 = 비례분담 (자기부담금 공제 X, 가입금액 초과해도 지급), 기타협력 = 비례분담 X 전액 지급. BATCH-1~6 CONCEPT-102 정합.', '가축재해보험', NULL, NULL, 'p.679', 679, 686, '손해평가 이론과 실무 — 제3절', '5. 비용손해의 지급한도', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-210', 'CONCEPT', '보험금 심사 — 면·부책 판단 4요건 + 손해액 평가 + 유의사항 5종', '보험금 심사 = 보험사고 접수 후 손해평가 결과 토대로 지급여부·지급보험금 결정. 약관의 규제에 관한 법률 + 약관 해석 원칙 + 특별약관 우선 적용 + 보통약관 보충. ① 면·부책 판단 4요건: (1) 보험기간 내 약관 담보 사고 (2) 사고-손해 상당인과관계 (3) 상법·약관 면책조항 해당 (4) 알릴 의무 위반 효과. ② 손해액 평가 = 약관 규정. ③ 유의사항 5종: (1) 계약체결 정당성 (피보험자 동의) (2) 고의·역선택 (다수보험·허위) (3) 고지의무 위반 (계약 전·후 알릴 의무) (4) 면책사유 (무효·고의·청구시효 소멸) (5) 기타 (개별약관 + 청구서류 보완·생략).', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.680', 680, 687, '손해평가 이론과 실무 — 제3절', '6. 보험금 심사', 'BATCH-7', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-211', 'CONCEPT', '보험사기 방지 — 정의 + 성립요건 5 + 처벌 (10년/5천만원) + 5년 취소', '보험사기 = 보험계약자 등이 보험제도 원리상 취할 수 없는 혜택을 부당 취득 또는 고액 보험금 수취 목적으로 고의·악의적 행동. 형법상 사기죄 한 유형. 보험사기방지 특별법: 10년 이하 징역 or 5천만원 이하 벌금. 성립요건 5종: ① 계약자·보험대상자 고의 ② 기망행위 (허위진술/진실은폐/침묵) ③ 보험자 착오 (과실 무관) ④ 착오로 인한 승낙 의사표시 + 인과관계 ⑤ 사기 위법성 (사회생활상 신의성실 원칙 반함). 사기행위자 = 권유자 교사 또는 계약자·피보험자 자신 사기 시 보장개시일로부터 5년 이내 계약 취소 가능 (고지의무 위반과 달리). 사기증명 = 재해보험사업자 측 입증책임. 조치 = ① 청구한 사고보험금 지급 거절 ② 약관에 의거 해당 계약 취소.', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.682', 682, 689, '손해평가 이론과 실무 — 제3절', '7. 보험사기 방지', 'BATCH-7', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-138', 'LAW', '<별표1> 품목별 표본주(구간)수 표 — 7개 분류표', '농작물재해보험 품목별 표본주(구간)수 표. 7개 분류: ① 사과배단감떫은감·포도(농업수입안정 포함)·복숭아·자두·밤·호두·무화과·감귤(만감류) (50주~1000주+ → 5~17 표본주, 100주 단위). ② 유자 (50주~800주+ → 5~10 표본주). ③ 참다래·블루베리·매실·대추·살구 / 오미자 (50주~1000주+ 또는 유인틀 길이 500m~6000m+ → 5~16 표본주). ④ 오디·복분자·감귤(온주밀감류) (50주·1000포기·5000㎡ 단위 → 6~13 표본). ⑤ 벼·밀·보리·귀리 (2000㎡~6000㎡+ → 3~8 표본구간). ⑥ 고구마·양파·마늘·옥수수·양배추·단호박 (수입보장 포함, 1500㎡~4500㎡+ → 4~7 표본구간). ⑦ 감자·차·콩·팥·수박·당근·생강·고랭지무·가을무(일반)·고랭지배추·가을배추 (수입보장 포함, 2500㎡~10000㎡+ → 4~8 표본구간). + 인삼 (피해칸 300칸~1800칸+ → 3~10 표본칸). + 고추·메밀·브로콜리·배추·무·파·시금치·양상추 (피해면적 3000㎡~15000㎡+ → 4~10 표본구간이랑수). + 두릅 (3000㎡~15000㎡+ → 4~10 표본). + 참깨·녹두 (1000㎡~10000㎡+ → 3~8 표본구간).', '농작물재해보험', NULL, NULL, 'p.684', 684, 691, '별표 1', '별표1 품목별 표본주(구간)수 표', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-139', 'LAW', '<별표2> 농작물재해보험 미보상비율 적용표 — 4단계 (감자·고추 제외/포함 분리)', '미보상비율 = 보장재해 이외 원인이 농지 수확량 감소에 영향을 준 비율. 감자·고추 제외 전 품목 = 제초상태·병해충상태·기타 3항목 개별 적용 후 합산. 감자·고추 = 제초상태·기타 2항목 (병해충 별도 보상). 4단계: ① 해당 없음 = 0% (잡초·병해충 농지 면적 20% 미만 분포). ② 미흡 = 10% 미만. ③ 불량 = 20% 미만 (또는 경작불능조사 결과 수확량 조사 결정+영농활동 증빙자료 부족). ④ 매우 불량 = 20% 이상 (또는 60%+ 분포 + 증빙자료 없음). 기타항목 = 영농기술 부족·영농 실수·생리장애·해거리·시비/토양관리·전정·조방재배·재식밀도·농지상태(혼식·멀칭·급배수)·가입이전 사고·자연감모·종자불량 등 → 0%/10%미만/20%미만/20%이상 4단계.', '농작물재해보험', NULL, NULL, 'p.688', 688, 695, '별표 2', '별표2 농작물재해보험 미보상비율 적용표', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-140', 'LAW', '<별표5> 무화과 사고발생일 잔여수확량 비율 — 8월/9월/10월 3구간 산식', '무화과 품목 사고발생일에 따른 잔여수확량 비율 (3구간 산식): ① 8월 = {100 - (1.06 × 사고발생일자)}. ② 9월 = {(100 - 33) - (1.13 × 사고발생일자)}. ③ 10월 = {(100 - 67) - (0.84 × 사고발생일자)}. 사고발생일자 = 해당월의 사고발생일자. F-155/156/157 산식 노드 이중 등록. BATCH-2 LAW-015 (별표 수확일자별 잔여수확량 비율 — 복분자/무화과 통합) 정합 — LAW-140은 무화과 산식 명세, LAW-015는 복분자 포함 통합 정의.', '농작물재해보험', '무화과', NULL, 'p.695', 695, 702, '별표 5', '별표5 무화과 사고발생일 잔여수확량 비율', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-141', 'LAW', '<별표6> 표본구간별 손해정도비율 — 10% 단위 10단계 (26년 정합)', '표본구간별 손해정도에 따른 손해정도비율 (26년 정합 — 10% 단위 10단계): 손해정도 1~10% = 손해정도비율 10%. 11~20% = 20%. 21~30% = 30%. 31~40% = 40%. 41~50% = 50%. 51~60% = 60%. 61~70% = 70%. 71~80% = 80%. 81~90% = 90%. 91~100% = 100%. BATCH-1~6 CONCEPT-081 (생산비보장 일반 26년 신규 10단계) + R1 CONCEPT-171 (준비기생산비계수+손해정도비율 20→10%) 정합 — 별표6은 매트릭스 정의, CONCEPT-081/171은 적용 노드.', '농작물재해보험', NULL, NULL, 'p.695', 695, 702, '별표 6', '별표6 표본구간별 손해정도비율', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-142', 'LAW', '<별표7> 고추 병충해 등급별 인정비율 — 1·2·3등급 (70/50/30%)', '고추 병충해 등급별 인정비율: ① 1등급 (인정비율 70%) = 역병·풋마름병·바이러스병·세균성점무늬병·탄저병. ② 2등급 (인정비율 50%) = 잿빛곰팡이병·시들음병·담배가루이·담배나방. ③ 3등급 (인정비율 30%) = 흰가루병·균핵병·무름병·진딧물 및 기타. BATCH-4 F-86 (고추 생산비보장 보험금 병충해 없음)·F-89 (병충해 있음 — 노지 고추) 산식의 인정비율 매트릭스.', '농작물재해보험', '고추', NULL, 'p.695', 695, 702, '별표 7', '별표7 고추 병충해 등급별 인정비율', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-143', 'LAW', '<별표9> 품목별 감수과실수 및 피해율 산정 방법 메타 (BATCH-1~5 산식 카탈로그)', '별표9 = 품목별 감수과실수 및 피해율 산정 방법 카탈로그 (75p, 2025.3.31. 개정). 영역: ① 적과전 종합위험방식 과수 (사과·배·단감·떫은감) — BATCH-1 F-01~F-13 정합. ② 종합위험 수확감소보장 과수 (포도·복숭아·자두·살구·매실·대추·유자·무화과·밤·호두·참다래·오미자) — BATCH-1·2 산식 정합. ③ 종합위험 수확감소보장 논·밭작물 (벼·밀·보리·옥수수 등) — BATCH-3·4 정합. ④ 종합위험 과실손해보장 (오디·감귤·복분자·무화과·블루베리·두릅) — BATCH-2 정합. ⑤ 종합위험 비가림시설 (포도·대추·참다래) — BATCH-1 정합. ⑥ 적과전 종합위험 II (5종한정특약) — BATCH-1·R2 CONCEPT-180 정합. ⑦ 종합위험 농업수입안정보장 — BATCH-5·R1·R2 CONCEPT-200/201 정합. 본 노드 = 별표9 메타 (카탈로그 인덱스). 본문 산식은 BATCH-1~5에 이미 적재 (중복 회피, TD-S43-2 정합).', '농작물재해보험', NULL, NULL, 'p.696', 696, 703, '별표 9', '별표9 품목별 감수과실수 및 피해율 산정 방법 (메타)', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-152', 'FORMULA', '일부보험 지급보험금 산식', '지급보험금 = 손해액 × (보험가입금액 ÷ 보험가액). 일부보험(가입금액<가액) 시 적용. 자기부담금은 별도 차감.', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.677', 677, 684, '손해평가 이론과 실무 — 제3절', '2. 지급보험금 계산 — 일부보험', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-153', 'FORMULA', '별표8 (1) 다른 계약 보험금 — 같은 계산방법 (가입금액 비례분담)', '다른 계약이 이 계약과 지급보험금 계산방법이 같은 경우. 자기부담금 별도 차감.', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.695', 695, 702, '별표 8', '별표8 (1) 같은 계산방법', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-154', 'FORMULA', '별표8 (2) 다른 계약 보험금 — 다른 계산방법 (보험금 비례분담)', '다른 계약이 이 계약과 지급보험금 계산방법이 다른 경우. 자기부담금 별도 차감.', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.695', 695, 702, '별표 8', '별표8 (2) 다른 계산방법', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-155', 'FORMULA', '별표5 무화과 8월 잔여수확량 비율 (%)', '8월 잔여수확량 비율 = 100 - (1.06 × 사고발생일자). 무화과 한정.', '농작물재해보험', '무화과', NULL, 'p.695', 695, 702, '별표 5', '별표5 무화과 8월 잔여수확량', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-156', 'FORMULA', '별표5 무화과 9월 잔여수확량 비율 (%)', '9월 잔여수확량 비율 = (100 - 33) - (1.13 × 사고발생일자) = 67 - 1.13×D. 무화과 한정.', '농작물재해보험', '무화과', NULL, 'p.695', 695, 702, '별표 5', '별표5 무화과 9월 잔여수확량', 'BATCH-7', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-157', 'FORMULA', '별표5 무화과 10월 잔여수확량 비율 (%)', '10월 잔여수확량 비율 = (100 - 67) - (0.84 × 사고발생일자) = 33 - 0.84×D. 무화과 한정.', '농작물재해보험', '무화과', NULL, 'p.695', 695, 702, '별표 5', '별표5 무화과 10월 잔여수확량', 'BATCH-7', 2026, 10, 'draft');

-- 2. formulas (6 rows, INSERT OR IGNORE — 기존 등록 row 보존)
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-152', '일부보험 지급보험금 산식', 'P = L * (S / V)', '{"P":"지급보험금","L":"손해액(원)","S":"보험가입금액(원)","V":"보험가액(원)"}', 'p.677', 'F-152', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-153', '별표8 (1) 다른 계약 보험금 — 같은 계산방법 (가입금액 비례분담)', 'P = L * (S_i / sum(S_k))', '{"P":"이 계약 지급보험금","L":"손해액(원)","S_i":"이 계약의 보험가입금액(원)","S_k":"다른 계약 없는 가정으로 각각 계산한 보험가입금액(원, 합산)"}', 'p.695', 'F-153', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-154', '별표8 (2) 다른 계약 보험금 — 다른 계산방법 (보험금 비례분담)', 'P = L * (B_i / sum(B_k))', '{"P":"이 계약 지급보험금","L":"손해액(원)","B_i":"이 계약 보험금(원)","B_k":"다른 계약 없는 가정으로 각각 계산한 보험금(원, 합산)"}', 'p.695', 'F-154', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-155', '별표5 무화과 8월 잔여수확량 비율 (%)', 'R = 100 - 1.06 * D', '{"R":"잔여수확량 비율(%)","D":"사고발생일자(8월 일자)"}', 'p.695', 'F-155', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-156', '별표5 무화과 9월 잔여수확량 비율 (%)', 'R = 67 - 1.13 * D', '{"R":"잔여수확량 비율(%)","D":"사고발생일자(9월 일자)"}', 'p.695', 'F-156', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-157', '별표5 무화과 10월 잔여수확량 비율 (%)', 'R = 33 - 0.84 * D', '{"R":"잔여수확량 비율(%)","D":"사고발생일자(10월 일자)"}', 'p.695', 'F-157', 2026);

-- 3. constants (7 rows, INSERT OR IGNORE)
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-185', 'deductible', '가축재해보험 폭염·전기적·질병위험 특약 자기부담금 한도 (원)', '2000000', 2000000.0, '가축재해보험 폭염·전기적·질병위험 특약 자기부담금 한도 (원)', 'p.678', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-186', 'deductible', '가축재해보험 축사 풍수재·설해·지진 자기부담금 한도 (원)', '500000', 500000.0, '가축재해보험 축사 풍수재·설해·지진 자기부담금 한도 (원)', 'p.678', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-187', 'ratio', '가축재해보험 말 부문 자기부담금 비율', '0.20', 0.2, '가축재해보험 말 부문 자기부담금 비율', 'p.678', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-188', 'ratio', '가축재해보험 잔존물처리비용 손해액 한도 비율', '0.10', 0.1, '가축재해보험 잔존물처리비용 손해액 한도 비율', 'p.679', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-189', 'threshold', '보험사기방지 특별법 징역 한도 (년)', '10', 10.0, '보험사기방지 특별법 징역 한도 (년)', 'p.682', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-190', 'deductible', '보험사기방지 특별법 벌금 한도 (원)', '50000000', 50000000.0, '보험사기방지 특별법 벌금 한도 (원)', 'p.682', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-191', 'threshold', '보험사기 보장개시일 기준 계약 취소 한도 기간 (년)', '5', 5.0, '보험사기 보장개시일 기준 계약 취소 한도 기간 (년)', 'p.683', 2026);

-- 4. knowledge_edges (36 rows) — nodes 적재 후
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0001', 'CONCEPT-204', 'CONCEPT-205', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0002', 'CONCEPT-204', 'CONCEPT-206', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0003', 'CONCEPT-204', 'CONCEPT-207', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0004', 'CONCEPT-204', 'CONCEPT-208', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0005', 'CONCEPT-204', 'CONCEPT-209', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0006', 'CONCEPT-204', 'CONCEPT-210', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0007', 'CONCEPT-204', 'CONCEPT-211', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0008', 'CONCEPT-204', 'LAW-138', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0009', 'CONCEPT-204', 'LAW-139', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0010', 'CONCEPT-204', 'LAW-140', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0011', 'CONCEPT-204', 'LAW-141', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0012', 'CONCEPT-204', 'LAW-142', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0013', 'CONCEPT-204', 'LAW-143', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0014', 'CONCEPT-206', 'CONCEPT-205', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0015', 'CONCEPT-207', 'CONCEPT-206', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0016', 'CONCEPT-208', 'CONCEPT-206', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0017', 'CONCEPT-209', 'CONCEPT-206', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0018', 'CONCEPT-210', 'CONCEPT-206', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0019', 'CONCEPT-206', 'F-152', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0020', 'CONCEPT-206', 'F-153', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0021', 'CONCEPT-206', 'F-154', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0022', 'LAW-140', 'F-155', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0023', 'LAW-140', 'F-156', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0024', 'LAW-140', 'F-157', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0025', 'CONCEPT-205', 'CONCEPT-124', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0026', 'CONCEPT-209', 'CONCEPT-102', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0027', 'LAW-140', 'LAW-015', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0028', 'LAW-141', 'CONCEPT-081', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0029', 'LAW-141', 'CONCEPT-171', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0030', 'LAW-141', 'CONCEPT-192', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0031', 'LAW-142', 'F-86', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0032', 'LAW-142', 'F-89', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0033', 'LAW-143', 'LAW-007', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0034', 'LAW-143', 'LAW-008', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0035', 'LAW-143', 'LAW-009', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-7-0036', 'CONCEPT-206', 'LAW-009', 'CROSS_REF', NULL);

-- 검증 SQL (적용 후 진산님 직접 확인):
-- SELECT COUNT(*) FROM knowledge_nodes WHERE batch_id='BATCH-7'; -- expect: 20
-- SELECT COUNT(*) FROM knowledge_edges WHERE id LIKE 'EDGE-BATCH-7-%'; -- expect: 36
-- SELECT COUNT(*) FROM formulas WHERE id LIKE 'F-%'; -- expect: \u003E= 6 (기존 등록 합산)
