-- BATCH 적재 SQL — BATCH-GAP-P2 (E0-8 갭 보강 P2: 부록 요령·운영규정·목적물고시, 2026-07-02)
-- 출처: 교재 2026 이론서 부록2-3/2-4/2-5 (book 807~826 / PDF 814~833). E0-8 리포트 §2 A-2.
-- 대상 정본: inventory content-coverage-inventory-20260702.md 라인 598~600 (부록2-3 요령 전문 / 2-4 운영규정 / 2-5 목적물고시).
--   부록2-1(법 전문 재수록)·2-2(시행령 전문 재수록)·부록3(참고문헌) = 중복/무관 스코프 제외(E0-8 B군).
-- 노드: 37 (LAW-166~202 — 요령 18 / 운영규정 18 / 목적물고시 1) / 엣지: 41 / 산식: 0 / 상수: 0
-- 결재: 진산 2026-07-02 — P2 착수 + override(P1 검수 FIX율 게이트 명시 생략, 근거 P1 독립검증 2회 CRITICAL 0).
--        플레이북 §8 결재란 P2 [x]. Opus 4.8 실행.
--
-- ★ 충돌 처리 (P1 A안 패턴 = 원문 노드 신규 + CROSS_REF, UPDATE 아님):
--   - 요령 제11조(검증조사) ↔ 기존 LAW-003 (교재 개관장 요약본) : CROSS_REF
--   - 요령 제12조(손해평가 단위) ↔ 기존 LAW-004 (교재 개관장 요약본) : CROSS_REF
--   - 요령 제8조의2(교차손해평가) ↔ 기존 CONCEPT-137 (법 제11조③ 교차평가) : CROSS_REF
--   - 요령 제13조 ↔ 기존 CONCEPT-179 (요령 제13조제4항 예찰조사 2026 개정분) : CROSS_REF (개정 관계 flag)
--   - 요령 근거 = 법 제11조제2항 (LAW-145, P1 적재) : 요령 전 조문 DEPENDS_ON LAW-145
--
-- ★ ESCALATE (플레이북 §6 — 노드는 원문 참조만, 별도 테이블 INSERT 금지):
--   - 요령 [별표1] 농작물 보험금 산정 (산식 다수) = 규칙1 산식 → 제13조 노드에 "별표1" 참조만. formulas INSERT 0.
--     (별표1/2 산식·조사방법 표는 BATCH-1~7 품목별 노드·별표 노드 LAW-005~015·138~143 에 기적재 — 중복 회피)
--   - 요령 [별표2] 조사방법 표 / [별표3] 제재조치 표 = 규칙3 표 → 제6조·제13조 노드에 참조만.
--   - 운영규정 제13조 응시수수료(1차 2만원/2차 3만3천원) = 규칙2 수치상수 → 노드 description 원문 인용, constants INSERT 0.
--   - 목적물고시 보험목적물 범위 [표] = 규칙3 표 → 노드에 "법 제5조 위임 표" 참조만, 표 셀 미적재.
--
-- 페이지축: 교재 이론서 book_page = pdf_page − 7 (E0-8 prestage §3, footer 실측 정합: pdf814='- 807 -' ~ pdf833='- 826 -').
--   page_ref = 인쇄본 book_page (인간 대면). book_page = 인쇄 쪽번호. pdf_page = PDF 순번.
-- 적용: cd apps/api && npx wrangler d1 execute thepick-db-production --file=<this-file> --remote
--        ★ production 쓰기 = 진산 인증 게이트.
-- 멱등성: INSERT OR IGNORE — 재실행 시 충돌 없음.
-- AI 생성 데이터 (Hard Limit) — status='draft' 만 INSERT. 진산 검수 후 status_transitions 로 approved 전이.
-- D1 wrangler --file 은 전체를 자동 트랜잭션 처리. 명시 BEGIN/COMMIT 생략(D1 거부).

-- ============================================================
-- (1) 농업재해보험 손해평가요령 [농식품부고시 제2024-25호, 시행 2024.3.29.] — 부록2-3, book 807~811
-- ============================================================

INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-166', 'LAW', '요령 제1조 (목적)', '이 요령은 「농어업재해보험법」 제11조제2항에 따른 손해평가에 필요한 세부사항을 규정함을 목적으로 한다. (농업재해보험 손해평가요령 = 농림축산식품부고시 제2024-25호, 시행 2024.3.29.)', NULL, NULL, NULL, 'p.807', 807, 814, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-167', 'LAW', '요령 제2조 (용어의 정의)', '요령 용어 정의 5호. 1. "손해평가" = 법 제2조제1호 피해 발생 시 법 제11조 및 제11조의3에 따라 손해평가인·손해평가사·손해사정사가 피해사실을 확인·평가하는 일련의 과정. 2. "손해평가인" = 법 제11조제1항과 시행령 제12조제1항에서 정한 자 중 재해보험사업자가 위촉하여 손해평가업무를 담당하는 자. 3. "손해평가사" = 법 제11조의4제1항 자격시험 합격자. 4. "손해평가보조인" = 제1호 손해평가 업무를 보조하는 자. 5. "농업재해보험" = 법 제4조에 따른 농작물재해보험·임산물재해보험·가축재해보험.', NULL, NULL, NULL, 'p.807', 807, 814, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-168', 'LAW', '요령 제3조 (손해평가 업무)', '① 손해평가 시 손해평가인·손해평가사·손해사정사는 다음 업무를 수행: 1. 피해사실 확인, 2. 보험가액 및 손해액 평가, 3. 그 밖에 손해평가에 관하여 필요한 사항. ② 임무 수행 전에 보험가입자("피보험자" 포함)에게 손해평가인증·손해평가사자격증·손해사정사등록증 등 신분 확인 서류를 제시하여야 한다.', NULL, NULL, NULL, 'p.807', 807, 814, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-169', 'LAW', '요령 제4조 (손해평가인 위촉)', '① 재해보험사업자는 법 제11조제1항과 시행령 제12조제1항에 따라 손해평가인을 위촉한 경우 그 자격을 표시하는 손해평가인증을 발급하여야 한다. ② 피해 발생 시 원활한 손해평가를 위해 시·군·자치구별 보험가입자 수 등을 고려하여 적정 규모의 손해평가인을 위촉할 수 있다. ③ 재해보험사업자 및 법 제14조에 따라 손해평가 업무를 위탁받은 자는 손해평가보조인을 운용할 수 있다.', NULL, NULL, NULL, 'p.807', 807, 814, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-170', 'LAW', '요령 제5조 (손해평가인 실무교육)', '① 재해보험사업자는 제4조에 따라 위촉된 손해평가인에게 농업재해보험 기초지식·보험상품 및 약관·손해평가 방법 및 절차 등 손해평가에 필요한 실무교육을 실시하여야 한다. ② 삭제. ③ 실무교육 손해평가인에게 재해보험사업자는 소정의 교육비를 지급할 수 있다.', NULL, NULL, NULL, 'p.807', 807, 814, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-171', 'LAW', '요령 제5조의2 (손해평가인 정기교육)', '① 법 제11조제5항에 따른 손해평가인 정기교육 세부내용: 1. 농업재해보험 기초지식(농어업재해보험법 제정 배경·구성 및 조문별 주요내용, 사업현황), 2. 농업재해보험 종류별 약관(상품 주요내용 및 약관 일반), 3. 손해평가 절차 및 방법(손해평가 개요, 보험목적물별 손해평가 기준 및 피해유형별 보상사례), 4. 피해유형별 현지조사표 작성 실습. ② 재해보험사업자는 정기교육 대상자에게 소정의 교육비를 지급할 수 있다.', NULL, NULL, NULL, 'p.808', 808, 815, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-172', 'LAW', '요령 제6조 (손해평가인 위촉의 취소 및 해지 등)', '① 위촉 취소 사유(어느 하나 해당·위촉당시 해당 판명 시 취소): 1. 피성년후견인, 2. 파산선고 후 미복권자, 3. 법 제30조에 의해 벌금이상 형을 선고받고 집행 종료·면제된 날부터 2년 미경과자, 4. 동 조에 따라 위촉취소 후 2년 미경과자, 5. 거짓·부정한 방법으로 제4조에 따라 위촉된 자, 6. 업무정지 기간 중 손해평가업무 수행자. ② 6개월 이내 업무정지·위촉해지 사유: 1. 법 제11조제2항 및 이 요령 규정 위반, 2. 법 및 요령에 의한 명령·처분 위반, 3. 개인정보보호법·신용정보법 등 정보보호 관련 법령 위반. ③ 취소·정지 시 청문 실시(불응 시 서면 통보 가능). ④ 해촉하거나 업무의 정지를 명한 때에는 지체 없이 이유를 기재한 문서로 그 뜻을 손해평가인에게 통지하여야 한다. ⑤ 업무정지·위촉해지 세부기준 = [별표3]. ⑥ 손해사정사가 관련 규정 위반 시 제재 적용기준 마련·시행.', NULL, NULL, NULL, 'p.808', 808, 815, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-173', 'LAW', '요령 제8조 (손해평가반 구성 등)', '① 재해보험사업자는 제2조제1호 손해평가 시 손해평가반을 구성하고 손해평가반별 평가일정계획을 수립하여야 한다. ② 손해평가반은 다음 중 어느 하나에 해당하는 자로 구성하며 5인 이내로 한다: 1. 손해평가인, 2. 손해평가사, 3. 「보험업법」 제186조 손해사정사. ③ 다음 손해평가는 해당자를 손해평가반 구성에서 배제: 1. 자기 또는 이해관계자(생계를 같이 하는 친족)가 가입한 보험계약 손해평가, 2. 자기·이해관계자가 모집한 보험계약 손해평가, 3. 직전 손해평가일로부터 30일 이내의 보험가입자간 상호 손해평가, 4. 자기가 실시한 손해평가에 대한 검증조사 및 재조사. (부칙: 제8조 개정규정은 공포 후 3개월 경과일 시행)', NULL, NULL, NULL, 'p.808', 808, 815, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-174', 'LAW', '요령 제8조의2 (교차손해평가)', '① 재해보험사업자는 공정·객관적 손해평가를 위해 교차손해평가가 필요한 경우 재해보험 가입규모·가입분포 등을 고려하여 교차손해평가 대상 시·군·구(자치구)를 선정하여야 한다. ② 선정한 시·군·구 내에서 손해평가 경력·타지역 조사 가능여부 등을 고려하여 교차손해평가 담당 지역손해평가인을 선발하여야 한다. ③ 교차손해평가 손해평가반 구성 시 선발된 지역손해평가인 1인 이상 포함(다만 거대재해·평가인력 부족 등 신속 손해평가가 불가피한 경우 예외).', NULL, NULL, NULL, 'p.809', 809, 816, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-175', 'LAW', '요령 제9조 (피해사실 확인)', '① 보험가입자가 보험책임기간 중 피해발생 통지를 한 때에는 재해보험사업자는 손해평가반으로 하여금 지체 없이 보험목적물의 피해사실을 확인하고 손해평가를 실시하게 하여야 한다. ② 손해평가 실시 시 재해보험사업자가 해당 보험가입자의 보험계약사항 중 손해평가 관련 사항을 손해평가반에게 통보하여야 한다.', NULL, NULL, NULL, 'p.809', 809, 816, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-176', 'LAW', '요령 제10조 (손해평가준비 및 평가결과 제출)', '① 재해보험사업자는 손해평가결과·손해평가반 구성원 기록용 현지조사서를 마련하여야 한다. ② 손해평가 전 현지조사서를 손해평가반에 배부하고 주의사항을 숙지시켜야 한다. ③ 손해평가반은 현지조사서에 결과를 정확히 작성·설명 후 보험가입자 서명을 받아 최종 조사일로부터 7영업일 이내에 제출(하우스 등 원예시설·축사 건물은 7영업일 초과 가능). 정당한 사유 없이 서명 거부 시 결과 통지 후 서명없이 제출. ④ 보험가입자가 정당한 사유없이 손해평가를 거부하면 피해를 인정할 수 없는 것으로 평가한다는 사실을 통지 후 제출. ⑤ 보험가입자가 설명·통지받은 날부터 7일 이내에 손해평가가 잘못됨을 증빙하는 서류·사진을 제출하면 재해보험사업자는 다른 손해평가반으로 재조사를 실시하게 할 수 있다.', NULL, NULL, NULL, 'p.809', 809, 816, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-177', 'LAW', '요령 제11조 (손해평가결과 검증)', '① 재해보험사업자 및 법 제25조의2에 따라 관리를 위탁받은 기관("사업 관리 위탁 기관")은 손해평가결과 확인을 위해 손해평가한 보험목적물 중 일정수를 임의 추출하여 검증조사를 할 수 있다. ② 농림축산식품부장관은 재해보험사업자로 하여금 검증조사를 하게 할 수 있으며, 재해보험사업자는 특별한 사유가 없는 한 응하여 결과를 장관에게 제출하여야 한다. ③ 검증조사결과 현저한 차이로 재조사가 불가피하면 해당 손해평가반이 조사한 전체 보험목적물을 재조사할 수 있다. ④ 보험가입자가 정당한 사유없이 검증조사 거부 시 검증불가 사실을 통지 후 검증조사결과 작성·제출. ⑤ 사업 관리 위탁 기관 검증조사 시 결과를 재해보험사업자에게 통보하고 조치 요구 가능. (교재 개관장 요약 LAW-003 과 CROSS_REF — 본 노드가 요령 원문.)', NULL, NULL, NULL, 'p.809', 809, 816, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-178', 'LAW', '요령 제12조 (손해평가 단위)', '① 보험목적물별 손해평가 단위: 1. 농작물 = 농지별, 2. 가축 = 개별가축별(단, 벌은 벌통 단위), 3. 농업시설물 = 보험가입 목적물별. ② 제1항제1호 "농지" = 하나의 보험가입금액에 해당하는 토지로 필지(지번)와 관계없이 농작물을 재배하는 하나의 경작지를 말하며, 방풍림·돌담·도로(농로 제외) 등 또는 동일 울타리·시설 등에 의해 구획된 것을 하나의 농지로 한다(경사지 등 극히 작은 것은 동일 작업 단위로 정리하여 하나의 농지에 포함 가능). (교재 개관장 요약 LAW-004 와 CROSS_REF — 본 노드가 요령 원문.)', NULL, NULL, NULL, 'p.810', 810, 817, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-179', 'LAW', '요령 제13조 (농작물의 보험가액 및 보험금 산정)', '① 농작물 보험가액 산정 5방식: 1. 특정위험방식 인삼 = 가입면적 × 보험가입 당시 단위당 가입가격(가입면적·연근 변경 가능), 2. 적과전종합위험방식 = 적과후착과수 조사 기준수확량 × 단위당 가입가격, 3. 종합위험방식 = 평년수확량 × 단위당 가입가격(가입면적·주수·수령·품종 변경 가능), 4. 생산비보장 = 작물별 가입 당시 정한 보험가액 기준, 5. 나무손해보장 = 최초 보험사고 시 과실생산 가능 나무 수(피해 나무 포함) × 나무당 가입가격. ② 보험금 산정 = [별표1]. ③ 손해수량 품목별·재해별·시기별 조사방법 = [별표2]. ④ 재해발생 전부터 생육상황 조사 가능(조사결과 1부 제출). (산식 상세 별표1/조사방법 별표2 = ESCALATE 참조. 제4항 예찰 관련 2026 개정분 = CONCEPT-179 CROSS_REF.)', NULL, NULL, NULL, 'p.810', 810, 817, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-180', 'LAW', '요령 제14조 (가축의 보험가액 및 손해액 산정)', '① 가축 보험가액 = 보험사고 발생 때·곳에서 평가한 보험목적물 수량 × 적용가격. ② 가축 손해액 = 보험사고 발생 때·곳에서 폐사 등 피해 보험목적물 수량 × 적용가격. ③ 적용가격 = 보험사고 발생 때·곳의 시장가격 등을 감안하여 보험약관에서 정한 방법으로 산정(가입당시 보험가입자와 재해보험사업자가 별도로 정한 경우 그 방법).', NULL, NULL, NULL, 'p.810', 810, 817, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-181', 'LAW', '요령 제15조 (농업시설물의 보험가액 및 손해액 산정)', '① 농업시설물 보험가액 = 보험사고 발생 때·곳에서 평가한 피해목적물의 재조달가액에서 내용연수에 따른 감가상각률을 적용한 감가상각액을 차감하여 산정. ② 농업시설물 손해액 = 보험사고 발생 때·곳에서 산정한 피해목적물의 원상복구비용. ③ 가입당시 보험가입자와 재해보험사업자가 보험가액 및 손해액 산정방식을 별도로 정한 경우 그 방법.', NULL, NULL, NULL, 'p.810', 810, 817, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-182', 'LAW', '요령 제16조 (손해평가업무방법서)', '재해보험사업자는 이 요령의 효율적 운용 및 시행을 위하여 필요한 세부적인 사항을 규정한 손해평가업무방법서를 작성하여야 한다.', NULL, NULL, NULL, 'p.811', 811, 818, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-183', 'LAW', '요령 제17조 (재검토기한)', '농림축산식품부장관은 이 고시에 대하여 2024년 1월 1일 기준으로 매 3년이 되는 시점(매 3년째의 12월 31일까지)마다 그 타당성을 검토하여 개선 등의 조치를 하여야 한다.', NULL, NULL, NULL, 'p.811', 811, 818, '농업재해보험 손해평가요령', '요령', 'BATCH-GAP-P2', 2026, 10, 'draft');

-- ============================================================
-- (2) 재보험사업 및 농업재해보험사업의 운영 등에 관한 규정 [농식품부고시 제2020-16호, 시행 2020.2.12.] — 부록2-4, book 822~825
-- ============================================================

INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-184', 'LAW', '운영규정 제1조 (목적)', '이 고시는 「농어업재해보험법」("법") 및 동법 시행령("영")에 의한 재보험사업 및 농업재해보험사업의 효율적인 관리·운영에 필요한 세부적인 사항에 대해 규정함을 목적으로 한다. (재보험사업 및 농업재해보험사업의 운영 등에 관한 규정 = 농림축산식품부고시 제2020-16호, 시행 2020.2.12.)', NULL, NULL, NULL, 'p.822', 822, 829, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-185', 'LAW', '운영규정 제2조 (용어의 정의)', '1. "수탁기관" = 법 제20조 및 법 제25조의2에 따라 재보험사업 및 농업재해보험사업에 관한 업무를 위탁받은 농업정책보험금융원. 2. "재해보험 가입현황서" = 재해보험사업자가 법 제19조제1항에 따른 보험료 일부를 지원받기 위해 작성·제출하는 보험계약사항 및 보험료 현황 서류. 3. "운영비 사용계획서" = 법 제19조제1항 운영비 지원용 운영비사용현황 서류. 4. "통계작업방법서" = 농림축산식품부장관 또는 수탁기관의 장이 통계 축적·보험료 및 재보험료 정산 등을 위해 자료 작성·제출방법을 규정한 것(약정서 첨부).', NULL, NULL, NULL, 'p.822', 822, 829, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-186', 'LAW', '운영규정 제3조 (적용범위)', '법, 영, 「농림축산식품분야재정사업관리기본규정」 및 「농특회계융자업무지침」에서 따로 정하는 사항을 제외하고는 이 고시에서 정하는 바에 따른다. 다만, 양식수산물재해보험에 대해서는 적용하지 아니한다.', NULL, NULL, NULL, 'p.822', 822, 829, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-187', 'LAW', '운영규정 제5조 (위탁업무의 처리)', '① 수탁기관은 위탁업무를 재보험 및 농업재해보험사업 수행 목적에 맞도록 처리하여야 한다. ② 수탁기관은 위탁업무 처리를 위해 농업재해보험 전담 부서("보험관리부서")를 설치하고 인원·장비 등을 지원하여야 한다. ③ 농림축산식품부장관은 예산의 범위에서 보험관리부서의 인건비 및 경비 등을 지원하여야 한다. (제4조 업무의 위탁 = 삭제.)', NULL, NULL, NULL, 'p.822', 822, 829, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-188', 'LAW', '운영규정 제6조 (약정의 체결)', '① 수탁기관은 재해보험사업자와 법 제20조제2항 및 영 제16조에서 정한 사항이 포함된 재보험사업 약정을 체결하여야 한다. ② 수탁기관은 재해보험사업자와 법 제8조제3항 및 영 제10조제2항에서 정한 사항이 포함된 재해보험사업 약정을 체결하여야 한다. ③ 제1항·제2항 약정은 매년 체결 원칙(기 체결 약정서에 자동연장 조항이 있고 내용 미변경 시 생략 가능).', NULL, NULL, NULL, 'p.822', 822, 829, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-189', 'LAW', '운영규정 제7조 (재보험 사업관리)', '① 수탁기관은 매년 영 제16조에서 정한 사항에 대해 재해보험사업자와 협의하여야 한다. ② 수탁기관은 재해보험사업자가 제6조제1항 약정을 준수하는지 조사하기 위해 재보험약정서에 정한 자료 제출을 요구할 수 있다. ③ 협의결과·조사결과를 농림축산식품부장관에게 보고. ④ 장관은 보고 자료를 검토하여 재보험조건 등을 확정하거나 관련법령에 따른 조치를 강구. ⑤ 기타 재보험사업 관리 사항 = 재보험사업약정서 및 「농어업재해재보험기금운용규정」에 따름.', NULL, NULL, NULL, 'p.823', 823, 830, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-190', 'LAW', '운영규정 제8조 (재해보험 사업의 관리)', '① 재해보험사업자는 법 제19조 및 영 제15조에 따른 보험료 및 운영비("사업비") 지원을 위해 재해보험 가입현황서나 운영비 사용계획서를 수탁기관에 제출. ② 수탁기관은 제출자료를 검토하여 결과를 장관에게 보고. ③ 수탁기관은 「보조금 관리에 관한 법률」·농업재해보험사업시행지침·약정서 등에 따라 사업점검 및 사업비 정산 업무를 정기 수행·보고. ④ 세부 검토 위해 관련 자료 제출 요구 가능. ⑤ 장관은 보고 자료를 검토하여 사업비 지원 및 정산 금액 등을 확정.', NULL, NULL, NULL, 'p.823', 823, 830, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-191', 'LAW', '운영규정 제9조 (상품 연구 및 보급)', '① 수탁기관은 농업현장 수요가 반영되도록 재해보험상품 연구에 철저를 기하며, 필요 시 재해보험사업자와 공동연구 또는 외부 전문기관 위탁 실시 가능. ② 재해보험사업자는 수탁기관의 상품 연구·보급 업무에 적극 협조하고, 개발용 연구 자료가 필요하면 수탁기관에 요구할 수 있다.', NULL, NULL, NULL, 'p.823', 823, 830, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-192', 'LAW', '운영규정 제10조 (재해 관련 통계 생산 및 데이터베이스 구축·분석)', '① 수탁기관은 농업재해보험 관리 및 상품 개발 활용을 위해 법 제25조의2제1항에 따라 재해 관련 통계를 생산·축적하고 데이터베이스를 구축·분석하여야 한다. ② 재해보험사업자는 상품 개발을 위해 수탁기관의 통계 생산 자료 및 DB 제공을 요구할 수 있다.', NULL, NULL, NULL, 'p.823', 823, 830, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-193', 'LAW', '운영규정 제11조 (통계작업방법서 작성)', '① 수탁기관은 통계 생산·축적 및 사업 관리를 위해 제6조 재보험사업약정 및 재해보험사업약정 체결 시 통계작업방법서를 제시하여 첨부하도록 하여야 한다. ② 통계작업방법서에는 재해보험상품의 각 계약자별·보험증권별 계약정보, 사고정보, 보험금 지급정보 등이 포함되어야 한다.', NULL, NULL, NULL, 'p.823', 823, 830, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-194', 'LAW', '운영규정 제12조 (손해평가기법의 연구·개발 및 보급)', '① 수탁기관은 손해평가의 신속성·편리성·공정성 강화를 위해 법 제25조의2제1항에 따른 손해평가기법을 연구·개발하여 재해보험사업자 및 손해평가사 등에게 보급할 수 있다. ② 필요 시 재해보험사업자와 공동 수행 또는 외부 전문기관 위탁 실시. ③ 재해보험사업자는 연구·개발 및 보급 업무에 협조.', NULL, NULL, NULL, 'p.823', 823, 830, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-195', 'LAW', '운영규정 제13조 (손해평가사 자격시험의 응시원서 및 수수료)', '① 영 제12조의2제3항에 따라 손해평가사 자격시험에 응시하려는 사람은 한국산업인력공단 이사장이 정하는 서식의 응시원서를 한국산업인력공단에 제출. ② 영 제12조의2제4항에 따른 응시수수료: 1. 제1차 시험 = 2만원, 2. 제2차 시험 = 3만3천원. ③ 응시수수료는 응시원서 제출 시 한국산업인력공단에 납부. (수치상수 = ESCALATE, constants INSERT 0.)', NULL, NULL, NULL, 'p.824', 824, 831, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-196', 'LAW', '운영규정 제13조의2 (손해평가사 자격시험 면제신청서류)', '영 제12조의5제3항에 따라 제1차 시험을 면제받으려는 사람은 별지 제4호 서식에 따른 면제신청서를 농림축산식품부장관에게 제출하여야 한다.', NULL, NULL, NULL, 'p.824', 824, 831, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-197', 'LAW', '운영규정 제14조 (손해평가사 자격증의 발급 등)', '① 수탁기관의 장은 영 제12조의7에 따라 자격시험 합격자에게 별지 제1호 서식의 손해평가사 자격증을 발급. ② 발급 시 별지 제2호 서식 발행대장에 기록. ③ 자격증을 잃어버리거나 훼손 등으로 쓸 수 없게 된 경우 별지 제3호 서식 재발급 신청서를 수탁기관에 제출하여 재발급 가능.', NULL, NULL, NULL, 'p.824', 824, 831, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-198', 'LAW', '운영규정 제15조 (손해평가사 교육 및 자격시험 등)', '① 수탁기관은 법 제11조의2 및 영 제12조의8에 따라 손해평가사 능력·자질향상 교육을 실시(위탁 가능: 1. 농식품부 소속 교육기관, 2. 사단법인 보험연수원, 3. 제6조제2항 약정 재해보험사업자, 4. 「민법」 제32조 비영리법인). ② 교육 포함내용: 1. 농업재해보험 관련 법령·제도, 2. 손해평가 이론과 실무, 3. 그 밖에 관련 교육. ③ 손해평가사 이수: 1. 실무교육 = 자격증 취득 후 1회 이상, 2. 보수교육 = 자격증 취득년도 후 3년마다 1회 이상. ④ 원격교육 가능. ⑤ 이수증명서 발급 및 다음 해 1월 15일까지 결과 제출. ⑥ 수탁기관은 교육 경비를 예산 범위에서 지원 가능.', NULL, NULL, NULL, 'p.824', 824, 831, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-199', 'LAW', '운영규정 제16조 (수탁기관의 지도·감독 등)', '농림축산식품부장관은 수탁기관의 지도·감독을 위하여 필요하다고 인정할 때에는 관계서류·장부 기타 참고자료의 제출을 명하거나 소속 공무원으로 하여금 수탁기관의 업무를 점검하게 할 수 있다.', NULL, NULL, NULL, 'p.825', 825, 832, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-200', 'LAW', '운영규정 제17조 (기타 세부사항)', '수탁기관은 이 고시의 시행에 필요한 세부사항에 대해서는 법, 영 및 이 고시에 저촉되지 않는 범위에서 별도로 농림축산식품부장관의 승인을 받아 제정·시행할 수 있다.', NULL, NULL, NULL, 'p.825', 825, 832, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-201', 'LAW', '운영규정 제18조 (재검토기한)', '농림축산식품부장관은 이 고시에 대하여 2020년 7월 1일 기준으로 매 3년이 되는 시점(매 3년째의 6월 30일까지)마다 그 타당성을 검토하여 개선 등의 조치를 하여야 한다.', NULL, NULL, NULL, 'p.825', 825, 832, '재보험사업 및 농업재해보험사업의 운영 등에 관한 규정', '운영규정', 'BATCH-GAP-P2', 2026, 10, 'draft');

-- ============================================================
-- (3) 농업재해보험에서 보상하는 보험목적물의 범위 [농식품부고시 제2025-58호, 시행 2025.5.27.] — 부록2-5, book 826
-- ============================================================

INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-202', 'LAW', '목적물고시 (농업재해보험에서 보상하는 보험목적물의 범위)', '제1조(보험목적물) 「농어업재해보험법」 제5조에 따라 농업재해보험에서 보상하는 보험목적물의 범위는 [표]와 같다. 제2조(재검토기한) 「훈령·예규 등의 발령 및 관리에 관한 규정」에 따라 2025년 7월 1일 기준 매 3년이 되는 시점(매 3년째의 6월 30일까지)마다 타당성 검토. (농림축산식품부고시 제2025-58호, 시행 2025.5.27. — 법 제5조 위임 보험목적물 범위 표 = ESCALATE 규칙3, 표 셀 미적재.)', NULL, NULL, NULL, 'p.826', 826, 833, '농업재해보험에서 보상하는 보험목적물의 범위', '목적물고시', 'BATCH-GAP-P2', 2026, 10, 'draft');

-- ============================================================
-- 엣지 41 (EDGE-GAP-P2-0001~0041) — 기존 엣지 어휘만 (DEPENDS_ON / CROSS_REF)
-- ============================================================

-- 요령 DEPENDS_ON 법 제11조(LAW-145, P1 적재) — 요령 = 법 제11조제2항 위임
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0001', 'LAW-166', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0002', 'LAW-167', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0003', 'LAW-168', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0004', 'LAW-169', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0005', 'LAW-170', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0006', 'LAW-171', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0007', 'LAW-172', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0008', 'LAW-173', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0009', 'LAW-174', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0010', 'LAW-175', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0011', 'LAW-176', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0012', 'LAW-177', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0013', 'LAW-178', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0014', 'LAW-179', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0015', 'LAW-180', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0016', 'LAW-181', 'LAW-145', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0017', 'LAW-182', 'LAW-145', 'DEPENDS_ON', NULL);
-- 요령 제17조(재검토기한) = 요령 내부 조항 → 요령 제1조(목적) DEPENDS_ON
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0018', 'LAW-183', 'LAW-166', 'DEPENDS_ON', NULL);

-- 요령 충돌 4건 = CROSS_REF (기존 요약/개념 노드)
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0019', 'LAW-174', 'CONCEPT-137', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0020', 'LAW-177', 'LAW-003', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0021', 'LAW-178', 'LAW-004', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0022', 'LAW-179', 'CONCEPT-179', 'CROSS_REF', NULL);

-- 운영규정 DEPENDS_ON: 재보험 직결(제1조 목적·제6조 약정·제7조 재보험관리) → 법 제20조 재보험(LAW-046)
--   / 나머지 조문(정의·적용·위탁처리·사업관리·통계·교육 등) → 운영규정 제1조 목적(LAW-184, 운영규정 root)
--   ★독립 리뷰 M2-B 반영: 제5조·제8조(법 제19조 사업비 근거)를 LAW-046(법20조) 대신 LAW-184 로 재앵커(의미 정밀화)
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0023', 'LAW-184', 'LAW-046', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0024', 'LAW-185', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0025', 'LAW-186', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0026', 'LAW-187', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0027', 'LAW-188', 'LAW-046', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0028', 'LAW-189', 'LAW-046', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0029', 'LAW-190', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0030', 'LAW-191', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0031', 'LAW-192', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0032', 'LAW-193', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0033', 'LAW-194', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0034', 'LAW-195', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0035', 'LAW-196', 'LAW-195', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0036', 'LAW-197', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0037', 'LAW-198', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0038', 'LAW-199', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0039', 'LAW-200', 'LAW-184', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0040', 'LAW-201', 'LAW-184', 'DEPENDS_ON', NULL);

-- 목적물고시 DEPENDS_ON 법 제5조(LAW-026) — 법 제5조 위임
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-GAP-P2-0041', 'LAW-202', 'LAW-026', 'DEPENDS_ON', NULL);

-- ============================================================
-- G-GAP 자체 점검 (참고용 — 판정은 독립 리뷰):
--   G-GAP-1 대상완전성: 부록2-3 요령 18조문 + 부록2-4 운영규정 18조문 + 부록2-5 목적물고시 1 = inventory 3 출처단위 전부 커버.
--   G-GAP-2 ID무결성: LAW-166~202 (연번, production 최대 LAW-165 + 1~ 무충돌).
--   G-GAP-4 수치무변조: 5인 이내·30일·7영업일·7일·2년·6개월·2만원·3만3천원·3년·1월15일·매3년 등 조문 본문 수치 원문 전수 대조(독립 리뷰 완료: 불일치 0).
--     (별표1/2/3 산식·표 수치 30,000주·65% 등은 ESCALATE = 노드 미포함이 정상 → 대조 대상 아님.)
--   G-GAP-5 draft-only: 전 INSERT status='draft'. approved 전이문 0.
--   G-GAP-6 행수검산: 노드 37 + 엣지 41 = 78 INSERT.
--   ESCALATE: 별표1(산식)·별표2/3(표)·목적물 범위표·응시수수료 상수 = formulas/constants INSERT 0 (원문 참조만).
-- ============================================================
