-- BATCH 적재 SQL — BATCH-1 (2025)
-- 출처: batch-1-knowledge-graph.json
-- 노드: 75 / 엣지: 133 / 산식: 13 / 상수: 5
-- 적용: wrangler d1 execute <db-name> --file=<this-file> --remote
-- 사전 의무: migration 0019 production 적용 완료
-- 멱등성: INSERT OR IGNORE — 재실행 시 충돌 없음
--
-- AI 생성 데이터 (CLAUDE.md Hard Limit) — status='draft' 만 INSERT
-- 진산님 검수 후 status_transitions UPDATE 로 review/approved 전이
--
-- 주의: D1 wrangler execute --file 은 전체 파일을 자동 트랜잭션으로 감싼다.
-- 명시 BEGIN TRANSACTION/COMMIT 은 D1 거부 (Durable Object 충돌). 의도적으로 생략.

-- 1. knowledge_nodes (75 rows)
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-01', 'INSURANCE', '적과전 종합위험 II', '사과·배·단감·떫은감 4개 품목을 대상으로 하는 종합위험 보험상품. 적과 종료 이전 자연재해(태풍·우박·동상해 등) 모든 위험 + 적과 종료 이후 한정된 재해(태풍·우박·일소·가을동상해) 보장. 시기별 조사 종류: 적과 전 손해조사 / 적과후착과수 조사 / 적과 후 손해조사.', '적과전 종합위험 II', NULL, NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-02', 'INSURANCE', '적과종료 이전 특정위험 5종 한정 보장 특별약관', '5종 한정 특약 — 적과종료 이전 사고가 태풍(강풍)·우박·집중호우·화재·지진 5종에 한해 보장. 적과 종료 이후는 적과전 종합위험 II 본 상품 보장 동일 적용.', '적과전 종합위험 II', NULL, NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-03', 'INSURANCE', '나무손해보장 특약', '보험기간 중 보상하는 재해로 인한 나무 고사로 발생한 손해를 보장. 피해율 = 고사주수 / 실제결과주수. 자기부담비율 5% 적용.', '적과전 종합위험 II', NULL, NULL, 'p.434', 427, 434, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-04', 'INSURANCE', '가을동상해 보장 특약', '수확기(보통 9월 말 ~ 11월) 적과종료 이후 동상해로 인한 과실 피해 보장. 피해인정계수 = 0.0031 × 잔여일수 (착과피해율 산정 시 적용).', '적과전 종합위험 II', NULL, NULL, 'p.424', 417, 424, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-05', 'INSURANCE', '일소피해 보장 특약', '여름철 강한 일사로 인한 과실 피해 보장. 일소 감수과실수 한도 = max(일소감수과실수 - 적과후착과수 × 6%, 0). 자연낙과 한도(6%)를 초과한 부분만 보상.', '적과전 종합위험 II', NULL, NULL, 'p.424', 417, 424, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-06', 'INSURANCE', '착과감소·과실손해 보장', '적과전 종합위험 II 의 주계약 보장 영역. 착과감소량(적과 종료 전 자연재해로 인한 평년착과수 대비 감소분) + 과실손해(적과 종료 이후 누적감수량) 보장.', '적과전 종합위험 II', NULL, NULL, 'p.426', 419, 426, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CROP-001', 'CROP', '사과', '적과전 종합위험 II 대상품목. 적과 종료 시점: 통상 6월 초~중순. 유과타박률 조사: 과총당 동일 위치(번호) 유과(꽃)에 대해 우박피해 여부 조사 (그림 #3).', NULL, '사과', NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CROP-002', 'CROP', '배', '적과전 종합위험 II 대상품목. 적과 종료 시점: 통상 6월 중순. 유과타박률 조사: 사과와 동일 (과총당 동일 위치 유과).', NULL, '배', NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CROP-003', 'CROP', '단감', '적과전 종합위험 II 대상품목. 6월 1일부터 해당 재해 발생 시 낙엽률 조사 실시. 인정피해율 산식: 1.0115 × 낙엽률 - 0.0014 × 경과일수 (떫은감과 다른 계수).', NULL, '단감', NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CROP-004', 'CROP', '떫은감', '적과전 종합위험 II 대상품목. 단감과 동일하게 6월 1일부터 낙엽률 조사. 인정피해율 산식: 0.9662 × 낙엽률 - 0.0703 (단감과 다른 계수). 단감 vs 떫은감 혼동 유형 핵심.', NULL, '떫은감', NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-01', 'FORMULA', '유과타박률', 'F-01 유과타박률 산식 노드. equation_template: damaged_fruits / (damaged_fruits + normal_fruits). 사과·배 적과 전 우박피해 여부 판정. 그림 #3 (book_p407) 시각 가이드.', NULL, '사과·배', '유과타박률 조사', 'p.414', 407, 414, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-02', 'FORMULA', '낙엽률', 'F-02 낙엽률 산식 노드. equation_template: defoliated / (defoliated + attached). 단감·떫은감 적과 후 태풍 등 재해 발생 시 적용. 그림 #6 (book_p416) 가지별 낙엽 판단 기준.', NULL, '단감·떫은감', '낙엽률 조사', 'p.415', 408, 415, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-03', 'FORMULA', '적정표본주수', 'F-03 적정표본주수 산식 노드. equation_template: ceil(total_sample × (variety_target / total_target)). 결과는 올림 정수. 교재 p.417 쓰가루 100/550 → 3주 예시.', NULL, NULL, '표본주 선정', 'p.417', 410, 417, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-04', 'FORMULA', '품종별 착과수', 'F-04 품종별 착과수 산식 노드. equation_template: (sample_fruits_sum / sample_trees_sum) × target_trees. 적과 후 표본주 조사 결과를 전체 조사대상주로 환산.', NULL, NULL, '적과후 착과수 조사', 'p.418', 411, 418, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-05', 'FORMULA', '침수주수 환산', 'F-05 침수주수 환산 산식 노드. equation_template: flooded_trees × (flooded_fruits / total_fruits). 침수 피해주수를 침수 과실비율로 환산한 주수 기준값.', NULL, NULL, '침수피해 조사', 'p.413', 406, 413, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-06', 'FORMULA', '단감 인정피해율', 'F-06 단감 인정피해율 산식 노드. equation_template: max(1.0115 × defoliation_rate - 0.0014 × elapsed_days, 0). 떫은감(F-07)과 계수가 다름 — 혼동 유형 핵심.', NULL, '단감', '낙엽률 조사', 'p.422', 415, 422, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-07', 'FORMULA', '떫은감 인정피해율', 'F-07 떫은감 인정피해율 산식 노드. equation_template: max(0.9662 × defoliation_rate - 0.0703, 0). 단감(F-06)과 달리 경과일수 변수 없음.', NULL, '떫은감', '낙엽률 조사', 'p.422', 415, 422, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-08', 'FORMULA', '착과감소보험금', 'F-08 착과감소보험금 산식 노드. equation_template: max(fruit_reduction - uncompensated - self_bearing, 0) × price × coverage. 적과 종료 전 자연재해로 인한 평년착과수 대비 감소분에 대한 보험금. 그림 #8 (book_p426) 시각화.', '적과전 종합위험 II', NULL, NULL, 'p.426', 419, 426, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-09', 'FORMULA', '과실손해보험금', 'F-09 과실손해보험금 산식 노드. equation_template: max(accumulated_reduction - self_bearing, 0) × price. 적과 종료 이후 누적감수량 대비 보험금. 그림 #9 (book_p426) 시각화.', '적과전 종합위험 II', NULL, NULL, 'p.426', 419, 426, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-10', 'FORMULA', '나무손해 피해율', 'F-10 나무손해 피해율 산식 노드. equation_template: damaged_trees / actual_bearing_trees. 고사나무 / 실제결과주수.', '나무손해보장 특약', NULL, '고사나무 조사', 'p.427', 420, 427, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-11', 'FORMULA', '나무손해보험금', 'F-11 나무손해보험금 산식 노드. equation_template: insured_amount × max(damage_rate - 0.05, 0). 자기부담비율 5% 차감.', '나무손해보장 특약', NULL, NULL, 'p.434', 427, 434, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-12', 'FORMULA', '가을동상해 피해인정계수', 'F-12 가을동상해 피해인정계수 산식 노드. equation_template: 0.0031 × remaining_days. 잔여일수 기준 시간 함수.', '가을동상해 보장 특약', NULL, NULL, 'p.424', 417, 424, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-13', 'FORMULA', '일소 감수과실수 한도', 'F-13 일소 감수과실수 한도 산식 노드. equation_template: max(sunburn_fruits - fruits_after_thinning × 0.06, 0). 자연낙과 한도(6%)를 초과한 부분만 일소피해로 인정.', '일소피해 보장 특약', NULL, NULL, 'p.424', 417, 424, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-001', 'INVESTIGATION', '피해사실확인 조사', '적과 종료 전 자연재해 발생 시 피해 사실을 확인하는 1차 조사. 후속 조사(유과타박률·낙엽률·고사나무 등)의 prerequisite.', NULL, NULL, '피해사실확인 조사', 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-002', 'INVESTIGATION', '적과 전 손해조사', '적과 종료 이전 시기에 실시하는 손해조사. 조사 항목: 피해사실확인 + 유과타박률(사과·배) + 낙엽률(단감·떫은감) + 나무피해. 5종한정특약 가입 시 5종(태풍·우박·집중호우·화재·지진) 한해 실시.', NULL, NULL, '적과 전 손해조사', 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-003', 'INVESTIGATION', '적과후착과수 조사', '사고 여부와 관계없이 가입 전건에 대해 실시하는 의무 조사. 결과는 기준착과수로 사용 (착과감소량 / 과실손해 산정의 기준점). F-04 품종별 착과수 산식 적용.', NULL, NULL, '적과후착과수 조사', 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-004', 'INVESTIGATION', '적과 후 손해조사', '적과 종료 이후부터 수확기 종료까지 실시하는 손해조사. 조사 항목: 낙과수 / 낙엽률(단감·떫은감) / 착과수 / 피해구성률.', NULL, NULL, '적과 후 손해조사', 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-005', 'INVESTIGATION', '유과타박률 조사', '사과·배 우박피해 여부 판정 조사. 과총당 동일 위치(번호) 유과(꽃)에 대하여 조사. 단감·떫은감은 선택된 유과(꽃)에 대해 조사. F-01 산식 적용. 그림 #3 (book_p407) 가이드.', NULL, '사과·배·단감·떫은감', '유과타박률 조사', 'p.414', 407, 414, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-006', 'INVESTIGATION', '낙엽률 조사', '단감·떫은감 6월 1일 이후 재해 발생 시 실시. 가지별 낙엽수 + 착엽수 산출 → F-02 낙엽률 산식 적용 → F-06/F-07 인정피해율 환산. 그림 #6 (book_p416) 시각 가이드.', NULL, '단감·떫은감', '낙엽률 조사', 'p.415', 408, 415, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-007', 'INVESTIGATION', '고사나무 조사', '나무손해보장 특약 가입 건의 고사주수 + 미보상주수 조사. 피해율 = 고사주수 / 실제결과주수. 자기부담비율 5% 적용 후 보험금 산정.', '나무손해보장 특약', NULL, '고사나무 조사', 'p.427', 420, 427, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-008', 'INVESTIGATION', '표본주 선정', '조사대상주수에서 적정표본주수 산정 후 표본주 위치 결정. F-03 적정표본주수 산식 적용. 그림 #4 (book_p411) 표본주 선정 패턴 가이드 (54주 + ★ 표본 위치).', NULL, NULL, '표본주 선정', 'p.418', 411, 418, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-009', 'INVESTIGATION', '침수피해 조사', '집중호우·태풍 등으로 인한 침수 피해 조사. 침수피해나무수 + 침수착과수 + 전체착과수 측정. F-05 침수주수 환산 산식 적용.', NULL, NULL, '침수피해 조사', 'p.413', 406, 413, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-010', 'INVESTIGATION', '일소피해 조사', '여름철 강한 일사로 인한 과실 피해 조사. 일소 감수과실수 한도 = max(일소감수과실수 - 적과후착과수 × 6%, 0). 자연낙과 6% 한도 초과분만 보상. 사고 시마다 낙과 + 착과피해 조사 동시 실시.', '일소피해 보장 특약', NULL, '일소피해 조사', 'p.424', 417, 424, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-011', 'INVESTIGATION', '가을동상해 조사', '수확기(보통 9월 말 ~ 11월) 적과종료 이후 동상해 발생 시 조사. 잔여일수 기준 피해인정계수 = 0.0031 × 잔여일수 (F-12) 적용.', '가을동상해 보장 특약', NULL, '가을동상해 조사', 'p.424', 417, 424, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-012', 'INVESTIGATION', '우박피해 조사', '우박 발생 시 적과 전(유과타박률) 또는 적과 후(낙과·착과피해) 조사. 5종한정특약 시에도 보장 대상 5종 중 하나로 포함.', NULL, NULL, '우박피해 조사', 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-013', 'INVESTIGATION', '태풍피해 조사', '태풍(강풍) 발생 시 낙과수 + 낙엽률(단감·떫은감) + 착과수 + 피해구성률 조사. 5종한정특약 보장 5종에 포함. 태풍피해 입었으나 잎 50% 미만 손상 시 착엽으로 분류 (그림 #6 우측).', NULL, NULL, '태풍피해 조사', 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-014', 'INVESTIGATION', '예찰조사', '재해 발생 후 사전 점검 차원의 조사. 적과 전 손해조사 단계의 일부로 실시. 26년 신설 항목.', NULL, NULL, '예찰조사', 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-015', 'INVESTIGATION', '검증조사', '재해보험사업자/사업관리위탁기관이 손해평가반 결과 확인을 위해 일정 수 임의추출하여 실시하는 사후 조사. 차이 발생 시 결과 정정.', NULL, NULL, '검증조사', 'p.405', 398, 405, '제1장 농업재해보험 손해평가 개관', '제3절 현지조사 내용', 'BATCH-1', 2025, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-001', 'CONCEPT', '손해평가 흐름', '계약자 피해 발생 → 지역 농협 사고 접수 → 재해보험사업자 손해보험 사고접수 → 손해평가 업무배정 → 조사기관 배정 → 조사자(손해평가반) 배정. 그림 #1 (book_p401) 시각 가이드.', NULL, NULL, NULL, 'p.408', 401, 408, '제2장 농작물재해보험 손해평가', '제1절 손해평가 기본단계', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-002', 'CONCEPT', '손해평가 5단계 절차', '(0) 계약자 사고신고 및 전산등록·준비 → (1) 계약 및 기본사항 확인 → (2) 보상하는 재해 여부 심사 → (3) 관련조사 선택 및 실시 → (4) 미보상 비율(양) 확인 → (5) 조사결과 설명 및 서명확인. 그림 #2 (book_p402) 시각 가이드.', NULL, NULL, NULL, 'p.409', 402, 409, '제2장 농작물재해보험 손해평가', '제1절 손해평가 기본단계', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-003', 'CONCEPT', '수관 면적', '나무의 수관(가지·잎이 분포한 영역)이 지면에 투영된 면적. 적과 후 착과수 환산 시 기준값 중 하나. 그림 #5 (book_p414) 점선 표시 정의.', NULL, NULL, NULL, 'p.421', 414, 421, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-004', 'CONCEPT', '평년착과수', '보험가입 시 산출하는 평년 평균 착과량의 주수 환산값. 적과전 종합위험 II 의 보장 기준 중 하나. 적과 종료 시점 적과후착과수와 비교하여 착과감소량 산출.', NULL, NULL, NULL, 'p.428', 421, 428, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-005', 'CONCEPT', '적과후착과수', '적과 종료 시점에 실제 남아있는 착과수 (사고 여부와 관계없이 가입 전건 의무 조사). 기준착과수로 사용 — 과실손해 산정 시 분모.', NULL, NULL, NULL, 'p.418', 411, 418, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-006', 'CONCEPT', '착과감소량', '평년착과수 - 적과후착과수. 적과 종료 전 자연재해로 인한 감소분. F-08 착과감소보험금의 핵심 변수.', NULL, NULL, NULL, 'p.433', 426, 433, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-007', 'CONCEPT', '미보상감수량', '보상하지 않는 사유(병해충·관리부실 등)로 인한 감수량. 보험금 산정 시 차감.', NULL, NULL, NULL, 'p.433', 426, 433, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-008', 'CONCEPT', '자기부담감수량', '자기부담비율을 평년착과수에 곱해 산출한 감수량. 보험금 산정 시 차감.', NULL, NULL, NULL, 'p.433', 426, 433, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-009', 'CONCEPT', '기준착과수', '보장 산정 기준이 되는 착과수. 적과후착과수 100%를 가입착과수로 한 경우 평년착과수와 동일. 그림 #8 #9 (book_p426) 우측 화살표.', NULL, NULL, NULL, 'p.433', 426, 433, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-010', 'CONCEPT', '피해 정도 비율', '적과 후 손해조사 시 사고 과실의 피해 정도 분류 기준. 정상 / 50% / 80% / 100% 4단계 시각 표본 (그림 #7 book_p418).', NULL, NULL, NULL, 'p.425', 418, 425, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-011', 'CONCEPT', '인정피해율', '낙엽률을 인정피해율로 환산하는 회귀식 결과. 단감(F-06) vs 떫은감(F-07) 계수가 다름 — 혼동 유형 핵심.', NULL, '단감·떫은감', NULL, 'p.422', 415, 422, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-012', 'CONCEPT', '착과감소 있음 vs 없음', '평년착과수 > 적과후착과수 = 착과감소 있음 (그림 #8) → F-08 착과감소보험금. 평년착과수 ≈ 적과후착과수 = 착과감소 없음 (그림 #9) → F-09 과실손해보험금만 산정.', NULL, NULL, NULL, 'p.433', 426, 433, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-013', 'CONCEPT', '5종한정특약 보장 재해', '태풍(강풍) / 우박 / 집중호우 / 화재 / 지진. 적과 종료 이전 사고가 5종 중 하나일 때만 보장. 일반 적과전 종합위험 II 가입 시 모든 자연재해 보장 (광범위 vs 한정).', '적과종료 이전 특정위험 5종 한정 보장 특별약관', NULL, NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-014', 'CONCEPT', '자기부담비율', '보험계약자가 부담하는 손해 비율. 나무손해보장 특약은 5% 고정 (CONST-004). 주계약 보장수준에 따라 다름.', NULL, NULL, NULL, 'p.434', 427, 434, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-015', 'CONCEPT', '보장수준', '보험계약자가 선택하는 보장 비율 (예: 70% / 80% / 90%). F-08 착과감소보험금 산정 시 곱셈 인자.', NULL, NULL, NULL, 'p.433', 426, 433, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-016', 'CONCEPT', '가입가격', '보험계약 시 농가가 선택하는 단위당 가격 (예: kg당 가격). F-08 / F-09 보험금 산식의 곱셈 인자.', NULL, NULL, NULL, 'p.433', 426, 433, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-017', 'CONCEPT', '태풍피해 착엽 판단', '태풍피해를 입었어도 잎 손상 50% 미만이면 착엽으로 분류 (낙엽률 산정 시 분모에 포함). 4 케이스: 잎 일부 찢어짐 / 50% 미만 찢김 (2 케이스) / 여러 곳 찢어졌으나 50% 미만. 그림 #6 (book_p416) 우측 가이드.', NULL, '단감·떫은감', NULL, 'p.423', 416, 423, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-018', 'CONCEPT', '단감 vs 떫은감 인정피해율 차이', '동일 낙엽률 0.45에서: 단감 (F-06) = max(1.0115×0.45 - 0.0014×30, 0) = 0.4131 / 떫은감 (F-07) = max(0.9662×0.45 - 0.0703, 0) = 0.3645. 떫은감은 경과일수 변수 없음. 혼동 유형 critical.', NULL, '단감·떫은감', NULL, 'p.422', 415, 422, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-019', 'CONCEPT', '유과타박률 vs 낙엽률', '유과타박률 (F-01) = 사과·배 적과 전 우박피해 / 낙엽률 (F-02) = 단감·떫은감 적과 후 (6월 1일 이후) 낙엽 발생. 적용 품목 + 시기 + 분자 분모 모두 다름. 혼동 유형 high.', NULL, NULL, NULL, 'p.414', 407, 414, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-020', 'CONCEPT', '적과 종료 시점', '사과·배·단감·떫은감 각 품목별 적과 종료 시점. 통상 6월 초~중순. 시점 기준으로 적과 전 / 적과 후 손해조사 분기. 단감·떫은감은 6월 1일부터 낙엽률 조사.', NULL, NULL, NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-001', 'TERM', '유과', '어린 과실. 사과·배의 경우 유과타박률 조사 대상 (적과 전 우박피해 판정).', NULL, NULL, NULL, 'p.414', 407, 414, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-002', 'TERM', '타박률', '유과타박률 = 피해유과수합계 / (피해유과수합계 + 정상유과수합계). 유과의 우박피해 비율.', NULL, NULL, NULL, 'p.414', 407, 414, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-003', 'TERM', '낙엽률', '낙엽률 = 낙엽수합계 / (낙엽수합계 + 착엽수합계). 단감·떫은감 적과 후 잎 손실 비율.', NULL, NULL, NULL, 'p.415', 408, 415, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-004', 'TERM', '적과', '과실 솎아내기. 한 송이에 너무 많이 달린 어린 과실 중 일부를 제거하여 나머지 과실의 품질을 높이는 작업.', NULL, NULL, NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-005', 'TERM', '적과 전', '계약체결일 24시 ~ 적과 종료 시점. 이 기간의 손해는 적과 전 손해조사 대상.', NULL, NULL, NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-006', 'TERM', '적과 후', '적과 종료 시점 ~ 수확기 종료. 이 기간의 손해는 적과 후 손해조사 대상.', NULL, NULL, NULL, 'p.410', 403, 410, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-007', 'TERM', '착엽수', '가지에 붙어있는 정상 잎 수. 낙엽률 산식의 분모 일부.', NULL, NULL, NULL, 'p.415', 408, 415, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-008', 'TERM', '낙엽수', '떨어진 잎 수. 낙엽률 산식의 분자 + 분모 일부. 태풍피해로 잎 50% 이상 손상 시 낙엽으로 분류.', NULL, NULL, NULL, 'p.415', 408, 415, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-009', 'TERM', '조사대상주수', '표본주 선정의 기준이 되는 주수 (전체 가입 주수 - 미보상주수 등). 적정표본주수 산식의 분모.', NULL, NULL, NULL, 'p.417', 410, 417, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-010', 'TERM', '표본주수', '조사를 위해 선정된 대표 주수. F-03 적정표본주수 산식으로 산출 (올림 정수). 그림 #4 (book_p411) 표본주 위치 가이드.', NULL, NULL, NULL, 'p.417', 410, 417, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-011', 'TERM', '실제결과주수', '실제로 결실한 주수. 나무손해 피해율(F-10)의 분모.', NULL, NULL, NULL, 'p.427', 420, 427, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-012', 'TERM', '고사주수', '보상하는 재해로 인해 고사한 나무 수. 나무손해 피해율(F-10)의 분자.', NULL, NULL, NULL, 'p.427', 420, 427, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-013', 'TERM', '미보상주수', '보상 대상이 아닌 사유로 손해가 발생한 주수. 조사대상주수 산정 시 차감.', NULL, NULL, NULL, 'p.427', 420, 427, '제2장 농작물재해보험 손해평가', '제2절 과수작물 손해평가 및 보험금 산정', 'BATCH-1', 2025, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-001', 'LAW', '농어업재해보험법 제8조 (재해보험사업자)', '농림축산식품부장관과 사업 약정을 체결한 자가 재해보험사업자. 손해평가의 주체로 지정.', NULL, NULL, NULL, 'p.401', 394, 401, '제1장 농업재해보험 손해평가 개관', '제2절 손해평가 체계', 'BATCH-1', 2025, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-002', 'LAW', '농어업재해보험법 제11조 (손해평가)', '재해보험사업자는 손해평가인 위촉 또는 손해평가사·손해사정사 위탁으로 손해평가 담당. 손해평가요령에 따른 공정·객관적 손해평가 의무.', NULL, NULL, NULL, 'p.401', 394, 401, '제1장 농업재해보험 손해평가 개관', '제2절 손해평가 체계', 'BATCH-1', 2025, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-003', 'LAW', '농업재해보험 손해평가요령 제11조 (손해평가결과 검증)', '재해보험사업자/사업관리위탁기관이 손해평가반의 손해평가결과 확인을 위해 일정 수 임의추출 검증조사 실시. 농림축산식품부장관 명령 시 응할 의무.', NULL, NULL, NULL, 'p.404', 397, 404, '제1장 농업재해보험 손해평가 개관', '제2절 손해평가 체계', 'BATCH-1', 2025, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-004', 'LAW', '농업재해보험 손해평가요령 제12조 (손해평가 단위)', '손해평가 단위별로 현지조사 실시. 품목·보장방식·재해종류에 따라 조사 종류가 다름. 품목별 현지조사 종류표 기준.', NULL, NULL, NULL, 'p.403', 396, 403, '제1장 농업재해보험 손해평가 개관', NULL, 'BATCH-1', 2025, 10, 'draft');

-- 2. formulas (13 rows, INSERT OR IGNORE — 기존 등록 row 보존)
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-01', '유과타박률', 'damaged_fruits / (damaged_fruits + normal_fruits)', '{"damaged_fruits":"피해유과수합계 integer\u003E=0","normal_fruits":"정상유과수합계 integer\u003E=0"}', 'p.414', 'F-01', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-02', '낙엽률', 'defoliated / (defoliated + attached)', '{"defoliated":"낙엽수합계 integer\u003E=0","attached":"착엽수합계 integer\u003E=0"}', 'p.415', 'F-02', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-03', '적정표본주수', 'ceil(total_sample * (variety_target / total_target))', '{"total_sample":"전체표본주수 integer\u003E=1","variety_target":"품종별조사대상주수 integer\u003E=0","total_target":"조사대상주수합 integer\u003E=1"}', 'p.417', 'F-03', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-04', '품종별 착과수', '(sample_fruits_sum / sample_trees_sum) * target_trees', '{"sample_fruits_sum":"표본주착과수합계 integer\u003E=0","sample_trees_sum":"표본주합계 integer\u003E=1","target_trees":"조사대상주수 integer\u003E=1"}', 'p.418', 'F-04', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-05', '침수주수', 'flooded_trees * (flooded_fruits / total_fruits)', '{"flooded_trees":"침수피해나무수 integer\u003E=0","flooded_fruits":"침수착과수 integer\u003E=0","total_fruits":"전체착과수 integer\u003E=1"}', 'p.413', 'F-05', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-06', '단감 인정피해율', 'max(1.0115 * defoliation_rate - 0.0014 * elapsed_days, 0)', '{"defoliation_rate":"낙엽률 ratio[0,1]","elapsed_days":"경과일수 integer\u003E=0"}', 'p.422', 'F-06', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-07', '떫은감 인정피해율', 'max(0.9662 * defoliation_rate - 0.0703, 0)', '{"defoliation_rate":"낙엽률 ratio[0,1]"}', 'p.422', 'F-07', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-08', '착과감소보험금', 'max(fruit_reduction - uncompensated - self_bearing, 0) * price * coverage', '{"fruit_reduction":"착과감소량 number\u003E=0","uncompensated":"미보상감수량 number\u003E=0","self_bearing":"자기부담감수량 number\u003E=0","price":"가입가격 number\u003E=0","coverage":"보장수준 ratio"}', 'p.426', 'F-08', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-09', '과실손해보험금', 'max(accumulated_reduction - self_bearing, 0) * price', '{"accumulated_reduction":"적과후누적감수량 number\u003E=0","self_bearing":"자기부담감수량 number\u003E=0","price":"가입가격 number\u003E=0"}', 'p.426', 'F-09', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-10', '나무손해 피해율', 'damaged_trees / actual_bearing_trees', '{"damaged_trees":"피해주수(고사나무) integer\u003E=0","actual_bearing_trees":"실제결과주수 integer\u003E=1"}', 'p.427', 'F-10', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-11', '나무손해보험금', 'insured_amount * max(damage_rate - 0.05, 0)', '{"insured_amount":"보험가입금액 number\u003E=0","damage_rate":"피해율 ratio[0,1]"}', 'p.434', 'F-11', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-12', '가을동상해 피해인정계수', '0.0031 * remaining_days', '{"remaining_days":"잔여일수 integer\u003E=0"}', 'p.424', 'F-12', 2025);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-13', '일소 감수과실수 한도', 'max(sunburn_fruits - fruits_after_thinning * 0.06, 0)', '{"sunburn_fruits":"일소감수과실수 integer\u003E=0","fruits_after_thinning":"적과후착과수 integer\u003E=0"}', 'p.424', 'F-13', 2025);

-- 3. constants (5 rows, INSERT OR IGNORE)
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-001', 'coefficient', '단감 인정피해율 낙엽률 계수', '1.0115', 1.0115, '단감 인정피해율 산식 F-06 낙엽률 계수', 'p.422', 2025);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-002', 'coefficient', '단감 인정피해율 경과일수 계수', '0.0014', 0.0014, '단감 인정피해율 산식 F-06 경과일수 계수', 'p.422', 2025);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-003', 'coefficient', '떫은감 인정피해율 낙엽률 계수', '0.9662', 0.9662, '떫은감 인정피해율 산식 F-07 낙엽률 계수', 'p.422', 2025);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-004', 'deductible', '나무손해보험 자기부담비율', '0.05', 0.05, '나무손해보험 산식 F-11 자기부담비율', 'p.434', 2025);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-005', 'ratio', '일소피해 자연낙과 한도 비율', '0.06', 0.06, '일소피해 산식 F-13 자연낙과 한도 비율', 'p.424', 2025);

-- 4. knowledge_edges (133 rows) — nodes 적재 후
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0001', 'INS-01', 'CROP-001', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0002', 'INS-01', 'CROP-002', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0003', 'INS-01', 'CROP-003', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0004', 'INS-01', 'CROP-004', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0005', 'INS-02', 'INS-01', 'EXCEPTION', '5종한정특약 가입 시 적과종료 이전 사고는 태풍·우박·집중호우·화재·지진 5종에 한해 보장');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0006', 'INS-03', 'INS-01', 'DEPENDS_ON', '주계약 부가 특약');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0007', 'INS-03', 'CROP-001', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0008', 'INS-03', 'CROP-002', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0009', 'INS-03', 'CROP-003', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0010', 'INS-03', 'CROP-004', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0011', 'INS-04', 'INS-01', 'DEPENDS_ON', '주계약 부가 특약');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0012', 'INS-05', 'INS-01', 'DEPENDS_ON', '주계약 부가 특약');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0013', 'INS-06', 'INS-01', 'DEFINED_AS', '주계약 보장 영역 (착과감소+과실손해)');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0014', 'INS-01', 'INV-002', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0015', 'INS-01', 'INV-003', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0016', 'INS-01', 'INV-004', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0017', 'INS-01', 'INV-005', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0018', 'INS-03', 'INV-007', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0019', 'INS-04', 'INV-011', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0020', 'INS-05', 'INV-010', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0021', 'INV-001', 'INV-002', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0022', 'INV-001', 'INV-005', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0023', 'INV-001', 'INV-007', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0024', 'INV-002', 'INV-005', 'TIME_CONSTRAINT', '적과 전 시기');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0025', 'INV-002', 'INV-006', 'TIME_CONSTRAINT', '적과 전 시기');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0026', 'INV-003', 'INV-004', 'TIME_CONSTRAINT', '적과 종료 시점 의무 조사');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0027', 'INV-004', 'INV-006', 'TIME_CONSTRAINT', '적과 후 시기');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0028', 'INV-005', 'F-01', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0029', 'INV-005', 'INV-006', 'DIFFERS_FROM', '유과타박률(사과·배 적과 전) vs 낙엽률(단감·떫은감 적과 후)');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0030', 'INV-006', 'F-02', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0031', 'INV-006', 'F-06', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0032', 'INV-006', 'F-07', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0033', 'INV-008', 'F-03', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0034', 'INV-009', 'F-05', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0035', 'INV-007', 'F-10', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0036', 'INV-007', 'F-11', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0037', 'INV-010', 'F-13', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0038', 'INV-011', 'F-12', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0039', 'INV-003', 'F-04', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0040', 'INV-002', 'F-08', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0041', 'INV-004', 'F-09', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0042', 'F-01', 'TERM-001', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0043', 'F-01', 'TERM-002', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0044', 'F-02', 'TERM-003', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0045', 'F-02', 'TERM-007', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0046', 'F-02', 'TERM-008', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0047', 'F-03', 'TERM-009', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0048', 'F-03', 'TERM-010', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0049', 'F-04', 'TERM-009', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0050', 'F-06', 'F-02', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0051', 'F-07', 'F-02', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0052', 'F-06', 'F-07', 'DIFFERS_FROM', '단감(1.0115×낙엽률 - 0.0014×경과일수) vs 떫은감(0.9662×낙엽률 - 0.0703) 계수 차이');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0053', 'F-08', 'CONCEPT-006', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0054', 'F-08', 'CONCEPT-007', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0055', 'F-08', 'CONCEPT-008', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0056', 'F-08', 'CONCEPT-015', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0057', 'F-08', 'CONCEPT-016', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0058', 'F-09', 'CONCEPT-005', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0059', 'F-09', 'CONCEPT-008', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0060', 'F-09', 'CONCEPT-016', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0061', 'F-10', 'TERM-011', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0062', 'F-10', 'TERM-012', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0063', 'F-11', 'F-10', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0064', 'F-11', 'CONCEPT-014', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0065', 'F-12', 'INS-04', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0066', 'F-13', 'INS-05', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0067', 'F-13', 'CONCEPT-005', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0068', 'CROP-003', 'F-06', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0069', 'CROP-004', 'F-07', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0070', 'CROP-001', 'F-01', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0071', 'CROP-002', 'F-01', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0072', 'CROP-003', 'F-02', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0073', 'CROP-004', 'F-02', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0074', 'CROP-001', 'CROP-002', 'SHARED_WITH', '사과·배 동일 유과타박률 조사 패턴');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0075', 'CROP-003', 'CROP-004', 'SHARED_WITH', '단감·떫은감 동일 낙엽률 조사 패턴');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0076', 'CROP-003', 'CROP-004', 'DIFFERS_FROM', '인정피해율 회귀계수 차이 (혼동 유형 핵심)');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0077', 'CONCEPT-001', 'CONCEPT-002', 'PREREQUISITE', '흐름도 → 5단계 절차');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0078', 'CONCEPT-002', 'INV-001', 'PREREQUISITE', '5단계 (3) 관련조사 = 피해사실확인 등');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0079', 'CONCEPT-005', 'INV-003', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0080', 'CONCEPT-006', 'CONCEPT-004', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0081', 'CONCEPT-006', 'CONCEPT-005', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0082', 'CONCEPT-009', 'CONCEPT-005', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0083', 'CONCEPT-011', 'F-06', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0084', 'CONCEPT-011', 'F-07', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0085', 'CONCEPT-012', 'F-08', 'USES_FORMULA', '착과감소 있음 케이스');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0086', 'CONCEPT-012', 'F-09', 'USES_FORMULA', '착과감소 없음 케이스 (그림 #9)');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0087', 'CONCEPT-013', 'INS-02', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0088', 'CONCEPT-014', 'INS-03', 'APPLIES_TO', '나무손해 5%');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0089', 'CONCEPT-017', 'INV-006', 'DEPENDS_ON', '낙엽 vs 착엽 분류 기준');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0090', 'CONCEPT-018', 'F-06', 'DIFFERS_FROM', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0091', 'CONCEPT-018', 'F-07', 'DIFFERS_FROM', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0092', 'CONCEPT-019', 'F-01', 'DIFFERS_FROM', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0093', 'CONCEPT-019', 'F-02', 'DIFFERS_FROM', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0094', 'CONCEPT-020', 'TERM-005', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0095', 'CONCEPT-020', 'TERM-006', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0096', 'TERM-005', 'TERM-006', 'DIFFERS_FROM', '적과 종료 시점 기준 시기 분기');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0097', 'TERM-007', 'TERM-008', 'DIFFERS_FROM', '착엽(붙어있음) vs 낙엽(떨어짐)');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0098', 'TERM-009', 'TERM-013', 'DEPENDS_ON', '조사대상주수 = 가입주수 - 미보상주수 등');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0099', 'TERM-011', 'TERM-012', 'DIFFERS_FROM', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0100', 'LAW-001', 'INV-015', 'GOVERNED_BY', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0101', 'LAW-002', 'INV-001', 'GOVERNED_BY', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0102', 'LAW-002', 'INV-002', 'GOVERNED_BY', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0103', 'LAW-003', 'INV-015', 'GOVERNED_BY', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0104', 'LAW-004', 'INS-01', 'GOVERNED_BY', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0105', 'INV-014', 'INV-002', 'TIME_CONSTRAINT', '적과 전 시기 사전 점검');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0106', 'INV-014', 'INV-001', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0107', 'INS-01', 'CONCEPT-001', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0108', 'INS-01', 'CONCEPT-002', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0109', 'INS-01', 'CONCEPT-013', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0110', 'INV-005', 'CONCEPT-019', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0111', 'INV-006', 'CONCEPT-017', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0112', 'INV-006', 'CONCEPT-019', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0113', 'INV-008', 'CONCEPT-003', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0114', 'INV-006', 'CONCEPT-010', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0115', 'F-06', 'CONCEPT-018', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0116', 'F-07', 'CONCEPT-018', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0117', 'F-08', 'CONCEPT-012', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0118', 'F-09', 'CONCEPT-012', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0119', 'F-04', 'CONCEPT-005', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0120', 'INV-007', 'TERM-011', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0121', 'INV-007', 'TERM-012', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0122', 'INV-007', 'TERM-013', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0123', 'INV-008', 'TERM-009', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0124', 'INV-008', 'TERM-010', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0125', 'INS-01', 'TERM-005', 'TIME_CONSTRAINT', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0126', 'INS-01', 'TERM-006', 'TIME_CONSTRAINT', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0127', 'CONCEPT-013', 'INV-002', 'TIME_CONSTRAINT', '5종한정 시 적과 전 5종 한해 조사');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0128', 'CONCEPT-009', 'INS-06', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0129', 'INS-01', 'INV-012', 'REQUIRES_INVESTIGATION', '우박 발생 시 적과 전(유과타박률) 또는 적과 후(낙과·착과피해)');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0130', 'INS-01', 'INV-013', 'REQUIRES_INVESTIGATION', '태풍 발생 시 낙과·낙엽률·착과수·피해구성률 조사');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0131', 'INS-02', 'INV-012', 'REQUIRES_INVESTIGATION', '5종한정특약 보장 5종 중 우박 사고 시');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0132', 'INS-02', 'INV-013', 'REQUIRES_INVESTIGATION', '5종한정특약 보장 5종 중 태풍 사고 시');
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-1-0133', 'TERM-004', 'CONCEPT-020', 'DEFINED_AS', '적과 종료 시점 = 적과 작업이 종료된 시점');

-- 검증 SQL (적용 후 진산님 직접 확인):
-- SELECT COUNT(*) FROM knowledge_nodes WHERE batch_id='BATCH-1'; -- expect: 75
-- SELECT COUNT(*) FROM knowledge_edges WHERE id LIKE 'EDGE-BATCH-1-%'; -- expect: 133
-- SELECT COUNT(*) FROM formulas WHERE id LIKE 'F-%'; -- expect: \u003E= 13 (기존 등록 합산)
