-- BATCH 적재 SQL — BATCH-R2 (2026)
-- 출처: batch-R2-knowledge-graph.json
-- 노드: 26 / 엣지: 52 / 산식: 0 / 상수: 22
-- 적용: wrangler d1 execute <db-name> --file=<this-file> --remote
-- 사전 의무: migration 0019 production 적용 완료
-- 멱등성: INSERT OR IGNORE — 재실행 시 충돌 없음
--
-- AI 생성 데이터 (CLAUDE.md Hard Limit) — status='draft' 만 INSERT
-- 진산님 검수 후 status_transitions UPDATE 로 review/approved 전이
--
-- 주의: D1 wrangler execute --file 은 전체 파일을 자동 트랜잭션으로 감싼다.
-- 명시 BEGIN TRANSACTION/COMMIT 은 D1 거부 (Durable Object 충돌). 의도적으로 생략.

-- 1. knowledge_nodes (26 rows)
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-178', 'CONCEPT', '[26년 개정 META] 2차 2과목 손해평가의 이론과 실무 변경사항 통합', '26년 2차 2과목 (손해평가의 이론과 실무) 변경사항 통합 학습 객체. 한종찬 교수 정리 (2026-03-31 기준) 10개 대분류: ① 예찰조사 신설 ② 적과전 종합위험방식(낙엽률·일소) ③ 종합위험 수확감소(사과배단감떫은감) ④ 과실손해보장(오디·복분자) ⑤ 종합위험 수확감소 밭작물(수확량조사 적기·표본·산정) ⑥ 생산비보장(노지) ⑦ 인삼·해가림시설 ⑧ 원예시설·버섯 ⑨ 농업수입안정 ⑩ 가축. BATCH-R1과 영역 중첩 시 R1=변경 사실 / R2=구체 명세 (CROSS_REF).', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.1', 1, 1, '26년 개정사항 정리 — 2차 2과목', 'META 통합', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-179', 'CONCEPT', '[26년 신설] 예찰조사 — 사고 미접수 상태 위험 평가 조사', '26년 신설. 예찰조사 = 사고 접수되지 않은 상태에서 보험 목적의 위험 상태를 조사. 적용: 적과전 종합위험·종합과수(농업수입 포함)·논작물(수입안정 포함)·밭작물(수입안정 포함)·차·인삼·시설작물·버섯·축사·가축재해보험. 적과전 = [농업재해보험 손해평가요령 제13조 제4항]. 조사대상=사고 여부 무관 가입한 모든 과수원. 대상재해=해당없음. 조사방법=생육상태 확인. 과실손해조사는 예찰조사 규정 없음. 논작물 등은 (1)가입 전 사고 (2)보상재해 피해 (3)보상 외 원인 수확량 감소 영향 요인 확인. 현지조사 결과 부적정시 보고.', '농작물재해보험·가축재해보험 공통', NULL, NULL, 'p.1', 1, 1, '26년 개정사항 정리 — 2차 2과목', '1. 예찰조사의 신설', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-180', 'CONCEPT', '[26년 정정] 적과전 낙엽률확인조사 종기 정리 (단감·떫은감 5종한정특약)', '26년 정정. 변경전: 단감·떫은감 수확연도 6/1 이후 낙엽피해 시 ''5종한정특약'' 가입건. 변경후: 단감 또는 떫은감, 수확연도 6/1 이후 적과종료 이전까지 낙엽피해 시 ''5종한정특약'' 가입건. 종기=''적과종료 이전'' 명시화. 시기별 조사종류표(신이론서 p20)에 따라 6/1부터 해당재해 발생시 낙엽률 조사 실시. 낙엽률은 적과전·적과후 모두 태풍·지진·집중호우·화재시 조사. 구교재 P24.', '농작물재해보험', '단감·떫은감', NULL, 'p.2', 24, 2, '26년 개정사항 정리 — 2차 2과목', '2. 적과전 종합위험방식 — 낙엽률확인', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-181', 'CONCEPT', '[26년 정정] 적과전 일소피해 사고시 낙과·착과피해 조사 동시 실시', '26년 정정. 일소 피해 사고 시마다 낙과 및 착과피해 조사를 동시 실시. 시기별 조사종류표(신이론서 p20)에서 6/1부터 해당재해 발생시 낙엽율 조사 실시 정합.', '농작물재해보험', '사과·배·단감·떫은감', NULL, 'p.2', 24, 2, '26년 개정사항 정리 — 2차 2과목', '2. 적과전 종합위험방식 — 일소피해', 'BATCH-R2', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-182', 'CONCEPT', '[26년 정합] 사과배단감떫은감 적과전종합위험 vs 종합위험수확감소 택1 가입', '26년 정합. 사과·배·단감·떫은감 품목은 적과전종합위험방식과 종합위험 수확감소보장방식 중 하나만 선택하여 가입하며 동시에 가입할 수 없다. BATCH-R1 CONCEPT-159(과수4종 보험기간 통일)와 보완 — R1=보험기간 / R2=가입방식 택1.', '농작물재해보험', '사과·배·단감·떫은감', NULL, 'p.2', 25, 2, '26년 개정사항 정리 — 2차 2과목', '3. 종합위험 수확감소보장 — 품목의 추가', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-183', 'CONCEPT', '[26년 정정] 과중조사 — 수확기 도래 명시 (품종별 3주 이상 + 20개 추출)', '26년 정정. 변경전: 품종별 착과 평균적인 3주 이상 나무에서 크기 평균적인 과실 20개 이상 추출. 변경후: 품종별로 착과 평균적인 3주 이상 나무에서 크기 평균적이고 ''수확기에 도래한'' 과실을 20개 이상 추출. ''수확기 도래'' 명시화. 농업수입안정보장방식과 표본수 차이는 CONCEPT-199 참조.', '농작물재해보험', NULL, '과중조사', 'p.3', 28, 3, '26년 개정사항 정리 — 2차 2과목', '3. 종합위험 수확감소보장 — 과중조사', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-184', 'CONCEPT', '[26년 신규] 사과 탄저병보장 — 피해율 산식', '26년 신규. 사과에 한하여 탄저병보장. 탄저병 병충해감수량 산정방법은 없으며 피해율 = (평년수확량 - 수확량 - 미보상감수량) ÷ 평년수확량으로 산출 (간이식 표기 = (평-수-미)÷평). 피해인정계수 1.0/0.5는 최종수정본(2026-03-31)에서 삭제됨 (R1 CONCEPT-155 정합). BATCH-R1 CONCEPT-155(보장재해 추가) ↔ R2 CONCEPT-184(피해율 산식) CROSS_REF.', '농작물재해보험', '사과', NULL, 'p.3', 89, 3, '26년 개정사항 정리 — 2차 2과목', '3. 종합위험 수확감소보장 — 병충해 (사과 탄저병)', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-185', 'CONCEPT', '[26년 정합] 비가림시설 자기부담금 — 단지 내 동일일자 사고시 안분 산정', '26년 정합. 단지 내 동일 일자 사고시 각 동별 자기부담금은 각 동 전체 손해액 합계에 해당하는 자기부담금을 각 동별 손해액으로 안분하여 산정한다. 농업용시설물 자기부담금 산정(CONCEPT-198)과 동일 패턴.', '농작물재해보험', '포도·대추·참다래(비가림시설)', NULL, 'p.3', 95, 3, '26년 개정사항 정리 — 2차 2과목', '3. 종합위험 수확감소보장 — 비가림시설 자기부담금', 'BATCH-R2', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-186', 'CONCEPT', '[26년 정정] 오디·복분자 과실손해조사 시기 변경 (조사 기점 명확화)', '26년 정정. ① 오디: 결실완료 직후~최초 수확전 → 결실 완료 후. ② 복분자: 수정완료 직후~최초 수확전 → 수정완료 후. 조사 시기 기점 명확화 (구간 → 시점).', '농작물재해보험', '오디·복분자', '과실손해조사', 'p.3', 145, 3, '26년 개정사항 정리 — 2차 2과목', '4. 과실손해보장 — 오디·복분자 조사시기', 'BATCH-R2', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-187', 'CONCEPT', '[26년 정합] 종합위험 밭작물 수확량조사 적기 (단호박/가을배추/가을무/참깨/당근/생강/녹두)', '26년 정합 품목별 수확량조사 적기: 단호박=과병부 세로 갈색 균열 발생 시기 / 가을배추(병충해보장형 포함)=결구 형성 완료된 때 / 가을무(일반무)=결구 형성 완료된 때 / 참깨=7월말~8월말, 아랫단 꼬투리 2~3개 벌어지는 시기 / 당근=겉잎이 지면에 닿을 정도로 늘어진 시기 / 생강=비대 종료 시점(파종후 180일 이후), 경북 10/30·충남 11월 초 종료 / 녹두=8월 초~10월, 생육 정지+일시수확 가능, 꼬투리 70~80% 흑갈색 변색 시기. 표본구간 측정: 양파·마늘 이랑폭 2m 미만=이랑길이(5주 이상)·이랑폭, 단호박·당근 이랑폭 2m 이상=이랑길이.', '농작물재해보험', '밭작물(단호박/가을배추/가을무/참깨/당근/생강/녹두)', '수확량조사 적기', 'p.5', 165, 5, '26년 개정사항 정리 — 2차 2과목', '5. 종합위험 수확감소보장 밭작물 — 품목별 수확량조사 적기', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-188', 'CONCEPT', '[26년 정합] 표본구간 작물 수확 후 무게 조사 방법 (작물별 정합)', '26년 정합 표본구간 수확 후 조사 방법: 단호박=과병부(꼭지) 절단 후 단호박 무게 조사 (재해로 인해 일반시장 출하 불가+가공용 공급 불가 작물=피해로 인정+0% 수확량 인정). 가을배추(병충해보장형 포함, 무름병 100% 보상)=뿌리 절단·외엽 2겹 내외 제거 후 무게. 참깨=수확가능 꼬투리 총 개수 확인+꼬투리 50~60개 추출(환산중량)+꼬투리 제거 종실 중량 및 함수율 3회 평균 조사(기준함수율 10%). 당근=줄기 절단 후 정상·80% 피해(가공용 공급 가능)·100% 피해(가공용 공급 불가) 구분 무게. 가을무(일반무)=무청 제거 후 무게. 생강=덩이와 가깝게 윗부분 줄기 절단 후 무게. 녹두=꼬투리 제거 후 종실 무게+함수율 3회 평균 (기준함수율 13%).', '농작물재해보험', '밭작물 표본구간 조사', '표본구간 수확량조사', 'p.6', 167, 6, '26년 개정사항 정리 — 2차 2과목', '5. 종합위험 수확감소보장 밭작물 — 표본구간 수확량조사', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-189', 'CONCEPT', '[26년 정합] 표본구간별 수확량 산정 (참깨 0.9 / 녹두 0.87 함수율 환산)', '26년 정합 표본구간 수확량 산정: 감자·수박(노지)·생강·단호박·가을무(일반무)·가을배추(병충해보장형 포함)=표본구간별 작물 무게의 합계. 참깨=표본구간별 참깨 종실중량 × (1-함수율) ÷ 0.9 의 합계 (기준함수율 10%). 녹두=표본구간별 녹두 종실중량 × (1-함수율) ÷ 0.87 의 합계 (기준함수율 13%). 환산계수 의미=수확가능 꼬투리율(참깨)·정상 종실 비율(녹두) 정합.', '농작물재해보험', '참깨·녹두', '수확량 산정', 'p.6', 167, 6, '26년 개정사항 정리 — 2차 2과목', '5. 종합위험 수확감소보장 밭작물 — 표본구간 수확량 산정방법', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-190', 'CONCEPT', '[26년 신규] 생산비보장(노지) 계약변경 조건 추가 (10% 차이 또는 ±1000㎡ 초과)', '26년 신규 계약변경 조건: 실제 경작면적 확인을 위해 GPS 면적측정기 또는 지형도 등을 이용하여 보험가입 면적과 실제 경작면적을 비교한다. 실제 경작면적이 보험가입 면적 대비 10% 이상 차이가 나거나 ±1,000㎡를 초과한 경우에는 계약사항을 변경해야 한다. 적용 품목: 고추·브로콜리·배추(봄·고랭지·월동)·무[고랭지·가을(단무지·알타리)·월동]·파(대파·쪽파·실파)·메밀·시금치(노지)·양상추.', '농작물재해보험', '생산비보장(노지) 전 품목', NULL, 'p.7', 189, 7, '26년 개정사항 정리 — 2차 2과목', '6. 생산비보장(노지) — 계약변경 조건', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-191', 'CONCEPT', '[26년 정정] 메밀 — 평가제외→정상 분류 변경 (재파종 정합)', '26년 정정. 변경전: 기 조사시 100%형 피해로 보험금 지급완료 후 새로 파종한 메밀 등 보장대상과 무관한 작물은 평가제외로 분류하여 조사 (구교재 P206). 변경후: 이때 피해가 없거나 보장하는 재해 이외의 원인으로 피해가 발생한 메밀 및 타작물은 정상으로 분류하여 조사한다.', '농작물재해보험', '메밀', '수확량조사', 'p.7', 206, 7, '26년 개정사항 정리 — 2차 2과목', '6. 생산비보장(노지) — 메밀 분류 변경', 'BATCH-R2', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-192', 'CONCEPT', '[26년 명세] 생산비보장 손해정도비율 조사방법 (구분별)', '26년 명세 (별표6 10% 구간 정합). 브로콜리=피해면적 기준 표본구간 산정·선정+각 표본구간 내 연속하는 10구의 작물피해율 조사+작물피해율(0/50/80/100%). 무(고랭지·가을·월동)=표본구간 내 연속하는 10구의 손해정도비율 조사 (가을무는 단무지무). 파=표본구간 내 연속하는 50구의 손해정도비율 조사. 배추·시금치·양상추·무(알타리무)=표본이랑 산정·선정+표본이랑별 식재 작물(식물체단위) 손해정도비율 조사 (시금치·알타리무 표본이랑 길이 1m 간격 구획). 고추=표본이랑 산정·선정+표본이랑별 식재 작물 손해정도비율 + 고추 병충해 등급별 인정비율 구분 조사. 메밀=표본구간 산정·선정+규격 원형(1㎡) 또는 가로·세로(1m×1m) 구획 조사. BATCH-R1 CONCEPT-171(준비기생산비계수+손해정도비율) CROSS_REF.', '농작물재해보험', '생산비보장(노지) 전 품목', '손해정도비율 조사', 'p.8', 200, 8, '26년 개정사항 정리 — 2차 2과목', '6+8. 손해정도비율 조사방법 (오류 정정 + 명세화)', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-193', 'CONCEPT', '[26년 변경] 인삼 전수조사 피해율 — 피해면적=피해칸수 (구 금차수확칸수)', '26년 변경. 인삼 전수조사 시 피해율 = (수확량/연근별기준수확량) × (피해면적/재배면적). 피해면적 정의 변경: 기존 ''금차수확칸수'' → ''피해칸수''로 변경. 재배면적 = 실제경작칸수.', '농작물재해보험', '인삼', '전수조사', 'p.9', 226, 9, '26년 개정사항 정리 — 2차 2과목', '7. 인삼 — 피해면적 정의 변경', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-194', 'CONCEPT', '[26년 변경] 해가림시설 비례보상 (재조달가액 보장 분기)', '26년 변경. 보험가입금액이 보험가액보다 작을 때(일부보험) 보험가입금액 한도 비례보상. (가) 재조달가액 보장 특별약관 미가입 또는 가입+수리복구 미실시 = 지급보험금 = (손해액 - 자기부담금) × (보험가입금액 ÷ 보험가액). (나) 재조달가액 보장 특별약관 가입+수리복구 실시 = 지급보험금 = (손해액 - 자기부담금) × (보험가입금액 ÷ 재조달가액). 자기부담금 = 손해액의 10%, 최소 10만원~최대 100만원 한도.', '농작물재해보험', '해가림시설', NULL, 'p.9', 231, 9, '26년 개정사항 정리 — 2차 2과목', '7. 해가림시설 — 비례보상 + 자기부담금', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-195', 'CONCEPT', '[26년 변경] 해가림시설 비용손해 — 자기부담금 공제대상 아님', '26년 변경. 비용손해 중 손해방지비용·대위권 보전비용·잔존물 보전비용·기타 협력비용은 보험가입금액을 초과하는 경우에도 지급한다 (단 농지별 손해방지비용은 20만원 한도 / min(실비×가입금액÷보험가액 또는 재조달가액, 20만원)). 비례보상 = 보험가입금액 ÷ 보험가액 또는 재조달가액. 비용 구분 — 손해방지·대위권·잔존물 보전비용=가입금액 초과보상+비례보상 모두 ○ / 기타협력비용=초과보상 ○·비례보상 X. 26년 변경 핵심: 자기부담금 공제대상 아님 + 비례보상 ÷ 분모에 재조달가액 포함. 잔존물 보전비용은 재해보험사업자 잔존물 취득 의사표시+취득 시에 한하여 지급.', '농작물재해보험', '해가림시설', NULL, 'p.9', 231, 9, '26년 개정사항 정리 — 2차 2과목', '7. 해가림시설 — 비용손해 자기부담금', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-196', 'CONCEPT', '[26년 추가] 부대시설 — 시설재배 농작물 대상 선별기 (휴대용 제외, 버섯재배사 제외)', '26년 추가. 부대시설 정의 추가 (라): 농업용 시설물 내부에 고정·연결 부착되고 동력을 공급받아 시설재배 농작물 대상으로 활용하는 선별기 (단 휴대용 선별기는 포함하지 않음). 주: 버섯재배사의 경우 선별기는 부대시설에서 제외 (약관의 변경시기 때문에 버섯은 수정되지 않은 것으로 추정).', '농작물재해보험', '부대시설(원예)', NULL, 'p.10', 251, 10, '26년 개정사항 정리 — 2차 2과목', '8. 원예시설 및 버섯 — 부대시설 선별기 추가', 'BATCH-R2', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-197', 'CONCEPT', '[26년 정합] 원예시설작물 보장하는 재해 — 시설물 직접피해 + 예외 4종 (일조량 30/4/15)', '26년 정합 (라): 자연재해로 시설물에 직접적 피해 발생 시에만 시설작물 피해 보상. 단 농업용시설물에 직접 피해가 발생하지 않더라도 다음 4종 보상: ① 시설작물 피해율 70% 이상 발생하여 전체 재배 포기 ② 기상특보 발령지역의 기상특보 관련 재해로 시설작물 피해 발생 ③ 시설재배 농작물에 조수해 피해 발생 ④ 농작물재해보험 사업시행지침에 따라 인정된 일조량 부족 재해 시·군 등에서 관련 재해로 작물 피해 발생. 일조량 부족 판단 기준: 연속된 30일 중 누적 일조시수(측정일부터 측정일 직전 2일 전까지 3일간 구간평균) 4시간 이하인 일수가 15일 이상인 경우. 버섯 작물 = 표고확장위험보장특약 가입 시 ①·② + 시설물(버섯재배사) 직접피해 발생 시 자연재해/조수해로 발생 손해 보상. BATCH-R1 CONCEPT-155(보장재해 추가, 일조량 부족) CROSS_REF.', '농작물재해보험', '원예시설작물·버섯', NULL, 'p.10', 252, 10, '26년 개정사항 정리 — 2차 2과목', '8. 원예시설 및 버섯 — 보장하는 재해', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-198', 'CONCEPT', '[26년 변경] 농업용시설물 자기부담금 — 단지·1사고 합계 기준 안분 (비가림시설 동일)', '26년 변경 (3). 농업용시설물과 부대시설 모두를 보험의 목적으로 하는 보험계약은 두 보험 목적의 손해액 합계액을 기준으로 자기부담금을 산출하고 두 목적물의 손해액 비율로 자기부담금을 적용. 단 동일단지에 농업용시설물 수 개동이 동일 일자에 사고시 각 동별 자기부담금은 각 동별 손해액 합계로 전체 단지별·1사고별 자기부담금 산정 후 각 동별 손해액 비율로 각 동별 자기부담금 적용. 비가림시설(CONCEPT-185)과 동일 패턴.', '농작물재해보험', '농업용시설물·부대시설', NULL, 'p.10', 254, 10, '26년 개정사항 정리 — 2차 2과목', '8. 원예시설 및 버섯 — 농업용시설물 자기부담금 산정', 'BATCH-R2', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-199', 'CONCEPT', '[26년 정정] 농업수입안정보장 표본과실수 — 과중 20 / 착과 30 / 낙과 30 (포·복·만)', '26년 정정. 농업수입안정보장 포도·복숭아·만감류 조사별 표본과실수: ① 과중조사 = 품종별 20개 이상 ② 착과피해조사 = 품종별 30개 이상 ③ 낙과피해조사 = 품종별 30개 이상. 수확감소보장방식과 차이: 수확감소보장 모두 품종별 20개 이상 통일. 농업수입안정보장은 과중조사만 20개 동일+착과/낙과는 30개 차별.', '농작물재해보험', '포도·복숭아·만감류(농업수입안정)', '농업수입안정 조사', 'p.11', 268, 11, '26년 개정사항 정리 — 2차 2과목', '9. 농업수입안정보장 — 표본과실수', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-200', 'CONCEPT', '[26년 명세] 농업수입안정 보험금 산식 — 과거수입형 / 기대수입형 (옥수수 외)', '26년 명세 (옥수수 외). 과거수입형: 보험금 = 보험가입금액 × (피해율 - 자기부담비율) / 피해율 = (기준수입 - 실제수입) ÷ 기준수입 / 기준수입 = 평년수확량 × 기준가격 / 실제수입 = (수확량 + 미보상감수량 - 병충해감수량(복숭아·감자만)) × 수확기가격. 기대수입형: 보험금 = 기준수입 × (피해율 - 자기부담비율) / 피해율 동일 / 기준수입 = 평년수확량 × max(기준가격, 수확기가격) (수확기가격 ≤ 기준가격×1.5) / 실제수입 동일. BATCH-R1 CONCEPT-173(가격조항+보험금 변경) CROSS_REF — R1=변경 사실 / R2=산식 명세.', '농작물재해보험', '농업수입안정 (옥수수 외)', NULL, 'p.11', 270, 11, '26년 개정사항 정리 — 2차 2과목', '9. 농업수입안정보장 — 보험금 산식', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-201', 'CONCEPT', '[26년 명세] 농업수입안정 옥수수 — 보험금 + 손해액 산식 (이론서·약관 차이)', '26년 명세. 옥수수 과거수입형: 보험금 = 보험가입금액 × (피해율 - 자기부담비율) / 피해율 = (기준수입 - 실제수입) ÷ 기준수입 / 기준수입 = 평년수확량 × 기준가격 / 실제수입 = 기준수입 - 실제 조사 손해액. 옥수수 기대수입형: 보험금 = 기준수입 × (피해율 - 자기부담비율) / 기준수입 = 평년수확량 × max(기준가격, 수확기가격) / 실제수입 = 기준수입 - 실제 조사 손해액. ① 재산출 평년수확량 > 보험가입시 평년수확량 = 보험금 = 기준수입 × (가입수확량/재산출평년수확량) × (피해율 - 자기부담비율). ② 재산출 평년수확량 < 보험가입시 평년수확량 = 보험가입시 평년수확량과 가입수확량을 보험가입시 산정한 값 대신 재산출평년수확량으로 함. ※ 이론서는 약관과 달리 과거/기대 구분 없음 (오류). 손해액 산식: (1) 기준가격 ≥ 수확기가격: 손해액 = (기준가격-수확기가격) × (평년수확량-피해수확량) + (기준가격 × 피해수확량). (2) 기준가격 < 수확기가격: 손해액 = 기준가격 × 피해수확량. ※ 기준가격 < 수확기가격 시 기대수입형 기준수입 산정에는 평년수확량×수확기가격이 들어가지만 손해액 산정에서는 기준가격을 곱하는 오류 (이론서 표기 모순).', '농작물재해보험', '옥수수(농업수입안정)', NULL, 'p.11', 272, 11, '26년 개정사항 정리 — 2차 2과목', '9. 농업수입안정보장 — 옥수수 보험금/손해액', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-202', 'CONCEPT', '[26년 정정] 돼지축산휴지위험보장 특약 — 종빈돈마리수 명시 (산식 오타 정정)', '26년 정정. 변경전: 종빈돈 × 10 × 1두당 비육돈(100kg 기준) 평균가격 × 이익률. 변경후: 종빈돈마리수 × 10 × 1두당 비육돈(100kg 기준) 평균가격 × 이익률. 단위 명시 (마리수). 기존 BATCH-6 F-145(축산휴지손해 보험가액)·F-144(이익률)·F-143(돼지질병위험보장 특약 보험가액)·F-151(돼지질병위험보장 특약 자기부담금)·INS-41(돼지축산휴지위험보장 특약)·INV-084(축산휴지손해 이익률 산정)·CONCEPT-129(이익률 조정 축산휴지위험보장)·TERM-057(축산휴지/축산휴지손해/사업이익) CROSS_REF.', '가축재해보험', '돼지(축산휴지위험보장 특약)', NULL, 'p.12', 286, 12, '26년 개정사항 정리 — 2차 2과목', '10. 가축 — 돼지축산휴지위험보장 특약', 'BATCH-R2', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-203', 'CONCEPT', '[26년 정합] 가축재해보험 부문별 특별약관 정리표', '26년 정합 부문별 특약 적용표. 돼지=전기적장치 위험보장·폭염재해보장. 가금=전기적장치 위험보장·폭염재해보장. 말=씨수말 번식첫해 선천성 불임 확장보장·말운송위험 확장보장·경주마 부적격·경주마 보험기간 설정에 관한 특별약관. 기타 가축=폐사 긴급도축 확장보상·꿀벌 낭충봉아부패병보장·꿀벌 부저병보장. 축사=설해손해 부보장. 부문별 특약 매트릭스 정합 (돼지O / 가금O / 말O / 기타O / 축사O 또는 -). BATCH-R1 CONCEPT-176(가축 가입조건+국고지원) CROSS_REF.', '가축재해보험', '가축재해보험 전 부문', NULL, 'p.12', 290, 12, '26년 개정사항 정리 — 2차 2과목', '10. 가축 — 특별약관 정리', 'BATCH-R2', 2026, 10, 'draft');

-- 2. formulas (0 rows, INSERT OR IGNORE — 기존 등록 row 보존)

-- 3. constants (22 rows, INSERT OR IGNORE)
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-163', 'ratio', '26년 단호박 가공용 인정 무게 비율 (피해 인정)', '0.00', 0.0, '26년 단호박 가공용 인정 무게 비율 (피해 인정)', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-164', 'ratio', '26년 참깨 기준함수율', '0.10', 0.1, '26년 참깨 기준함수율', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-165', 'ratio', '26년 녹두 기준함수율', '0.13', 0.13, '26년 녹두 기준함수율', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-166', 'sample', '26년 참깨 환산중량 추출 최소 꼬투리 수', '50', 50.0, '26년 참깨 환산중량 추출 최소 꼬투리 수', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-167', 'sample', '26년 참깨 환산중량 추출 최대 꼬투리 수', '60', 60.0, '26년 참깨 환산중량 추출 최대 꼬투리 수', 'p.6', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-168', 'sample', '26년 농업수입안정 과중조사 품종별 최소 표본과실수', '20', 20.0, '26년 농업수입안정 과중조사 품종별 최소 표본과실수', 'p.11', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-169', 'sample', '26년 농업수입안정 착과피해조사 품종별 최소 표본과실수', '30', 30.0, '26년 농업수입안정 착과피해조사 품종별 최소 표본과실수', 'p.11', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-170', 'sample', '26년 농업수입안정 낙과피해조사 품종별 최소 표본과실수', '30', 30.0, '26년 농업수입안정 낙과피해조사 품종별 최소 표본과실수', 'p.11', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-171', 'ratio', '26년 농업수입안정 기대수입형 수확기가격 한도 배수', '1.50', 1.5, '26년 농업수입안정 기대수입형 수확기가격 한도 배수', 'p.11', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-172', 'deductible', '26년 해가림시설 자기부담금 최소 한도 (원)', '100000', 100000.0, '26년 해가림시설 자기부담금 최소 한도 (원)', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-173', 'deductible', '26년 해가림시설 자기부담금 최대 한도 (원)', '1000000', 1000000.0, '26년 해가림시설 자기부담금 최대 한도 (원)', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-174', 'ratio', '26년 해가림시설 자기부담금 비율 (손해액 대비)', '0.10', 0.1, '26년 해가림시설 자기부담금 비율 (손해액 대비)', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-175', 'deductible', '26년 해가림시설 농지별 손해방지비용 한도 (원)', '200000', 200000.0, '26년 해가림시설 농지별 손해방지비용 한도 (원)', 'p.9', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-176', 'threshold', '26년 원예시설작물 일조량 부족 누적 일조시수 임계 (시간)', '4', 4.0, '26년 원예시설작물 일조량 부족 누적 일조시수 임계 (시간)', 'p.10', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-177', 'threshold', '26년 원예시설작물 일조량 부족 일수 임계 (일)', '15', 15.0, '26년 원예시설작물 일조량 부족 일수 임계 (일)', 'p.10', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-178', 'threshold', '26년 원예시설작물 일조량 부족 측정기간 (일)', '30', 30.0, '26년 원예시설작물 일조량 부족 측정기간 (일)', 'p.10', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-179', 'ratio', '26년 생산비보장(노지) 계약변경 면적 차이 비율 한도', '0.10', 0.1, '26년 생산비보장(노지) 계약변경 면적 차이 비율 한도', 'p.7', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-180', 'threshold', '26년 생산비보장(노지) 계약변경 면적 차이 절대값 한도 (㎡)', '1000', 1000.0, '26년 생산비보장(노지) 계약변경 면적 차이 절대값 한도 (㎡)', 'p.7', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-181', 'sample', '26년 손해정도비율 표본구간 작물수 (브로콜리·무)', '10', 10.0, '26년 손해정도비율 표본구간 작물수 (브로콜리·무)', 'p.8', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-182', 'sample', '26년 손해정도비율 표본구간 작물수 (파)', '50', 50.0, '26년 손해정도비율 표본구간 작물수 (파)', 'p.8', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-183', 'threshold', '26년 시금치·알타리무 표본이랑 길이 간격 (m)', '1', 1.0, '26년 시금치·알타리무 표본이랑 길이 간격 (m)', 'p.8', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-184', 'sample', '26년 과중조사 품종별 최소 표본 나무수 (수확감소보장+농업수입안정 공통)', '3', 3.0, '26년 과중조사 품종별 최소 표본 나무수 (수확감소보장+농업수입안정 공통)', 'p.3', 2026);

-- 4. knowledge_edges (52 rows) — nodes 적재 후
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0001', 'CONCEPT-178', 'CONCEPT-179', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0002', 'CONCEPT-178', 'CONCEPT-180', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0003', 'CONCEPT-178', 'CONCEPT-181', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0004', 'CONCEPT-178', 'CONCEPT-182', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0005', 'CONCEPT-178', 'CONCEPT-183', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0006', 'CONCEPT-178', 'CONCEPT-184', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0007', 'CONCEPT-178', 'CONCEPT-185', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0008', 'CONCEPT-178', 'CONCEPT-186', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0009', 'CONCEPT-178', 'CONCEPT-187', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0010', 'CONCEPT-178', 'CONCEPT-188', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0011', 'CONCEPT-178', 'CONCEPT-189', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0012', 'CONCEPT-178', 'CONCEPT-190', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0013', 'CONCEPT-178', 'CONCEPT-191', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0014', 'CONCEPT-178', 'CONCEPT-192', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0015', 'CONCEPT-178', 'CONCEPT-193', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0016', 'CONCEPT-178', 'CONCEPT-194', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0017', 'CONCEPT-178', 'CONCEPT-195', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0018', 'CONCEPT-178', 'CONCEPT-196', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0019', 'CONCEPT-178', 'CONCEPT-197', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0020', 'CONCEPT-178', 'CONCEPT-198', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0021', 'CONCEPT-178', 'CONCEPT-199', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0022', 'CONCEPT-178', 'CONCEPT-200', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0023', 'CONCEPT-178', 'CONCEPT-201', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0024', 'CONCEPT-178', 'CONCEPT-202', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0025', 'CONCEPT-178', 'CONCEPT-203', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0026', 'CONCEPT-179', 'CONCEPT-180', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0027', 'CONCEPT-179', 'CONCEPT-181', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0028', 'CONCEPT-183', 'CONCEPT-182', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0029', 'CONCEPT-184', 'CONCEPT-183', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0030', 'CONCEPT-188', 'CONCEPT-187', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0031', 'CONCEPT-189', 'CONCEPT-188', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0032', 'CONCEPT-195', 'CONCEPT-194', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0033', 'CONCEPT-201', 'CONCEPT-200', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0034', 'CONCEPT-184', 'CONCEPT-155', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0035', 'CONCEPT-187', 'CONCEPT-167', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0036', 'CONCEPT-189', 'CONCEPT-167', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0037', 'CONCEPT-192', 'CONCEPT-171', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0038', 'CONCEPT-193', 'CONCEPT-170', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0039', 'CONCEPT-194', 'CONCEPT-170', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0040', 'CONCEPT-197', 'CONCEPT-155', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0041', 'CONCEPT-200', 'CONCEPT-173', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0042', 'CONCEPT-202', 'CONCEPT-176', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0043', 'CONCEPT-203', 'CONCEPT-176', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0044', 'CONCEPT-182', 'INS-01', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0045', 'CONCEPT-186', 'INV-054', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0046', 'CONCEPT-186', 'CROP-018', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0047', 'CONCEPT-194', 'CROP-059', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0048', 'CONCEPT-195', 'CROP-059', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0049', 'CONCEPT-196', 'INS-27', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0050', 'CONCEPT-197', 'INS-27', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0051', 'CONCEPT-202', 'INS-41', 'CROSS_REF', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-R2-0052', 'CONCEPT-203', 'INS-33', 'CROSS_REF', NULL);

-- 검증 SQL (적용 후 진산님 직접 확인):
-- SELECT COUNT(*) FROM knowledge_nodes WHERE batch_id='BATCH-R2'; -- expect: 26
-- SELECT COUNT(*) FROM knowledge_edges WHERE id LIKE 'EDGE-BATCH-R2-%'; -- expect: 52
-- SELECT COUNT(*) FROM formulas WHERE id LIKE 'F-%'; -- expect: \u003E= 0 (기존 등록 합산)
