-- ============================================================
-- Phase 2A 별표 1 LAW-138 적재 — TBL-001 부모 (H_nested) + 15 sub-tables
-- Session 055 후속 (2026-05-08)
-- 적재 단위: 16 tables + 모든 headers + 모든 cells + 16 node_links
-- 순서: ① 16 table_structures → ② 모든 headers → ③ 모든 cells (nested_table FK 정합) → ④ node_links
-- BEGIN/COMMIT 미포함 — wrangler d1 execute 자동 wrap (TD-S49-1).
-- ============================================================

-- ① table_structures (16 rows)
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-001', 'LAW-138', '농작물재해보험 품목별 표본주(구간)수 표 — 15 분류 nested 부모 (옵션 C 패턴-H)', 'H_nested', 15, 1, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-002', 'LAW-138', '사과/배/단감 등 표본주수 표 (50주~1000주+ 13구간)', 'A_simple', 13, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-003', 'LAW-138', '유자 표본주수 표 (50주~800주+ 6구간)', 'A_simple', 6, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-004', 'LAW-138', '참다래/블루베리 표본주수 표 (50주~800주+ 6구간)', 'A_simple', 6, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-005', 'LAW-138', '매실/대추/살구 표본주수 표 (100주~1000주+ 5구간)', 'A_simple', 5, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-006', 'LAW-138', '오미자 표본주수 표 (유인틀 길이 500m~6000m+ 6구간)', 'A_simple', 6, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-007', 'LAW-138', '오디 표본주수 표 (50주~600주+ 8구간)', 'A_simple', 8, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-008', 'LAW-138', '복분자 표본포기수 표 (1000~3000포기+ 6구간)', 'A_simple', 6, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-009', 'LAW-138', '감귤(온주밀감류) 표본주수 표 (5000~10000㎡+ 3구간)', 'A_simple', 3, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-010', 'LAW-138', '벼/밀/보리/귀리 표본구간수 표 (2000~6000㎡+ 6구간)', 'A_simple', 6, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-011', 'LAW-138', '고구마/양파/마늘/옥수수/양배추/단호박 표본구간수 표 (1500~4500㎡+ 4구간)', 'A_simple', 4, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-016', 'LAW-138', '감자/차/콩/팥/수박/당근 등 표본구간수 표 (2500~10000㎡+ 5구간)', 'A_simple', 5, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-017', 'LAW-138', '인삼 표본칸수 표 (300~1800칸+ 8구간)', 'A_simple', 8, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-018', 'LAW-138', '고추/메밀/브로콜리/배추/무/파/시금치/양상추 표본구간(이랑)수 표 (3000~15000㎡+ 4구간)', 'A_simple', 4, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-019', 'LAW-138', '두릅 표본구간(이랑)수 표 (3000~15000㎡+ 4구간)', 'A_simple', 4, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');
INSERT INTO table_structures (id, source_node_id, title, pattern_type, row_count, col_count, source, status) VALUES ('TBL-020', 'LAW-138', '참깨/녹두 표본구간수 표 (1000~10000㎡+ 5구간)', 'A_simple', 6, 2, '교재 별표1 / book_page=684 / pdf_page=691 / LAW-138 PDF 정확 매트릭스 — sub-table', 'draft');

-- ② table_headers (136 rows)
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-01', 'TBL-001', 'row', 1, 1, NULL, '사과/배/단감/떫은감/포도(농업수입안정 포함)/복숭아/자두/밤/호두/무화과/감귤(만감류)');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-02', 'TBL-001', 'row', 1, 2, NULL, '유자');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-03', 'TBL-001', 'row', 1, 3, NULL, '참다래/블루베리');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-04', 'TBL-001', 'row', 1, 4, NULL, '매실/대추/살구');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-05', 'TBL-001', 'row', 1, 5, NULL, '오미자');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-06', 'TBL-001', 'row', 1, 6, NULL, '오디');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-07', 'TBL-001', 'row', 1, 7, NULL, '복분자');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-08', 'TBL-001', 'row', 1, 8, NULL, '감귤(온주밀감류)');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-09', 'TBL-001', 'row', 1, 9, NULL, '벼/밀/보리/귀리');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-10', 'TBL-001', 'row', 1, 10, NULL, '고구마/양파/마늘/옥수수/양배추/단호박 (수입보장 포함)');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-11', 'TBL-001', 'row', 1, 11, NULL, '감자/차/콩/팥/수박/당근/생강/고랭지무/가을무(일반)/고랭지배추/가을배추 (수입보장 포함)');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-12', 'TBL-001', 'row', 1, 12, NULL, '인삼');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-13', 'TBL-001', 'row', 1, 13, NULL, '고추/메밀/브로콜리/배추(봄/고랭지/월동)/무/파/시금치/양상추');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-14', 'TBL-001', 'row', 1, 14, NULL, '두릅');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-001-15', 'TBL-001', 'row', 1, 15, NULL, '참깨/녹두');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-001-01', 'TBL-001', 'column', 1, 1, NULL, '표본주(구간)수 표');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-01', 'TBL-002', 'row', 1, 1, NULL, '50주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-02', 'TBL-002', 'row', 1, 2, NULL, '50주 이상 100주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-03', 'TBL-002', 'row', 1, 3, NULL, '100주 이상 150주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-04', 'TBL-002', 'row', 1, 4, NULL, '150주 이상 200주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-05', 'TBL-002', 'row', 1, 5, NULL, '200주 이상 300주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-06', 'TBL-002', 'row', 1, 6, NULL, '300주 이상 400주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-07', 'TBL-002', 'row', 1, 7, NULL, '400주 이상 500주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-08', 'TBL-002', 'row', 1, 8, NULL, '500주 이상 600주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-09', 'TBL-002', 'row', 1, 9, NULL, '600주 이상 700주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-10', 'TBL-002', 'row', 1, 10, NULL, '700주 이상 800주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-11', 'TBL-002', 'row', 1, 11, NULL, '800주 이상 900주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-12', 'TBL-002', 'row', 1, 12, NULL, '900주 이상 1,000주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-002-13', 'TBL-002', 'row', 1, 13, NULL, '1,000주 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-002-01', 'TBL-002', 'column', 1, 1, NULL, '조사대상주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-002-02', 'TBL-002', 'column', 1, 2, NULL, '표본주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-003-01', 'TBL-003', 'row', 1, 1, NULL, '50주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-003-02', 'TBL-003', 'row', 1, 2, NULL, '50주 이상 100주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-003-03', 'TBL-003', 'row', 1, 3, NULL, '100주 이상 200주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-003-04', 'TBL-003', 'row', 1, 4, NULL, '200주 이상 500주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-003-05', 'TBL-003', 'row', 1, 5, NULL, '500주 이상 800주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-003-06', 'TBL-003', 'row', 1, 6, NULL, '800주 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-003-01', 'TBL-003', 'column', 1, 1, NULL, '조사대상주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-003-02', 'TBL-003', 'column', 1, 2, NULL, '표본주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-004-01', 'TBL-004', 'row', 1, 1, NULL, '50주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-004-02', 'TBL-004', 'row', 1, 2, NULL, '50주 이상 100주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-004-03', 'TBL-004', 'row', 1, 3, NULL, '100주 이상 200주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-004-04', 'TBL-004', 'row', 1, 4, NULL, '200주 이상 500주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-004-05', 'TBL-004', 'row', 1, 5, NULL, '500주 이상 800주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-004-06', 'TBL-004', 'row', 1, 6, NULL, '800주 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-004-01', 'TBL-004', 'column', 1, 1, NULL, '조사대상주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-004-02', 'TBL-004', 'column', 1, 2, NULL, '표본주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-005-01', 'TBL-005', 'row', 1, 1, NULL, '100주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-005-02', 'TBL-005', 'row', 1, 2, NULL, '100주 이상 300주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-005-03', 'TBL-005', 'row', 1, 3, NULL, '300주 이상 500주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-005-04', 'TBL-005', 'row', 1, 4, NULL, '500주 이상 1,000주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-005-05', 'TBL-005', 'row', 1, 5, NULL, '1,000주 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-005-01', 'TBL-005', 'column', 1, 1, NULL, '조사대상주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-005-02', 'TBL-005', 'column', 1, 2, NULL, '표본주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-006-01', 'TBL-006', 'row', 1, 1, NULL, '500m 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-006-02', 'TBL-006', 'row', 1, 2, NULL, '500m 이상 1,000m 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-006-03', 'TBL-006', 'row', 1, 3, NULL, '1,000m 이상 2,000m 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-006-04', 'TBL-006', 'row', 1, 4, NULL, '2,000m 이상 4,000m 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-006-05', 'TBL-006', 'row', 1, 5, NULL, '4,000m 이상 6,000m 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-006-06', 'TBL-006', 'row', 1, 6, NULL, '6,000m 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-006-01', 'TBL-006', 'column', 1, 1, NULL, '조사대상 유인틀 길이');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-006-02', 'TBL-006', 'column', 1, 2, NULL, '표본주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-007-01', 'TBL-007', 'row', 1, 1, NULL, '50주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-007-02', 'TBL-007', 'row', 1, 2, NULL, '50주 이상 100주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-007-03', 'TBL-007', 'row', 1, 3, NULL, '100주 이상 200주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-007-04', 'TBL-007', 'row', 1, 4, NULL, '200주 이상 300주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-007-05', 'TBL-007', 'row', 1, 5, NULL, '300주 이상 400주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-007-06', 'TBL-007', 'row', 1, 6, NULL, '400주 이상 500주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-007-07', 'TBL-007', 'row', 1, 7, NULL, '500주 이상 600주 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-007-08', 'TBL-007', 'row', 1, 8, NULL, '600주 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-007-01', 'TBL-007', 'column', 1, 1, NULL, '조사대상주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-007-02', 'TBL-007', 'column', 1, 2, NULL, '표본주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-008-01', 'TBL-008', 'row', 1, 1, NULL, '1,000포기 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-008-02', 'TBL-008', 'row', 1, 2, NULL, '1,000포기 이상 1,500포기 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-008-03', 'TBL-008', 'row', 1, 3, NULL, '1,500포기 이상 2,000포기 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-008-04', 'TBL-008', 'row', 1, 4, NULL, '2,000포기 이상 2,500포기 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-008-05', 'TBL-008', 'row', 1, 5, NULL, '2,500포기 이상 3,000포기 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-008-06', 'TBL-008', 'row', 1, 6, NULL, '3,000포기 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-008-01', 'TBL-008', 'column', 1, 1, NULL, '가입포기수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-008-02', 'TBL-008', 'column', 1, 2, NULL, '표본포기수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-009-01', 'TBL-009', 'row', 1, 1, NULL, '5,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-009-02', 'TBL-009', 'row', 1, 2, NULL, '5,000㎡ 이상 10,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-009-03', 'TBL-009', 'row', 1, 3, NULL, '10,000㎡ 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-009-01', 'TBL-009', 'column', 1, 1, NULL, '가입면적');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-009-02', 'TBL-009', 'column', 1, 2, NULL, '표본주수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-010-01', 'TBL-010', 'row', 1, 1, NULL, '2,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-010-02', 'TBL-010', 'row', 1, 2, NULL, '2,000㎡ 이상 3,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-010-03', 'TBL-010', 'row', 1, 3, NULL, '3,000㎡ 이상 4,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-010-04', 'TBL-010', 'row', 1, 4, NULL, '4,000㎡ 이상 5,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-010-05', 'TBL-010', 'row', 1, 5, NULL, '5,000㎡ 이상 6,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-010-06', 'TBL-010', 'row', 1, 6, NULL, '6,000㎡ 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-010-01', 'TBL-010', 'column', 1, 1, NULL, '조사대상면적');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-010-02', 'TBL-010', 'column', 1, 2, NULL, '표본구간');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-011-01', 'TBL-011', 'row', 1, 1, NULL, '1,500㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-011-02', 'TBL-011', 'row', 1, 2, NULL, '1,500㎡ 이상 3,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-011-03', 'TBL-011', 'row', 1, 3, NULL, '3,000㎡ 이상 4,500㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-011-04', 'TBL-011', 'row', 1, 4, NULL, '4,500㎡ 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-011-01', 'TBL-011', 'column', 1, 1, NULL, '조사대상면적');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-011-02', 'TBL-011', 'column', 1, 2, NULL, '표본구간');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-016-01', 'TBL-016', 'row', 1, 1, NULL, '2,500㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-016-02', 'TBL-016', 'row', 1, 2, NULL, '2,500㎡ 이상 5,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-016-03', 'TBL-016', 'row', 1, 3, NULL, '5,000㎡ 이상 7,500㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-016-04', 'TBL-016', 'row', 1, 4, NULL, '7,500㎡ 이상 10,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-016-05', 'TBL-016', 'row', 1, 5, NULL, '10,000㎡ 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-016-01', 'TBL-016', 'column', 1, 1, NULL, '조사대상면적');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-016-02', 'TBL-016', 'column', 1, 2, NULL, '표본구간');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-017-01', 'TBL-017', 'row', 1, 1, NULL, '300칸 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-017-02', 'TBL-017', 'row', 1, 2, NULL, '300칸 이상 500칸 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-017-03', 'TBL-017', 'row', 1, 3, NULL, '500칸 이상 700칸 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-017-04', 'TBL-017', 'row', 1, 4, NULL, '700칸 이상 900칸 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-017-05', 'TBL-017', 'row', 1, 5, NULL, '900칸 이상 1,200칸 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-017-06', 'TBL-017', 'row', 1, 6, NULL, '1,200칸 이상 1,500칸 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-017-07', 'TBL-017', 'row', 1, 7, NULL, '1,500칸 이상 1,800칸 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-017-08', 'TBL-017', 'row', 1, 8, NULL, '1,800칸 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-017-01', 'TBL-017', 'column', 1, 1, NULL, '피해칸수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-017-02', 'TBL-017', 'column', 1, 2, NULL, '표본칸수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-018-01', 'TBL-018', 'row', 1, 1, NULL, '3,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-018-02', 'TBL-018', 'row', 1, 2, NULL, '3,000㎡ 이상 7,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-018-03', 'TBL-018', 'row', 1, 3, NULL, '7,000㎡ 이상 15,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-018-04', 'TBL-018', 'row', 1, 4, NULL, '15,000㎡ 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-018-01', 'TBL-018', 'column', 1, 1, NULL, '피해면적');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-018-02', 'TBL-018', 'column', 1, 2, NULL, '표본구간(이랑) 수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-019-01', 'TBL-019', 'row', 1, 1, NULL, '3,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-019-02', 'TBL-019', 'row', 1, 2, NULL, '3,000㎡ 이상 7,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-019-03', 'TBL-019', 'row', 1, 3, NULL, '7,000㎡ 이상 15,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-019-04', 'TBL-019', 'row', 1, 4, NULL, '15,000㎡ 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-019-01', 'TBL-019', 'column', 1, 1, NULL, '조사대상면적');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-019-02', 'TBL-019', 'column', 1, 2, NULL, '표본구간(이랑) 수');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-020-01', 'TBL-020', 'row', 1, 1, NULL, '1,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-020-02', 'TBL-020', 'row', 1, 2, NULL, '1,000㎡ 이상 2,500㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-020-03', 'TBL-020', 'row', 1, 3, NULL, '2,500㎡ 이상 5,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-020-04', 'TBL-020', 'row', 1, 4, NULL, '5,000㎡ 이상 7,500㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-020-05', 'TBL-020', 'row', 1, 5, NULL, '7,500㎡ 이상 10,000㎡ 미만');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TROW-020-06', 'TBL-020', 'row', 1, 6, NULL, '10,000㎡ 이상');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-020-01', 'TBL-020', 'column', 1, 1, NULL, '조사대상면적');
INSERT INTO table_headers (id, table_id, axis, level, index_pos, parent_id, text) VALUES ('TCOL-020-02', 'TBL-020', 'column', 1, 2, NULL, '표본구간');

-- ③ table_cells (195 rows, nested_table FK 정합)
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-01-01', 'TBL-001', 'TROW-001-01', 'TCOL-001-01', '→ TBL-002 (사과/배/단감/떫은감/포도(농업수입안정 포함)/복숭아/자두/밤/호두/무화과/감귤(만감류))', 'nested_table', NULL, NULL, 'TBL-002');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-02-01', 'TBL-001', 'TROW-001-02', 'TCOL-001-01', '→ TBL-003 (유자)', 'nested_table', NULL, NULL, 'TBL-003');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-03-01', 'TBL-001', 'TROW-001-03', 'TCOL-001-01', '→ TBL-004 (참다래/블루베리)', 'nested_table', NULL, NULL, 'TBL-004');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-04-01', 'TBL-001', 'TROW-001-04', 'TCOL-001-01', '→ TBL-005 (매실/대추/살구)', 'nested_table', NULL, NULL, 'TBL-005');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-05-01', 'TBL-001', 'TROW-001-05', 'TCOL-001-01', '→ TBL-006 (오미자)', 'nested_table', NULL, NULL, 'TBL-006');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-06-01', 'TBL-001', 'TROW-001-06', 'TCOL-001-01', '→ TBL-007 (오디)', 'nested_table', NULL, NULL, 'TBL-007');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-07-01', 'TBL-001', 'TROW-001-07', 'TCOL-001-01', '→ TBL-008 (복분자)', 'nested_table', NULL, NULL, 'TBL-008');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-08-01', 'TBL-001', 'TROW-001-08', 'TCOL-001-01', '→ TBL-009 (감귤(온주밀감류))', 'nested_table', NULL, NULL, 'TBL-009');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-09-01', 'TBL-001', 'TROW-001-09', 'TCOL-001-01', '→ TBL-010 (벼/밀/보리/귀리)', 'nested_table', NULL, NULL, 'TBL-010');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-10-01', 'TBL-001', 'TROW-001-10', 'TCOL-001-01', '→ TBL-011 (고구마/양파/마늘/옥수수/양배추/단호박 (수입보장 포함))', 'nested_table', NULL, NULL, 'TBL-011');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-11-01', 'TBL-001', 'TROW-001-11', 'TCOL-001-01', '→ TBL-016 (감자/차/콩/팥/수박/당근/생강/고랭지무/가을무(일반)/고랭지배추/가을배추 (수입보장 포함))', 'nested_table', NULL, NULL, 'TBL-016');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-12-01', 'TBL-001', 'TROW-001-12', 'TCOL-001-01', '→ TBL-017 (인삼)', 'nested_table', NULL, NULL, 'TBL-017');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-13-01', 'TBL-001', 'TROW-001-13', 'TCOL-001-01', '→ TBL-018 (고추/메밀/브로콜리/배추(봄/고랭지/월동)/무/파/시금치/양상추)', 'nested_table', NULL, NULL, 'TBL-018');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-14-01', 'TBL-001', 'TROW-001-14', 'TCOL-001-01', '→ TBL-019 (두릅)', 'nested_table', NULL, NULL, 'TBL-019');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-001-15-01', 'TBL-001', 'TROW-001-15', 'TCOL-001-01', '→ TBL-020 (참깨/녹두)', 'nested_table', NULL, NULL, 'TBL-020');
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-01-01', 'TBL-002', 'TROW-002-01', 'TCOL-002-01', '50주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-01-02', 'TBL-002', 'TROW-002-01', 'TCOL-002-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-02-01', 'TBL-002', 'TROW-002-02', 'TCOL-002-01', '50주 이상 100주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-02-02', 'TBL-002', 'TROW-002-02', 'TCOL-002-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-03-01', 'TBL-002', 'TROW-002-03', 'TCOL-002-01', '100주 이상 150주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-03-02', 'TBL-002', 'TROW-002-03', 'TCOL-002-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-04-01', 'TBL-002', 'TROW-002-04', 'TCOL-002-01', '150주 이상 200주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-04-02', 'TBL-002', 'TROW-002-04', 'TCOL-002-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-05-01', 'TBL-002', 'TROW-002-05', 'TCOL-002-01', '200주 이상 300주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-05-02', 'TBL-002', 'TROW-002-05', 'TCOL-002-02', '9', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-06-01', 'TBL-002', 'TROW-002-06', 'TCOL-002-01', '300주 이상 400주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-06-02', 'TBL-002', 'TROW-002-06', 'TCOL-002-02', '10', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-07-01', 'TBL-002', 'TROW-002-07', 'TCOL-002-01', '400주 이상 500주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-07-02', 'TBL-002', 'TROW-002-07', 'TCOL-002-02', '11', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-08-01', 'TBL-002', 'TROW-002-08', 'TCOL-002-01', '500주 이상 600주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-08-02', 'TBL-002', 'TROW-002-08', 'TCOL-002-02', '12', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-09-01', 'TBL-002', 'TROW-002-09', 'TCOL-002-01', '600주 이상 700주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-09-02', 'TBL-002', 'TROW-002-09', 'TCOL-002-02', '13', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-10-01', 'TBL-002', 'TROW-002-10', 'TCOL-002-01', '700주 이상 800주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-10-02', 'TBL-002', 'TROW-002-10', 'TCOL-002-02', '14', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-11-01', 'TBL-002', 'TROW-002-11', 'TCOL-002-01', '800주 이상 900주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-11-02', 'TBL-002', 'TROW-002-11', 'TCOL-002-02', '15', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-12-01', 'TBL-002', 'TROW-002-12', 'TCOL-002-01', '900주 이상 1,000주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-12-02', 'TBL-002', 'TROW-002-12', 'TCOL-002-02', '16', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-13-01', 'TBL-002', 'TROW-002-13', 'TCOL-002-01', '1,000주 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-002-13-02', 'TBL-002', 'TROW-002-13', 'TCOL-002-02', '17', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-01-01', 'TBL-003', 'TROW-003-01', 'TCOL-003-01', '50주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-01-02', 'TBL-003', 'TROW-003-01', 'TCOL-003-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-02-01', 'TBL-003', 'TROW-003-02', 'TCOL-003-01', '50주 이상 100주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-02-02', 'TBL-003', 'TROW-003-02', 'TCOL-003-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-03-01', 'TBL-003', 'TROW-003-03', 'TCOL-003-01', '100주 이상 200주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-03-02', 'TBL-003', 'TROW-003-03', 'TCOL-003-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-04-01', 'TBL-003', 'TROW-003-04', 'TCOL-003-01', '200주 이상 500주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-04-02', 'TBL-003', 'TROW-003-04', 'TCOL-003-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-05-01', 'TBL-003', 'TROW-003-05', 'TCOL-003-01', '500주 이상 800주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-05-02', 'TBL-003', 'TROW-003-05', 'TCOL-003-02', '9', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-06-01', 'TBL-003', 'TROW-003-06', 'TCOL-003-01', '800주 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-003-06-02', 'TBL-003', 'TROW-003-06', 'TCOL-003-02', '10', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-01-01', 'TBL-004', 'TROW-004-01', 'TCOL-004-01', '50주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-01-02', 'TBL-004', 'TROW-004-01', 'TCOL-004-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-02-01', 'TBL-004', 'TROW-004-02', 'TCOL-004-01', '50주 이상 100주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-02-02', 'TBL-004', 'TROW-004-02', 'TCOL-004-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-03-01', 'TBL-004', 'TROW-004-03', 'TCOL-004-01', '100주 이상 200주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-03-02', 'TBL-004', 'TROW-004-03', 'TCOL-004-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-04-01', 'TBL-004', 'TROW-004-04', 'TCOL-004-01', '200주 이상 500주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-04-02', 'TBL-004', 'TROW-004-04', 'TCOL-004-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-05-01', 'TBL-004', 'TROW-004-05', 'TCOL-004-01', '500주 이상 800주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-05-02', 'TBL-004', 'TROW-004-05', 'TCOL-004-02', '9', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-06-01', 'TBL-004', 'TROW-004-06', 'TCOL-004-01', '800주 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-004-06-02', 'TBL-004', 'TROW-004-06', 'TCOL-004-02', '10', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-01-01', 'TBL-005', 'TROW-005-01', 'TCOL-005-01', '100주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-01-02', 'TBL-005', 'TROW-005-01', 'TCOL-005-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-02-01', 'TBL-005', 'TROW-005-02', 'TCOL-005-01', '100주 이상 300주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-02-02', 'TBL-005', 'TROW-005-02', 'TCOL-005-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-03-01', 'TBL-005', 'TROW-005-03', 'TCOL-005-01', '300주 이상 500주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-03-02', 'TBL-005', 'TROW-005-03', 'TCOL-005-02', '9', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-04-01', 'TBL-005', 'TROW-005-04', 'TCOL-005-01', '500주 이상 1,000주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-04-02', 'TBL-005', 'TROW-005-04', 'TCOL-005-02', '12', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-05-01', 'TBL-005', 'TROW-005-05', 'TCOL-005-01', '1,000주 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-005-05-02', 'TBL-005', 'TROW-005-05', 'TCOL-005-02', '16', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-01-01', 'TBL-006', 'TROW-006-01', 'TCOL-006-01', '500m 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-01-02', 'TBL-006', 'TROW-006-01', 'TCOL-006-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-02-01', 'TBL-006', 'TROW-006-02', 'TCOL-006-01', '500m 이상 1,000m 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-02-02', 'TBL-006', 'TROW-006-02', 'TCOL-006-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-03-01', 'TBL-006', 'TROW-006-03', 'TCOL-006-01', '1,000m 이상 2,000m 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-03-02', 'TBL-006', 'TROW-006-03', 'TCOL-006-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-04-01', 'TBL-006', 'TROW-006-04', 'TCOL-006-01', '2,000m 이상 4,000m 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-04-02', 'TBL-006', 'TROW-006-04', 'TCOL-006-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-05-01', 'TBL-006', 'TROW-006-05', 'TCOL-006-01', '4,000m 이상 6,000m 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-05-02', 'TBL-006', 'TROW-006-05', 'TCOL-006-02', '9', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-06-01', 'TBL-006', 'TROW-006-06', 'TCOL-006-01', '6,000m 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-006-06-02', 'TBL-006', 'TROW-006-06', 'TCOL-006-02', '10', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-01-01', 'TBL-007', 'TROW-007-01', 'TCOL-007-01', '50주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-01-02', 'TBL-007', 'TROW-007-01', 'TCOL-007-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-02-01', 'TBL-007', 'TROW-007-02', 'TCOL-007-01', '50주 이상 100주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-02-02', 'TBL-007', 'TROW-007-02', 'TCOL-007-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-03-01', 'TBL-007', 'TROW-007-03', 'TCOL-007-01', '100주 이상 200주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-03-02', 'TBL-007', 'TROW-007-03', 'TCOL-007-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-04-01', 'TBL-007', 'TROW-007-04', 'TCOL-007-01', '200주 이상 300주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-04-02', 'TBL-007', 'TROW-007-04', 'TCOL-007-02', '9', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-05-01', 'TBL-007', 'TROW-007-05', 'TCOL-007-01', '300주 이상 400주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-05-02', 'TBL-007', 'TROW-007-05', 'TCOL-007-02', '10', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-06-01', 'TBL-007', 'TROW-007-06', 'TCOL-007-01', '400주 이상 500주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-06-02', 'TBL-007', 'TROW-007-06', 'TCOL-007-02', '11', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-07-01', 'TBL-007', 'TROW-007-07', 'TCOL-007-01', '500주 이상 600주 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-07-02', 'TBL-007', 'TROW-007-07', 'TCOL-007-02', '12', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-08-01', 'TBL-007', 'TROW-007-08', 'TCOL-007-01', '600주 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-007-08-02', 'TBL-007', 'TROW-007-08', 'TCOL-007-02', '13', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-01-01', 'TBL-008', 'TROW-008-01', 'TCOL-008-01', '1,000포기 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-01-02', 'TBL-008', 'TROW-008-01', 'TCOL-008-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-02-01', 'TBL-008', 'TROW-008-02', 'TCOL-008-01', '1,000포기 이상 1,500포기 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-02-02', 'TBL-008', 'TROW-008-02', 'TCOL-008-02', '9', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-03-01', 'TBL-008', 'TROW-008-03', 'TCOL-008-01', '1,500포기 이상 2,000포기 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-03-02', 'TBL-008', 'TROW-008-03', 'TCOL-008-02', '10', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-04-01', 'TBL-008', 'TROW-008-04', 'TCOL-008-01', '2,000포기 이상 2,500포기 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-04-02', 'TBL-008', 'TROW-008-04', 'TCOL-008-02', '11', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-05-01', 'TBL-008', 'TROW-008-05', 'TCOL-008-01', '2,500포기 이상 3,000포기 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-05-02', 'TBL-008', 'TROW-008-05', 'TCOL-008-02', '12', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-06-01', 'TBL-008', 'TROW-008-06', 'TCOL-008-01', '3,000포기 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-008-06-02', 'TBL-008', 'TROW-008-06', 'TCOL-008-02', '13', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-009-01-01', 'TBL-009', 'TROW-009-01', 'TCOL-009-01', '5,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-009-01-02', 'TBL-009', 'TROW-009-01', 'TCOL-009-02', '4', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-009-02-01', 'TBL-009', 'TROW-009-02', 'TCOL-009-01', '5,000㎡ 이상 10,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-009-02-02', 'TBL-009', 'TROW-009-02', 'TCOL-009-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-009-03-01', 'TBL-009', 'TROW-009-03', 'TCOL-009-01', '10,000㎡ 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-009-03-02', 'TBL-009', 'TROW-009-03', 'TCOL-009-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-01-01', 'TBL-010', 'TROW-010-01', 'TCOL-010-01', '2,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-01-02', 'TBL-010', 'TROW-010-01', 'TCOL-010-02', '3', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-02-01', 'TBL-010', 'TROW-010-02', 'TCOL-010-01', '2,000㎡ 이상 3,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-02-02', 'TBL-010', 'TROW-010-02', 'TCOL-010-02', '4', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-03-01', 'TBL-010', 'TROW-010-03', 'TCOL-010-01', '3,000㎡ 이상 4,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-03-02', 'TBL-010', 'TROW-010-03', 'TCOL-010-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-04-01', 'TBL-010', 'TROW-010-04', 'TCOL-010-01', '4,000㎡ 이상 5,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-04-02', 'TBL-010', 'TROW-010-04', 'TCOL-010-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-05-01', 'TBL-010', 'TROW-010-05', 'TCOL-010-01', '5,000㎡ 이상 6,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-05-02', 'TBL-010', 'TROW-010-05', 'TCOL-010-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-06-01', 'TBL-010', 'TROW-010-06', 'TCOL-010-01', '6,000㎡ 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-010-06-02', 'TBL-010', 'TROW-010-06', 'TCOL-010-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-011-01-01', 'TBL-011', 'TROW-011-01', 'TCOL-011-01', '1,500㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-011-01-02', 'TBL-011', 'TROW-011-01', 'TCOL-011-02', '4', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-011-02-01', 'TBL-011', 'TROW-011-02', 'TCOL-011-01', '1,500㎡ 이상 3,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-011-02-02', 'TBL-011', 'TROW-011-02', 'TCOL-011-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-011-03-01', 'TBL-011', 'TROW-011-03', 'TCOL-011-01', '3,000㎡ 이상 4,500㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-011-03-02', 'TBL-011', 'TROW-011-03', 'TCOL-011-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-011-04-01', 'TBL-011', 'TROW-011-04', 'TCOL-011-01', '4,500㎡ 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-011-04-02', 'TBL-011', 'TROW-011-04', 'TCOL-011-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-01-01', 'TBL-016', 'TROW-016-01', 'TCOL-016-01', '2,500㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-01-02', 'TBL-016', 'TROW-016-01', 'TCOL-016-02', '4', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-02-01', 'TBL-016', 'TROW-016-02', 'TCOL-016-01', '2,500㎡ 이상 5,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-02-02', 'TBL-016', 'TROW-016-02', 'TCOL-016-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-03-01', 'TBL-016', 'TROW-016-03', 'TCOL-016-01', '5,000㎡ 이상 7,500㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-03-02', 'TBL-016', 'TROW-016-03', 'TCOL-016-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-04-01', 'TBL-016', 'TROW-016-04', 'TCOL-016-01', '7,500㎡ 이상 10,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-04-02', 'TBL-016', 'TROW-016-04', 'TCOL-016-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-05-01', 'TBL-016', 'TROW-016-05', 'TCOL-016-01', '10,000㎡ 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-016-05-02', 'TBL-016', 'TROW-016-05', 'TCOL-016-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-01-01', 'TBL-017', 'TROW-017-01', 'TCOL-017-01', '300칸 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-01-02', 'TBL-017', 'TROW-017-01', 'TCOL-017-02', '3칸', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-02-01', 'TBL-017', 'TROW-017-02', 'TCOL-017-01', '300칸 이상 500칸 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-02-02', 'TBL-017', 'TROW-017-02', 'TCOL-017-02', '4칸', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-03-01', 'TBL-017', 'TROW-017-03', 'TCOL-017-01', '500칸 이상 700칸 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-03-02', 'TBL-017', 'TROW-017-03', 'TCOL-017-02', '5칸', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-04-01', 'TBL-017', 'TROW-017-04', 'TCOL-017-01', '700칸 이상 900칸 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-04-02', 'TBL-017', 'TROW-017-04', 'TCOL-017-02', '6칸', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-05-01', 'TBL-017', 'TROW-017-05', 'TCOL-017-01', '900칸 이상 1,200칸 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-05-02', 'TBL-017', 'TROW-017-05', 'TCOL-017-02', '7칸', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-06-01', 'TBL-017', 'TROW-017-06', 'TCOL-017-01', '1,200칸 이상 1,500칸 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-06-02', 'TBL-017', 'TROW-017-06', 'TCOL-017-02', '8칸', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-07-01', 'TBL-017', 'TROW-017-07', 'TCOL-017-01', '1,500칸 이상 1,800칸 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-07-02', 'TBL-017', 'TROW-017-07', 'TCOL-017-02', '9칸', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-08-01', 'TBL-017', 'TROW-017-08', 'TCOL-017-01', '1,800칸 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-017-08-02', 'TBL-017', 'TROW-017-08', 'TCOL-017-02', '10칸', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-018-01-01', 'TBL-018', 'TROW-018-01', 'TCOL-018-01', '3,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-018-01-02', 'TBL-018', 'TROW-018-01', 'TCOL-018-02', '4', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-018-02-01', 'TBL-018', 'TROW-018-02', 'TCOL-018-01', '3,000㎡ 이상 7,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-018-02-02', 'TBL-018', 'TROW-018-02', 'TCOL-018-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-018-03-01', 'TBL-018', 'TROW-018-03', 'TCOL-018-01', '7,000㎡ 이상 15,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-018-03-02', 'TBL-018', 'TROW-018-03', 'TCOL-018-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-018-04-01', 'TBL-018', 'TROW-018-04', 'TCOL-018-01', '15,000㎡ 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-018-04-02', 'TBL-018', 'TROW-018-04', 'TCOL-018-02', '10', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-019-01-01', 'TBL-019', 'TROW-019-01', 'TCOL-019-01', '3,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-019-01-02', 'TBL-019', 'TROW-019-01', 'TCOL-019-02', '4', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-019-02-01', 'TBL-019', 'TROW-019-02', 'TCOL-019-01', '3,000㎡ 이상 7,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-019-02-02', 'TBL-019', 'TROW-019-02', 'TCOL-019-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-019-03-01', 'TBL-019', 'TROW-019-03', 'TCOL-019-01', '7,000㎡ 이상 15,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-019-03-02', 'TBL-019', 'TROW-019-03', 'TCOL-019-02', '8', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-019-04-01', 'TBL-019', 'TROW-019-04', 'TCOL-019-01', '15,000㎡ 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-019-04-02', 'TBL-019', 'TROW-019-04', 'TCOL-019-02', '10', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-01-01', 'TBL-020', 'TROW-020-01', 'TCOL-020-01', '1,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-01-02', 'TBL-020', 'TROW-020-01', 'TCOL-020-02', '3', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-02-01', 'TBL-020', 'TROW-020-02', 'TCOL-020-01', '1,000㎡ 이상 2,500㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-02-02', 'TBL-020', 'TROW-020-02', 'TCOL-020-02', '4', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-03-01', 'TBL-020', 'TROW-020-03', 'TCOL-020-01', '2,500㎡ 이상 5,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-03-02', 'TBL-020', 'TROW-020-03', 'TCOL-020-02', '5', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-04-01', 'TBL-020', 'TROW-020-04', 'TCOL-020-01', '5,000㎡ 이상 7,500㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-04-02', 'TBL-020', 'TROW-020-04', 'TCOL-020-02', '6', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-05-01', 'TBL-020', 'TROW-020-05', 'TCOL-020-01', '7,500㎡ 이상 10,000㎡ 미만', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-05-02', 'TBL-020', 'TROW-020-05', 'TCOL-020-02', '7', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-06-01', 'TBL-020', 'TROW-020-06', 'TCOL-020-01', '10,000㎡ 이상', 'text', NULL, NULL, NULL);
INSERT INTO table_cells (id, table_id, row_id, col_id, value_text, value_type, formula_id, merged_with_id, nested_table_id) VALUES ('TCELL-020-06-02', 'TBL-020', 'TROW-020-06', 'TCOL-020-02', '8', 'text', NULL, NULL, NULL);

-- ④ table_node_links (16 rows, extracted_from)
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-001', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-002', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-003', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-004', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-005', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-006', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-007', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-008', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-009', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-010', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-011', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-016', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-017', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-018', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-019', 'LAW-138', 'extracted_from');
INSERT INTO table_node_links (table_id, related_node_id, relation_type) VALUES ('TBL-020', 'LAW-138', 'extracted_from');
