-- BATCH 적재 SQL — BATCH-6 (2026)
-- 출처: batch-6-knowledge-graph.json
-- 노드: 70 / 엣지: 100 / 산식: 21 / 상수: 21
-- 적용: wrangler d1 execute <db-name> --file=<this-file> --remote
-- 사전 의무: migration 0019 production 적용 완료
-- 멱등성: INSERT OR IGNORE — 재실행 시 충돌 없음
--
-- AI 생성 데이터 (CLAUDE.md Hard Limit) — status='draft' 만 INSERT
-- 진산님 검수 후 status_transitions UPDATE 로 review/approved 전이
--
-- 주의: D1 wrangler execute --file 은 전체 파일을 자동 트랜잭션으로 감싼다.
-- 명시 BEGIN TRANSACTION/COMMIT 은 D1 거부 (Durable Object 충돌). 의도적으로 생략.

-- 1. knowledge_nodes (70 rows)
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-33', 'INSURANCE', '가축재해보험 (총칙)', '가축에 발생하는 재해 손해를 보장하는 손해보험. 상법상 손해보험에 해당. 부문 = 소(牛) / 돼지 / 가금 / 말·종모우·기타 가축 / 축사 5개. 보험가액 산정 후 손해액 평가하여 보험금 지급. 이득금지원칙 적용. 보험기간동안 보험증권 기재 지역 내 보험목적 보관 의무.', '가축재해보험', NULL, NULL, 'p.648', 648, 655, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-34', 'INSURANCE', '가축재해보험 소(牛) 부문', '한우(암/수, 거세우 포함) + 젖소(암컷) + 육우 대상. 보험가액 산정 = 월령(만 개월) 기준 구분. 한우/젖소/육우 별 산정 방식 상이. 폐사 = 보험목적 전부손해 → 보험가액 = 손해액. 긴급도축 = 보험가액 - 이용물처분액 = 손해액.', '가축재해보험', NULL, NULL, 'p.654', 654, 661, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-35', 'INSURANCE', '가축재해보험 돼지 부문', '종모돈 / 종빈돈 / 비육돈·육성돈·후보돈 / 자돈(포유돈·이유돈) / 기타 돼지로 분류. 종모돈 = 종빈돈 가액 × 1.20 (20% 가산). 종빈돈 = 비육돈 지육단가 범위에 따른 표 가격 (350,000~700,000원). 비육돈 = 자돈가격(30kg) + (적용체중-30) × (110kg수취가격-자돈가격) / 80. 자돈/기타 = 협정가액.', '가축재해보험', NULL, NULL, 'p.659', 659, 666, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-36', 'INSURANCE', '가축재해보험 가금 부문', '닭(종계/산란계/육계/토종닭/부화장 종란·병아리) + 오리 + 꿩·메추리·칠면조·거위·타조·관상조 등. 종계 = 주령별 단계 적용 (병아리/성계/노계). 산란계 = 단계별 보간 + 20~70주 = (550-사고일령) × 70% × (계란평균가격-77원). 육계/토종닭/오리 = 주령별 평균가격 × 발육표준표 중량. 일령 한도 (육계 40일=2.3kg / 토종닭 84일=2.8kg / 오리 45일=3.5kg).', '가축재해보험', NULL, NULL, 'p.662', 662, 669, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-37', 'INSURANCE', '가축재해보험 말·종모우·기타 가축 부문', '협정보험가액 적용 (계약체결 시 계약자와 협의 평가). 협정보험가액이 사고 발생 시 가액을 현저히 초과하면 사고 발생 시 가액을 보험가액으로 한다. 손해액 = 보험가액 - 이용물 처분액 - 보상금.', '가축재해보험', NULL, NULL, 'p.665', 665, 672, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-38', 'INSURANCE', '가축재해보험 축사 부문', '부보비율(80%) 조건부 실손 보상. 보험가입금액이 보험가액의 80% 이상 = 전부보험으로 보고 비례보상 미적용. 80% 미만 = 손해액 × (보험가입금액 / 보험가액의 80%) = 비례보상. 자기부담금 = 풍재·수재·설해·지진 시 (자기부담비율을 곱한 금액 또는 50만원 중 큰 금액). 화재 시 = 자기부담비율을 곱한 금액. 경년감가율 = 손해보험협회 기준 준용. 잔가율 = 보온덮개·쇠파이프 조인 축사구조물 최대 50%, 그 외 70% (6개월 내 미수리 시 30% 한도).', '가축재해보험', NULL, NULL, 'p.666', 666, 673, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-39', 'INSURANCE', '소(牛) 도체결함보장 특약', '사고소의 도체등급과 같은 등급의 전국평균 경락가격(등외등급 및 결함 제외 정상도체 가격)과 사고소 도체의 경락가격으로 손해액 산정. 자기부담금 = 보통약관 1) 또는 2) 계산금액의 20%.', '가축재해보험', NULL, NULL, 'p.669', 669, 676, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-40', 'INSURANCE', '돼지 질병위험보장 특약 (종빈돈)', '전염성위장염(TGE) + 돼지유행성설사병(PED) + 로타바이러스감염증을 직접 원인으로 폐사하거나 수의학적으로 구할 수 없는 상태의 손해 보상. 보험가액 = 모돈두수 × 2.5 × 자돈가격. 진단확정 = 해부병리 또는 임상병리 전문 수의사 + 형광항체법/PCR. 자기부담금 = 자기부담비율 × 손해액과 200만원 중 큰 금액.', '가축재해보험', NULL, NULL, 'p.670', 670, 677, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-41', 'INSURANCE', '돼지 축산휴지위험보장 특약', '보상위험으로 축산업 전부/일부 중단 시 사업이익 손해 보상. 사업이익 = 1두당 평균가격 - 경영비. 이익률 = (두당비육돈평균가격 - 경영비) / 두당비육돈평균가격 (16.5% 미만이면 16.5% 적용). 보험가액 = 종빈돈마리수 × 10 × 1두당 비육돈(100kg 기준) 평균가격 × 이익률. 후보돈/임신·분만·포유 종빈돈 제외. 자기부담금 미적용.', '가축재해보험', NULL, NULL, 'p.672', 672, 679, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-42', 'INSURANCE', '전기적장치 위험보장 특약', '돼지/가금 부문 적용 가능. 전기적 장치 (전기 시설·기기) 의 위험으로 인한 손해 보상.', '가축재해보험', NULL, NULL, 'p.675', 675, 682, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INS-43', 'INSURANCE', '폭염재해보장 특약', '돼지/가금 부문 적용 가능. 폭염으로 인한 가축 폐사 손해 보상.', '가축재해보험', NULL, NULL, 'p.675', 675, 682, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-114', 'CONCEPT', '계약 후 알릴 의무 (가축재해보험)', '계약 체결 이후 위험 변경 사항 등을 보험자에게 통지할 의무. 모든 부문 축종 공통 의무 + 부문별 특정 의무 (소 부문: 개체 표시 변경 등). 위반 시 보험자는 그 사실을 안 날부터 1월 내에 계약을 해지할 수 있다.', '가축재해보험', NULL, NULL, 'p.649', 649, 656, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-115', 'CONCEPT', '보험사고 발생 통지의무', '보험사고 발생을 안 때 지체없이 보험자에게 통지를 발송할 의무 (상법 제657조 제1항). 사고조사 신속 진행과 손해 확대 방지 목적. 위반 시 확대된 손해 또는 회복 가능한 손해는 재해보험사업자가 보상하지 않음.', '가축재해보험', NULL, NULL, 'p.651', 651, 658, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-116', 'CONCEPT', '손해방지의무 (가축재해보험)', '보험사고 발생 시 보험계약자/피보험자가 손해 방지·경감을 위해 노력해야 하는 법정·약관 의무 (상법 제680조). 고의 또는 중대한 과실로 게을리한 때 = 방지/경감할 수 있었을 손해를 손해액에서 공제. 손해방지비용 = 보험가입금액의 보험가액 대비 비율 따라 계산 (부보비율 80% 조건부 실손).', '가축재해보험', NULL, NULL, 'p.651', 651, 658, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-117', 'CONCEPT', '보험목적관리의무 (가축재해보험)', '보험목적이 사람의 지속적 관리가 필요한 생명체라는 특수성으로 부여된 의무. 사육·관리·보호 / 적합한 사료 급여·급수·운동·휴식·수면 / 예방접종·정기검진·기생충 구제 / 신속 치료. 게을리한 경우 = 방지/경감 가능했던 손해 공제 또는 보험자 직접 조치 가능.', '가축재해보험', NULL, NULL, 'p.651', 651, 658, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-118', 'CONCEPT', '이용물 처분액 (가축재해보험)', '긴급도축 등의 결과로 보험목적인 가축의 도축으로 얻어지는 고기·가죽 등 수익. 도축장발행 정산자료 = 지육금액 × 75%. 정산자료 X = 중량 × 지육가격 × 75%. 보험가액에서 공제하여 손해액 산정. 정산서 X 시 축산물이력제 조회 (도체중량·등급).', '가축재해보험', NULL, NULL, 'p.654', 654, 661, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-119', 'CONCEPT', '월령 산정 방식 (가축재해보험)', '월령은 폐사는 폐사 시점, 긴급도축은 긴급도축 시점의 월령을 만(滿)으로 계산. 월 미만 일수는 무시. 다만 사고 발생일까지가 1개월 이하인 경우 1개월로 한다.', '가축재해보험', NULL, NULL, 'p.654', 654, 661, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-120', 'CONCEPT', '산지가격 적용범위표 (한우/육우/젖소 수컷)', '한우 = 수컷 350kg 해당 전국 산지평균가격 + 성별 생후 7개월 이상 600kg 해당 전국 산지평균 가격 중 kg당 가격이 높은 금액. 육우(젖소 수컷) = 생후 3개월 이상 500kg 해당 전국 산지평균 가격. 한우 수컷 25개월 초과 = 655kg 인정 / 한우 암컷 40개월 초과 = 470kg 인정 / 육우 25개월 초과 = 600kg 인정.', '가축재해보험', NULL, NULL, 'p.656', 656, 663, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-121', 'CONCEPT', '젖소 9단계 보험가액 산정', '젖소 암컷의 보험가액은 월령 기준 9단계로 구분: 1~7개월(분유떼기), 8~12(보간), 13~18(수정단계), 19~23(보간), 24~31(초산우), 32~39(보간), 40~55(다산우), 56~66(보간), 67+(노산우). 보간 = 양 끝 단계 가격 사이 선형 보간.', '가축재해보험', NULL, NULL, 'p.656', 656, 663, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-122', 'CONCEPT', '발육표준표 (가금)', '<그림 3-1>. 가금 보험가액 산정용 일령별 표준중량표. 보험가액(중량×kg당 시세)이 병아리 시세보다 낮은 경우 병아리 시세로 보상. 일령 한도: 육계 40일 초과 = 2.3kg / 토종닭 84일 초과 = 2.8kg / 오리 45일 초과 = 3.5kg / 삼계 = 육계 중량 70%.', '가축재해보험', NULL, NULL, 'p.665', 665, 672, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-123', 'CONCEPT', '부보비율 80% 조건부 실손 보상 (축사부문)', '축사부문 지급보험금 계산방식. 보험가입금액 ≥ 보험가액 × 80% = 전부보험으로 보고 비례보상 X (보험가입금액 한도로 손해액 전액 / 보험가입금액 > 보험가액이면 보험가액 한도). 보험가입금액 < 보험가액 × 80% = 손해액 × (보험가입금액 / (보험가액 × 80%)). 손해방지비용도 동일 부보비율 적용.', '가축재해보험', NULL, NULL, 'p.666', 666, 673, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-124', 'CONCEPT', '이득금지원칙', '손해보험을 지배하는 기본 원칙. 보험으로 이득을 보아서는 안 된다. 피보험자가 보험사고 발생 결과 사고 발생 직전 경제 상태보다 더 나은 상태에 놓이면 고의 보험사고 유발 등 손해보험제도 존립을 위협. 손해보험 본질·보험단체 형평 유지 + 도덕적 위험 강력 억제 목적.', '가축재해보험', NULL, NULL, 'p.676', 676, 683, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-125', 'CONCEPT', '전부보험·초과보험·중복보험·일부보험', '보험가액 = 보험가입금액 → 전부보험. 보험가입금액 > 보험가액 → 초과보험 (보험가액 한도 보상). 동일 사고 다른 보험계약 합계 > 보험가액 → 중복보험 (별표8 비례분담 또는 독립책임액분담). 보험가입금액 < 보험가액 → 일부보험 (보험가입금액 / 보험가액 비율로 비례보상).', '가축재해보험', NULL, NULL, 'p.676', 676, 683, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-126', 'CONCEPT', '잔존보험가입금액', '일부손해 보험금 지급 후 손해발생일 이후 보험기간에 대한 보험가입금액. 잔존가입금액 = 보험가입금액 - 기지급 보험금. 가축재해보험은 돼지/가금/기타 가축/축사 부문에서 적용. 보험목적이 둘 이상이면 각각 적용.', '가축재해보험', NULL, NULL, 'p.679', 679, 686, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-127', 'CONCEPT', '비용손해 5종 지급한도', '잔존물처리비용 + 손해방지비용 + 대위권 보전비용 + 잔존물 보전비용 + 기타 협력비용. 잔존물처리비용 = 손해액의 10% 한도, 보험가입금액 한도. 손해방지비용/대위권 보전비용/잔존물 보전비용 = 보험가입금액 초과해도 지급 (자기부담금 미공제). 기타 협력비용 = 보험가입금액 초과해도 전액 지급.', '가축재해보험', NULL, NULL, 'p.679', 679, 686, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-128', 'CONCEPT', '보험사기 (가축재해보험)', '보험계약자가 보험제도 원리상 취할 수 없는 보험혜택을 부당하게 얻거나 보험제도를 역이용하여 고액 보험금을 수취할 목적으로 고의·악의적으로 행동하는 일체의 불법행위. 형법상 사기죄 형성. 사기행위에 권유자 교사 또는 계약자/피보험자 자신의 사기행위 = 고지의무 위반과 달리 보장개시일로부터 5년 이내 계약 취소 가능.', '가축재해보험', NULL, NULL, 'p.682', 682, 689, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('CONCEPT-129', 'CONCEPT', '이익률 조정 (축산휴지위험보장)', '영업에 있어 특수 사정 영향이 있는 때 또는 영업추세가 현저히 변화한 때 = 손해사정에 있어 이익률에 공정한 조정 적용. 이익률이 16.5% 미만 = 16.5% 로 적용 (하한).', '가축재해보험', NULL, NULL, 'p.674', 674, 681, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-043', 'TERM', '한우 (Korean Native Cattle)', '한국 재래종 소. 가축재해보험 소(牛) 부문 주요 보험목적. 암컷·수컷(거세우 포함) 모두 보장. 보험가액 산정은 월령 기준 6개월 이하 / 7개월 이상으로 구분.', '가축재해보험', NULL, NULL, 'p.655', 655, 662, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-044', 'TERM', '송아지', '어린 소 (월령 1~6개월 기준). 한우 1~6개월령 보험가액 = 송아지 가격(농협축산정보센터 등재 전전월 전국산지평균). 2개월 미만(질병사고는 3개월 미만) = 50% 적용.', '가축재해보험', NULL, NULL, 'p.655', 655, 662, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-045', 'TERM', '초산우 / 다산우 / 노산우', '젖소(암컷) 산차 단계. 초산우 = 첫 출산. 다산우 = 다회 출산 단계 (최대 산유량). 노산우 = 산차가 많아 산유량이 감소한 노령 젖소. 보험가액 보간 산정의 기준 가격.', '가축재해보험', NULL, NULL, 'p.657', 657, 664, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-046', 'TERM', '거세우', '거세된 수소. 한우 보험가액 산정에서 수컷 범주에 포함. 산지가격 적용범위표의 수컷 가격 적용.', '가축재해보험', NULL, NULL, 'p.655', 655, 662, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 6, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-047', 'TERM', '젖소 / 분유떼기 / 수정단계', '젖소(암컷) 월령 단계. 분유떼기 = 분유 급여를 마친 단계 (1~7개월). 수정단계 = 인공수정 가능 시기 (13~18개월). 8~12 / 19~23 단계는 양 끝 가격 사이 선형 보간.', '가축재해보험', NULL, NULL, 'p.656', 656, 663, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-048', 'TERM', '육우', '육용으로 사육되는 소 (분유떼기 젖소 수컷 등). 보험가액 산정 = 3개월 미만 / 3개월 이상으로 구분. 25개월 초과 = 600kg 인정. 전국산지평균가격이 없는 경우 = 전국도매시장 지육평균 × 지육율 58%.', '가축재해보험', NULL, NULL, 'p.657', 657, 664, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-049', 'TERM', '도체 / 지육 / 도체중', '도체 = 도축된 가축의 머리·내장·족·가죽 등 부분 제외한 몸체. 지육 = 도체와 동의어. 도체중 = 지육중량 = 살아있는 생체에서 두부·내장·족·가죽 등 제외한 무게. 생체중 = 살아있는 생물의 무게. 지육율(도체율) = 도체중 / 생체중.', '가축재해보험', NULL, NULL, 'p.658', 658, 665, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-050', 'TERM', '종모돈 / 종빈돈', '종모돈 = 번식용 수퇘지. 종빈돈 = 번식용 암퇘지. 종모돈 보험가액 = 종빈돈 가액의 1.20배 (20% 가산). 종빈돈 보험가액 = 비육돈 지육단가 범위에 따른 표 가격 (표 참조 1,949원 이하 350,000원 ~ 5,350원 이상 700,000원).', '가축재해보험', NULL, NULL, 'p.659', 659, 666, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-051', 'TERM', '비육돈 / 육성돈 / 후보돈', '비육돈 = 출하용 살찐 돼지. 육성돈 = 31~110kg 적용 단위구간 (10kg 단위 중간 생체중량). 후보돈 = 종돈 후보. 적용체중 = 35/45/55/65/75/85/95/105 (단위구간별). 110kg 이상은 110kg으로 한다. 보험가액 산식 = 자돈가격 + (적용체중-30) × (110kg수취가격 - 자돈가격) / 80.', '가축재해보험', NULL, NULL, 'p.660', 660, 667, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-052', 'TERM', '자돈 / 포유돈 / 이유돈 / 모돈', '자돈 = 새끼돼지. 포유돈 = 젖먹이 돼지. 이유돈 = 젖을 뗀 돼지. 모돈 = 어미돼지 (= 종빈돈 동의어 또는 광의). 자돈 보험가액 = 협정가액. 돼지 질병위험보장 특약 보험가액 = 모돈두수 × 2.5 × 자돈가격.', '가축재해보험', NULL, NULL, 'p.661', 661, 668, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-053', 'TERM', '종계 / 산란계 / 육계 / 토종닭', '종계 = 번식용 닭 (병아리/성계/노계 단계). 산란계 = 알 생산용 닭 (병아리/중추/산란계/산란노계 단계). 육계 = 고기용 닭 (1주 미만 병아리 / 1주 이상 평균가격×중량). 토종닭 = 한국 재래종 닭 (산정 방식은 육계와 동일하나 사육계약서상 단가 한도 적용).', '가축재해보험', NULL, NULL, 'p.662', 662, 669, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-054', 'TERM', '산란실용계 / 산란중추', '산란실용계 = 산란용 실용계(상업적 산란 닭). 산란실용계 병아리 = 갓 부화한 산란용 병아리. 산란중추 = 중간 단계 산란용 닭 (10~15주). 산란계 보험가액 산정 시 단계별 가격 보간 (8주 = 분유떼기+(수정단계-분유떼기)/9 × (사고주령-1) 등 패턴).', '가축재해보험', NULL, NULL, 'p.663', 663, 670, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 7, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-055', 'TERM', '발육표준표 / 일령 / 주령', '일령 = 일 단위 사육 기간. 주령 = 주 단위 사육 기간. 발육표준표 = 가축재해보험 약관 부속표 (가금 일령별 표준 중량). 보험가액 = 중량 × kg당 시세 (단, 병아리 시세보다 낮으면 병아리 시세로). 한도: 육계 40일=2.3kg, 토종닭 84일=2.8kg, 오리 45일=3.5kg, 삼계 = 육계 70%.', '가축재해보험', NULL, NULL, 'p.665', 665, 672, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-056', 'TERM', '협정보험가액', '계약체결 시 계약자와 재해보험사업자가 협의하여 평가한 보험가액. 자돈/기타 돼지/말·종모우·기타 가축/부화장 종란 등에 적용. 협정보험가액이 사고 발생 시 가액을 현저하게 초과하면 사고 발생 시 가액을 보험가액으로 한다.', '가축재해보험', NULL, NULL, 'p.665', 665, 672, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 8, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('TERM-057', 'TERM', '축산휴지 / 축산휴지손해 / 사업이익', '축산휴지 = 보험의 목적 손해로 불가피하게 발생한 전부 또는 일부의 축산업 중단. 축산휴지손해 = 보상위험으로 축산업 중단 결과 발생한 사업이익과 손해 미발생 시 예상 사업이익의 차감금액. 사업이익 = 1두당 평균가격 - 경영비. 1두당 평균가격 = 비육돈 생체중량 100kg 가격. 경영비 = 통계청 발표 최근 비육돈 평균경영비.', '가축재해보험', NULL, NULL, 'p.672', 672, 679, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-016', 'LAW', '상법 제657조 제1항 (보험사고 통지의무)', '보험계약자 또는 피보험자는 보험사고의 발생을 안 때에는 지체없이 보험자에게 그 통지를 발송해야 한다. 가축재해보험에서 인용 (book p.651).', NULL, NULL, NULL, 'p.651', 651, 658, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-017', 'LAW', '상법 제682조 (제3자에 대한 보험대위)', '① 손해가 제3자의 행위로 인하여 발생한 경우에 보험금을 지급한 보험자는 그 지급한 금액의 한도에서 그 제3자에 대한 보험계약자 또는 피보험자의 권리를 취득한다. 다만, 보험자가 보상할 보험금의 일부를 지급한 경우에는 피보험자의 권리를 침해하지 아니하는 범위에서 그 권리를 행사할 수 있다. ② 보험계약자나 피보험자의 제1항에 따른 권리가 그와 생계를 같이 하는 가족에 대한 것인 경우 (이하 단서). 가축재해보험 중복보험 처리 시 인용 (book p.685).', NULL, NULL, NULL, 'p.685', 678, 685, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('LAW-018', 'LAW', '상법 제680조 (손해방지의무)', '보험계약자와 피보험자는 손해의 방지와 경감을 위하여 노력하여야 한다. 그러나 이를 위하여 필요 또는 유익하였던 비용과 보상액이 보험금액을 초과한 경우라도 보험자가 이를 부담한다. 가축재해보험에서 인용 (book p.651).', NULL, NULL, NULL, 'p.651', 651, 658, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-081', 'INVESTIGATION', '가축재해보험 보험금 심사 절차', '보험사고 접수 → 피해 사실 확인 → 보험가액·손해액 평가 → 손해평가 → 지급보험금 결정. 유의사항: 계약체결의 정당성 확인 (피보험자 동의 여부), 보험계약 인수 정당성, 손해사정 정당성 확인, 보험금 지급 정당성 확인.', '가축재해보험', NULL, NULL, 'p.680', 680, 687, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-082', 'INVESTIGATION', '도축장 정산자료 / 축산물이력제 조회', '이용물 처분액 산정 시 자료 확인 절차. 도축장발행 정산자료 = 지육금액 × 75% 적용. 정산자료 X 시 = 축산물이력제 조회 (이력번호 → 도체중·육질등급 → 도체중량×지육가격×75%). 지육가격 = 축산물품질평가원 고시 사고일 기준 사고소 등급 전국평균가격.', '가축재해보험', NULL, NULL, 'p.654', 654, 661, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-083', 'INVESTIGATION', '월령 산정 + 발육표준표 적용', '월령은 폐사·긴급도축 시점의 만(滿) 개월 (월 미만 일수 무시). 1개월 이하면 1개월. 한우 25개월 초과 수컷 = 655kg / 한우 40개월 초과 암컷 = 470kg / 육우 25개월 초과 = 600kg 인정. 가금 = 발육표준표 일령별 중량 적용 (육계 40일/토종닭 84일/오리 45일 한도).', '가축재해보험', NULL, NULL, 'p.656', 656, 663, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('INV-084', 'INVESTIGATION', '축산휴지손해 이익률 산정', '두당비육돈평균가격 = 직전 5영업일 평균돈육대표가격 × 110kg × 76.8%. 경영비 = 통계청 발표 최근 비육돈 평균경영비. 이익률 = (두당평균가격 - 경영비) / 두당평균가격. 16.5% 미만이면 16.5% 적용 (하한). 영업 특수사정·영업추세 변화 시 공정한 조정.', '가축재해보험', NULL, NULL, 'p.673', 673, 680, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-131', 'FORMULA', '한우 1~6개월령 보험가액', '산식: calf_price * (0.5 if month_age < threshold_month else 1.0)', '가축재해보험', NULL, NULL, 'p.655', 655, 662, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-132', 'FORMULA', '한우 7개월+ 보험가액 (체중 × kg당 금액)', '산식: weight_kg * price_per_kg', '가축재해보험', NULL, NULL, 'p.655', 655, 662, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-133', 'FORMULA', '젖소 8~12개월령 보험가액 (보간)', '산식: weaning_price + (mating_price - weaning_price) / 6 * (accident_month - 7)', '가축재해보험', NULL, NULL, 'p.656', 656, 663, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-134', 'FORMULA', '젖소 19~23개월령 보험가액 (보간)', '산식: mating_price + (first_birth_price - mating_price) / 6 * (accident_month - 18)', '가축재해보험', NULL, NULL, 'p.656', 656, 663, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-135', 'FORMULA', '젖소 32~39개월령 보험가액 (보간)', '산식: first_birth_price + (multi_birth_price - first_birth_price) / 9 * (accident_month - 31)', '가축재해보험', NULL, NULL, 'p.657', 657, 664, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-136', 'FORMULA', '젖소 56~66개월령 보험가액 (보간)', '산식: multi_birth_price + (old_birth_price - multi_birth_price) / 12 * (accident_month - 55)', '가축재해보험', NULL, NULL, 'p.657', 657, 664, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-137', 'FORMULA', '이용물 처분액 (도축장 정산자료)', '산식: carcass_price * 0.75', '가축재해보험', NULL, NULL, 'p.654', 654, 661, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-138', 'FORMULA', '이용물 처분액 (정산자료 없음)', '산식: carcass_weight * carcass_price_per_kg * 0.75', '가축재해보험', NULL, NULL, 'p.654', 654, 661, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-139', 'FORMULA', '종모돈 보험가액 (종빈돈 가액 20% 가산)', '산식: sow_price * 1.20', '가축재해보험', NULL, NULL, 'p.659', 659, 666, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-140', 'FORMULA', '110kg 비육돈 수취가격', '산식: pork_price_per_kg * 110 * 0.768', '가축재해보험', NULL, NULL, 'p.661', 661, 668, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-141', 'FORMULA', '비육돈 보험가액 (적용체중 선형보간)', '산식: piglet_price + (applied_weight - 30) * (pig_110kg_price - piglet_price) / 80', '가축재해보험', NULL, NULL, 'p.661', 661, 668, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-142', 'FORMULA', '산란계 20~70주 보험가액', '산식: max(egg_price - egg_production_cost, 10) * 0.70 * (550 - accident_age_days)', '가축재해보험', NULL, NULL, 'p.663', 663, 670, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-143', 'FORMULA', '돼지 질병위험보장 특약 보험가액', '산식: sow_count * 2.5 * piglet_price', '가축재해보험', NULL, NULL, 'p.672', 672, 679, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-144', 'FORMULA', '이익률 (축산휴지 특약)', '산식: max((avg_pig_price - operation_cost) / avg_pig_price, 0.165)', '가축재해보험', NULL, NULL, 'p.673', 673, 680, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-145', 'FORMULA', '축산휴지손해 보험가액', '산식: breeding_sow_count * 10 * avg_pig_price * profit_rate', '가축재해보험', NULL, NULL, 'p.674', 674, 681, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-146', 'FORMULA', '가축재해보험 지급보험금 (전부보험)', '산식: min(loss_amount, insurance_value) - deductible', '가축재해보험', NULL, NULL, 'p.677', 677, 684, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-147', 'FORMULA', '가축재해보험 지급보험금 (일부보험)', '산식: loss_amount * insurance_amount / insurance_value - deductible', '가축재해보험', NULL, NULL, 'p.677', 677, 684, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-148', 'FORMULA', '잔존보험가입금액', '산식: insurance_amount - paid_insurance', '가축재해보험', NULL, NULL, 'p.679', 679, 686, '제3장 가축재해보험 손해평가', '제3절 보험금 지급 및 심사', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-149', 'FORMULA', '축사부문 부보비율 80% 미달 지급보험금', '산식: loss_amount * insurance_amount / (insurance_value * 0.80)', '가축재해보험', NULL, NULL, 'p.666', 666, 673, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 10, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-150', 'FORMULA', '축사부문 자기부담금 (풍수설지진)', '산식: max(loss_amount * deductible_rate, 500000)', '가축재해보험', NULL, NULL, 'p.667', 667, 674, '제3장 가축재해보험 손해평가', '제1절 손해의 평가', 'BATCH-6', 2026, 9, 'draft');
INSERT OR IGNORE INTO knowledge_nodes (id, type, name, description, lv1_insurance, lv2_crop, lv3_investigation, page_ref, book_page, pdf_page, chapter, section, batch_id, version_year, truth_weight, status) VALUES ('F-151', 'FORMULA', '돼지 질병위험보장 특약 자기부담금', '산식: max(loss_amount * deductible_rate, 2000000)', '가축재해보험', NULL, NULL, 'p.672', 672, 679, '제3장 가축재해보험 손해평가', '제2절 특약의 손해평가', 'BATCH-6', 2026, 9, 'draft');

-- 2. formulas (21 rows, INSERT OR IGNORE — 기존 등록 row 보존)
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-131', '한우 1~6개월령 보험가액', 'calf_price * (0.5 if month_age < threshold_month else 1.0)', '{"calf_price":"전전월 전국산지평균 송아지 가격 number>=0","month_age":"사고 월령 integer>=1","threshold_month":"50% 적용 임계 (질병사고 3, 그외 2) integer"}', 'p.655', 'F-131', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-132', '한우 7개월+ 보험가액', 'weight_kg * price_per_kg', '{"weight_kg":"발육표준표 적용 체중 number>0","price_per_kg":"산지가격 적용범위표 kg당 금액 number>0"}', 'p.655', 'F-132', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-133', '젖소 8~12개월령 보험가액 (보간)', 'weaning_price + (mating_price - weaning_price) / 6 * (accident_month - 7)', '{"weaning_price":"분유떼기 암컷 가격 number>=0","mating_price":"수정단계 가격 number>0","accident_month":"사고 월령 integer 8..12"}', 'p.656', 'F-133', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-134', '젖소 19~23개월령 보험가액 (보간)', 'mating_price + (first_birth_price - mating_price) / 6 * (accident_month - 18)', '{"mating_price":"수정단계 가격 number","first_birth_price":"초산우 가격 number","accident_month":"사고 월령 integer 19..23"}', 'p.656', 'F-134', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-135', '젖소 32~39개월령 보험가액 (보간)', 'first_birth_price + (multi_birth_price - first_birth_price) / 9 * (accident_month - 31)', '{"first_birth_price":"초산우 가격 number","multi_birth_price":"다산우 가격 number","accident_month":"사고 월령 integer 32..39"}', 'p.657', 'F-135', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-136', '젖소 56~66개월령 보험가액 (보간)', 'multi_birth_price + (old_birth_price - multi_birth_price) / 12 * (accident_month - 55)', '{"multi_birth_price":"다산우 가격 number","old_birth_price":"노산우 가격 number","accident_month":"사고 월령 integer 56..66"}', 'p.657', 'F-136', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-137', '이용물 처분액 (정산자료)', 'carcass_price * 0.75', '{"carcass_price":"도축장발행 정산자료 지육금액 number>=0"}', 'p.654', 'F-137', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-138', '이용물 처분액 (정산자료 X)', 'carcass_weight * carcass_price_per_kg * 0.75', '{"carcass_weight":"도체 중량 (kg) number>0","carcass_price_per_kg":"축산물품질평가원 고시 등급별 전국평균 지육가격 (원/kg) number>0"}', 'p.654', 'F-138', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-139', '종모돈 보험가액', 'sow_price * 1.20', '{"sow_price":"종빈돈 보험가액 number>0"}', 'p.659', 'F-139', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-140', '110kg 비육돈 수취가격', 'pork_price_per_kg * 110 * 0.768', '{"pork_price_per_kg":"직전 5영업일 평균돈육대표가격 (전체, 탕박) number>0"}', 'p.661', 'F-140', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-141', '비육돈 보험가액 (선형보간)', 'piglet_price + (applied_weight - 30) * (pig_110kg_price - piglet_price) / 80', '{"piglet_price":"자돈가격 (30kg 기준) number>0","applied_weight":"적용체중 (kg) integer 35..105","pig_110kg_price":"110kg 비육돈 수취가격 (F-140 결과) number>0"}', 'p.661', 'F-141', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-142', '산란계 20~70주 보험가액', 'max(egg_price - egg_production_cost, 10) * 0.70 * (550 - accident_age_days)', '{"egg_price":"직전 5영업일 계란 1개 평균가격 (가중평균) number>0","egg_production_cost":"계란 1개 생산비 = 77 number=77","accident_age_days":"사고 일령 integer 1..550"}', 'p.663', 'F-142', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-143', '돼지 질병위험보장 특약 보험가액', 'sow_count * 2.5 * piglet_price', '{"sow_count":"모돈두수 integer>=1","piglet_price":"자돈가격 number>0"}', 'p.672', 'F-143', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-144', '이익률 (축산휴지)', 'max((avg_pig_price - operation_cost) / avg_pig_price, 0.165)', '{"avg_pig_price":"두당 비육돈 (100kg 기준) 평균가격 number>0","operation_cost":"통계청 발표 비육돈 평균경영비 number>=0"}', 'p.673', 'F-144', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-145', '축산휴지손해 보험가액', 'breeding_sow_count * 10 * avg_pig_price * profit_rate', '{"breeding_sow_count":"종빈돈 마리수 (후보돈/임신·분만·포유 제외) integer>=1","avg_pig_price":"두당 비육돈 평균가격 number>0","profit_rate":"이익률 (F-144 결과) number 0..1"}', 'p.674', 'F-145', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-146', '가축재해보험 지급보험금 (전부보험)', 'min(loss_amount, insurance_value) - deductible', '{"loss_amount":"손해액 number>=0","insurance_value":"보험가액 number>0","deductible":"자기부담금 number>=0"}', 'p.677', 'F-146', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-147', '가축재해보험 지급보험금 (일부보험)', 'loss_amount * insurance_amount / insurance_value - deductible', '{"loss_amount":"손해액 number>=0","insurance_amount":"보험가입금액 number>0","insurance_value":"보험가액 number>0","deductible":"자기부담금 number>=0"}', 'p.677', 'F-147', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-148', '잔존보험가입금액', 'insurance_amount - paid_insurance', '{"insurance_amount":"보험가입금액 number>0","paid_insurance":"기지급 보험금 number>=0"}', 'p.679', 'F-148', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-149', '축사부문 부보비율 80% 미달 지급보험금', 'loss_amount * insurance_amount / (insurance_value * 0.80)', '{"loss_amount":"손해액 number>=0","insurance_amount":"보험가입금액 number>0","insurance_value":"보험가액 number>0"}', 'p.666', 'F-149', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-150', '축사부문 자기부담금 (풍수설지진)', 'max(loss_amount * deductible_rate, 500000)', '{"loss_amount":"손해액 number>=0","deductible_rate":"자기부담비율 number 0..1"}', 'p.667', 'F-150', 2026);
INSERT OR IGNORE INTO formulas (id, name, equation_template, variables_schema, page_ref, node_id, version_year) VALUES ('F-151', '돼지 질병위험보장 특약 자기부담금', 'max(loss_amount * deductible_rate, 2000000)', '{"loss_amount":"손해액 number>=0","deductible_rate":"자기부담비율 number 0..1"}', 'p.672', 'F-151', 2026);

-- 3. constants (21 rows, INSERT OR IGNORE)
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-092', 'threshold', '한우 6개월령 경계 (송아지 가격 적용 상한)', '6', 6.0, '한우 6개월령 경계 (송아지 가격 적용 상한)', 'p.655', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-093', 'threshold', '한우 수컷 25개월 초과 적용 체중 (kg)', '655', 655.0, '한우 수컷 25개월 초과 적용 체중 (kg)', 'p.656', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-094', 'threshold', '한우 암컷 40개월 초과 적용 체중 (kg)', '470', 470.0, '한우 암컷 40개월 초과 적용 체중 (kg)', 'p.656', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-095', 'threshold', '육우 25개월 초과 적용 체중 (kg)', '600', 600.0, '육우 25개월 초과 적용 체중 (kg)', 'p.657', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-096', 'ratio', '한우/젖소 2개월 미만 50% 적용 비율', '0.5', 0.5, '한우/젖소 2개월 미만 50% 적용 비율', 'p.655', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-097', 'ratio', '이용물 처분액 적용율 (정산자료/X 공통)', '0.75', 0.75, '이용물 처분액 적용율 (정산자료/X 공통)', 'p.654', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-098', 'ratio', '종모돈 가산율 (종빈돈 대비)', '0.20', 0.2, '종모돈 가산율 (종빈돈 대비)', 'p.659', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-099', 'coefficient', '비육돈 110kg 지급육율', '0.768', 0.768, '비육돈 110kg 지급육율', 'p.661', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-100', 'threshold', '산란계 수명 일령', '550', 550.0, '산란계 수명 일령', 'p.663', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-101', 'ratio', '산란계 70% 적용 비율', '0.70', 0.7, '산란계 70% 적용 비율', 'p.663', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-102', 'coefficient', '산란계 계란 1개 생산비 (원)', '77', 77.0, '산란계 계란 1개 생산비 (원)', 'p.663', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-103', 'threshold', '축사부문 부보비율 80% 임계', '0.80', 0.8, '축사부문 부보비율 80% 임계', 'p.666', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-104', 'coefficient', '돼지 질병위험보장 특약 자돈가격 곱셈', '2.5', 2.5, '돼지 질병위험보장 특약 자돈가격 곱셈', 'p.672', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-105', 'coefficient', '축산휴지손해 곱셈 (10일 기준)', '10', 10.0, '축산휴지손해 곱셈 (10일 기준)', 'p.674', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-106', 'threshold', '축산휴지 이익률 하한', '0.165', 0.165, '축산휴지 이익률 하한', 'p.673', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-107', 'deductible', '축사부문 자기부담금 최저 (풍수설지진)', '500000', 500000.0, '축사부문 자기부담금 최저 (풍수설지진)', 'p.667', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-108', 'deductible', '돼지 질병위험보장 자기부담금 최저', '2000000', 2000000.0, '돼지 질병위험보장 자기부담금 최저', 'p.672', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-109', 'threshold', '육계 일령 한도 (40일 초과 시 2.3kg 적용)', '40', 40.0, '육계 일령 한도 (40일 초과 시 2.3kg 적용)', 'p.665', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-110', 'threshold', '토종닭 일령 한도 (84일 초과 시 2.8kg 적용)', '84', 84.0, '토종닭 일령 한도 (84일 초과 시 2.8kg 적용)', 'p.665', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-111', 'threshold', '오리 일령 한도 (45일 초과 시 3.5kg 적용)', '45', 45.0, '오리 일령 한도 (45일 초과 시 3.5kg 적용)', 'p.665', 2026);
INSERT OR IGNORE INTO constants (id, category, name, value, numeric_value, applies_to, page_ref, version_year) VALUES ('CONST-112', 'ratio', '잔존물처리비용 손해액 한도율', '0.10', 0.1, '잔존물처리비용 손해액 한도율', 'p.679', 2026);

-- 4. knowledge_edges (100 rows) — nodes 적재 후
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0001', 'INS-33', 'INS-34', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0002', 'INS-33', 'INS-35', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0003', 'INS-33', 'INS-36', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0004', 'INS-33', 'INS-37', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0005', 'INS-33', 'INS-38', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0006', 'INS-33', 'CONCEPT-114', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0007', 'INS-33', 'CONCEPT-115', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0008', 'INS-33', 'CONCEPT-116', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0009', 'INS-33', 'CONCEPT-117', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0010', 'INS-33', 'CONCEPT-124', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0011', 'INS-33', 'CONCEPT-125', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0012', 'CONCEPT-115', 'LAW-016', 'GOVERNED_BY', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0013', 'CONCEPT-116', 'LAW-018', 'GOVERNED_BY', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0014', 'INS-34', 'TERM-043', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0015', 'INS-34', 'TERM-044', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0016', 'INS-34', 'TERM-045', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0017', 'INS-34', 'TERM-046', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0018', 'INS-34', 'TERM-047', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0019', 'INS-34', 'TERM-048', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0020', 'INS-34', 'TERM-049', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0021', 'INS-34', 'CONCEPT-118', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0022', 'INS-34', 'CONCEPT-119', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0023', 'INS-34', 'CONCEPT-120', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0024', 'INS-34', 'CONCEPT-121', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0025', 'INS-34', 'F-131', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0026', 'INS-34', 'F-132', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0027', 'INS-34', 'F-133', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0028', 'INS-34', 'F-134', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0029', 'INS-34', 'F-135', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0030', 'INS-34', 'F-136', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0031', 'INS-34', 'F-137', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0032', 'INS-34', 'F-138', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0033', 'INS-34', 'INV-082', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0034', 'INS-34', 'INV-083', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0035', 'INS-35', 'TERM-050', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0036', 'INS-35', 'TERM-051', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0037', 'INS-35', 'TERM-052', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0038', 'INS-35', 'F-139', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0039', 'INS-35', 'F-140', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0040', 'INS-35', 'F-141', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0041', 'INS-36', 'TERM-053', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0042', 'INS-36', 'TERM-054', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0043', 'INS-36', 'TERM-055', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0044', 'INS-36', 'CONCEPT-122', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0045', 'INS-36', 'F-142', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0046', 'INS-37', 'TERM-056', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0047', 'INS-38', 'CONCEPT-123', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0048', 'INS-38', 'F-146', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0049', 'INS-38', 'F-147', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0050', 'INS-38', 'F-149', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0051', 'INS-38', 'F-150', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0052', 'INS-39', 'INS-34', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0053', 'INS-39', 'TERM-049', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0054', 'INS-40', 'INS-35', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0055', 'INS-40', 'TERM-052', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0056', 'INS-40', 'F-143', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0057', 'INS-40', 'F-151', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0058', 'INS-41', 'INS-35', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0059', 'INS-41', 'TERM-050', 'APPLIES_TO', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0060', 'INS-41', 'TERM-057', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0061', 'INS-41', 'CONCEPT-129', 'PREREQUISITE', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0062', 'INS-41', 'F-144', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0063', 'INS-41', 'F-145', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0064', 'INS-41', 'INV-084', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0065', 'INS-42', 'INS-35', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0066', 'INS-42', 'INS-36', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0067', 'INS-43', 'INS-35', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0068', 'INS-43', 'INS-36', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0069', 'F-145', 'F-144', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0070', 'F-141', 'F-140', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0071', 'INS-33', 'CONCEPT-126', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0072', 'INS-33', 'CONCEPT-127', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0073', 'INS-33', 'CONCEPT-128', 'DEFINED_AS', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0074', 'INS-33', 'F-148', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0075', 'INS-33', 'F-146', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0076', 'INS-33', 'F-147', 'USES_FORMULA', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0077', 'INS-33', 'INV-081', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0078', 'INS-34', 'INV-081', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0079', 'INS-35', 'INV-081', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0080', 'INS-36', 'INV-081', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0081', 'INS-37', 'INV-081', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0082', 'INS-38', 'INV-081', 'REQUIRES_INVESTIGATION', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0083', 'CONCEPT-125', 'LAW-017', 'GOVERNED_BY', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0084', 'INS-34', 'INS-33', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0085', 'INS-35', 'INS-33', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0086', 'INS-36', 'INS-33', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0087', 'INS-37', 'INS-33', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0088', 'INS-38', 'INS-33', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0089', 'F-150', 'F-146', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0090', 'F-151', 'F-146', 'DEPENDS_ON', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0091', 'INS-34', 'INS-26', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0092', 'INS-34', 'INS-09', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0093', 'INS-38', 'INS-25', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0094', 'CONCEPT-115', 'CONCEPT-007', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0095', 'CONCEPT-116', 'CONCEPT-008', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0096', 'CONCEPT-124', 'CONCEPT-002', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0097', 'CONCEPT-125', 'CONCEPT-021', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0098', 'F-146', 'F-08', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0099', 'F-147', 'F-09', 'SHARED_WITH', NULL);
INSERT OR IGNORE INTO knowledge_edges (id, from_node, to_node, edge_type, condition) VALUES ('EDGE-BATCH-6-0100', 'F-148', 'F-12', 'SHARED_WITH', NULL);

-- 검증 SQL (적용 후 진산님 직접 확인):
-- SELECT COUNT(*) FROM knowledge_nodes WHERE batch_id='BATCH-6'; -- expect: 70
-- SELECT COUNT(*) FROM knowledge_edges WHERE id LIKE 'EDGE-BATCH-6-%'; -- expect: 100
-- SELECT COUNT(*) FROM formulas WHERE id LIKE 'F-%'; -- expect: \u003E= 21 (기존 등록 합산)
